# Generated By: Claude Code (Claude Opus 4.7)
"""Entry point for `python -m agentpulse.tray` and `agentpulse-tray`."""

import argparse
import sys
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser(prog="agentpulse-tray")
    parser.add_argument(
        "--config",
        type=lambda s: Path(s).expanduser(),
        required=True,
        help="Path to config JSON file",
    )
    args = parser.parse_args()

    try:
        from agentpulse.tray.app import run

        sys.exit(run(config_path=args.config))
    except FileNotFoundError as exc:
        print(f"error: {exc}", file=sys.stderr)
        print("run: agentpulse init", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
