# Generated By: Claude Code (Claude Opus 4.7)
"""Tray menu action handlers."""

import subprocess
import sys
from pathlib import Path


def _startfile(path: str) -> None:
    """Indirection so tests can patch without requiring Windows.

    Dispatches to os.startfile on Windows; unused elsewhere.
    """
    import os

    os.startfile(path)  # type: ignore[attr-defined]  # Windows-only stdlib


def open_path(path: Path) -> None:
    """Open path in the system default handler."""
    if not path.exists():
        raise FileNotFoundError(path)
    if sys.platform == "win32":
        _startfile(str(path))
    else:
        subprocess.Popen(["xdg-open", str(path)])
