# Generated By: Claude Code (Claude Opus 4.7)
"""Tray application — pystray Icon wiring + lifecycle.

Stateless. The tray is a right-click menu for ops actions (open logs,
open config, stop service, restart service, quit) — no live status
display.
"""

import logging
import signal
import sys
import threading
from pathlib import Path

from agentpulse import pidfile
from agentpulse.tray import actions, supervisor

logger = logging.getLogger(__name__)

TRAY_PIDFILE_NAME = "agentpulse-tray"


class AlreadyRunningError(RuntimeError):
    """Another tray instance is already running."""


def acquire_singleton() -> None:
    """Prevent a second tray from starting."""
    existing = pidfile.read_pid(TRAY_PIDFILE_NAME)
    if existing is not None and pidfile.is_process_ours(
        existing, must_contain="agentpulse"
    ):
        raise AlreadyRunningError(
            f"tray already running (pid={existing}); "
            f"quit it from the system tray or kill the process"
        )
    pidfile.write_pid(TRAY_PIDFILE_NAME)


def release_singleton() -> None:
    pidfile.remove_pid(TRAY_PIDFILE_NAME)


def install_shutdown_handlers(stop_event: threading.Event) -> None:
    """Make SIGINT/SIGTERM set `stop_event` so main can tear down cleanly."""

    def _handler(signum: int, frame: object) -> None:
        logger.info("received signal %d; stopping tray", signum)
        stop_event.set()

    for sig_name in ("SIGINT", "SIGTERM", "SIGBREAK"):
        sig = getattr(signal, sig_name, None)
        if sig is None:
            continue
        try:
            signal.signal(sig, _handler)
        except (ValueError, OSError):
            pass


def _load_icon_image():  # type: ignore[no-untyped-def]
    from PIL import Image, ImageDraw

    img = Image.new("RGBA", (64, 64), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    draw.ellipse((8, 8, 56, 56), fill=(60, 200, 90, 255))
    return img


def _build_menu(*, config_path: Path, log_path: Path):  # type: ignore[no-untyped-def]
    import pystray  # type: ignore[import-untyped]

    def _quit(icon, _):  # type: ignore[no-untyped-def]
        icon.stop()

    return pystray.Menu(
        pystray.MenuItem("Open logs", lambda *_: actions.open_path(log_path)),
        pystray.MenuItem("Open config", lambda *_: actions.open_path(config_path)),
        pystray.Menu.SEPARATOR,
        pystray.MenuItem("Stop service", lambda *_: supervisor.stop_service()),
        pystray.MenuItem("Restart service", lambda *_: supervisor.restart_service()),
        pystray.Menu.SEPARATOR,
        pystray.MenuItem("Quit tray", _quit),
    )


def run(*, config_path: Path) -> int:  # pragma: no cover — GUI blocking
    import pystray  # type: ignore[import-untyped]

    from agentpulse.config import get_settings, set_config_path

    set_config_path(config_path=config_path)
    settings = get_settings()
    pidfile.set_base_dir(settings.pidfile_dir)

    try:
        acquire_singleton()
    except AlreadyRunningError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    try:
        supervisor.configure(config_path=config_path)

        stop_event = threading.Event()
        install_shutdown_handlers(stop_event)

        icon = pystray.Icon(
            "agentpulse",
            icon=_load_icon_image(),
            title="AgentPulse",
            menu=_build_menu(config_path=config_path, log_path=settings.log_file),
        )

        def _signal_watchdog() -> None:
            while not stop_event.wait(timeout=0.5):
                pass
            try:
                icon.stop()
            except Exception:
                logger.exception("icon.stop failed")

        threading.Thread(target=_signal_watchdog, daemon=True).start()

        try:
            icon.run()
        finally:
            stop_event.set()
        return 0
    finally:
        release_singleton()
