# Generated By: Claude Code (Claude Opus 4.7)
"""Tray application — pystray Icon wiring + lifecycle."""

import asyncio
import logging
import threading
from pathlib import Path

from agentpulse.tray import actions, supervisor
from agentpulse.tray.state import TrayState
from agentpulse.tray.ws_client import run_forever

logger = logging.getLogger(__name__)


def _load_icon_image(*, connected: bool):  # type: ignore[no-untyped-def]
    from PIL import Image, ImageDraw

    img = Image.new("RGBA", (64, 64), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    color = (60, 200, 90, 255) if connected else (200, 60, 60, 255)
    draw.ellipse((8, 8, 56, 56), fill=color)
    return img


def _build_menu(  # type: ignore[no-untyped-def]
    *, state: TrayState, config_path: Path, log_path: Path
):
    import pystray  # type: ignore[import-untyped]

    def _quit(icon, _):  # type: ignore[no-untyped-def]
        icon.stop()

    return pystray.Menu(
        pystray.MenuItem(lambda _: state.status_label(), None, enabled=False),
        pystray.Menu.SEPARATOR,
        pystray.MenuItem("Open logs", lambda *_: actions.open_path(log_path)),
        pystray.MenuItem("Open config", lambda *_: actions.open_path(config_path)),
        pystray.Menu.SEPARATOR,
        pystray.MenuItem("Stop service", lambda *_: supervisor.stop_service()),
        pystray.MenuItem("Restart service", lambda *_: supervisor.restart_service()),
        pystray.Menu.SEPARATOR,
        pystray.MenuItem("Quit tray", _quit),
    )


def _start_ws_thread(
    state: TrayState, *, host: str, port: int, stop_event: threading.Event
) -> threading.Thread:
    def _runner() -> None:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        async_stop = asyncio.Event()

        def _watch_stop() -> None:
            stop_event.wait()
            loop.call_soon_threadsafe(async_stop.set)

        watcher = threading.Thread(target=_watch_stop, daemon=True)
        watcher.start()
        try:
            loop.run_until_complete(
                run_forever(state, host=host, port=port, stop_event=async_stop)
            )
        finally:
            loop.close()

    thread = threading.Thread(target=_runner, daemon=True)
    thread.start()
    return thread


def run(*, config_path: Path) -> int:  # pragma: no cover — GUI blocking
    import pystray  # type: ignore[import-untyped]

    from agentpulse.config import get_settings, set_config_path

    set_config_path(config_path=config_path)
    settings = get_settings()

    state = TrayState()
    stop_event = threading.Event()
    _start_ws_thread(
        state, host=settings.host, port=settings.port, stop_event=stop_event
    )

    icon = pystray.Icon(
        "agentpulse",
        icon=_load_icon_image(connected=False),
        title=state.tooltip(),
        menu=_build_menu(
            state=state, config_path=config_path, log_path=settings.log_file
        ),
    )

    def _refresh() -> None:
        while not stop_event.is_set():
            try:
                icon.icon = _load_icon_image(connected=state.connected)
                icon.title = state.tooltip()
                icon.update_menu()
            except Exception:  # noqa: BLE001
                logger.exception("icon refresh failed")
            stop_event.wait(timeout=2.0)

    threading.Thread(target=_refresh, daemon=True).start()

    try:
        icon.run()
    finally:
        stop_event.set()
    return 0
