# Generated By: Claude Code (Claude Opus 4.7)
"""Tray state container with thread-safe accessors."""

import threading
from dataclasses import dataclass, field


@dataclass
class TrayState:
    connected: bool = False
    active_sessions: int = 0
    last_error: str | None = None
    _lock: threading.Lock = field(default_factory=threading.Lock, repr=False)

    def set_connected(self, value: bool) -> None:
        with self._lock:
            self.connected = value

    def set_active_sessions(self, value: int) -> None:
        with self._lock:
            self.active_sessions = max(0, value)

    def set_error(self, msg: str | None) -> None:
        with self._lock:
            self.last_error = msg

    def handle_message(self, msg: dict) -> None:
        msg_type = msg.get("type")
        with self._lock:
            if msg_type == "session_discovered":
                self.active_sessions += 1
            elif msg_type in ("session_ended", "session_cleared"):
                self.active_sessions = max(0, self.active_sessions - 1)

    def status_label(self) -> str:
        with self._lock:
            if not self.connected:
                return "Stopped"
            return f"Running · {self.active_sessions} active sessions"

    def tooltip(self) -> str:
        with self._lock:
            status = "Running" if self.connected else "Stopped"
            return f"AgentPulse - {status} - {self.active_sessions} active"
