# Generated By: Claude Code (Claude Opus 4.7)
"""Stop / restart the AgentPulse service from the tray app.

Linux  : shells out to `systemctl --user stop|restart agentpulse`.
Windows: terminates the running agentpulse.exe via psutil, then (on
         restart) relaunches the pipx-installed executable.
"""

import logging
import shutil
import subprocess
import sys
from pathlib import Path

logger = logging.getLogger(__name__)

SYSTEMD_UNIT = "agentpulse"
WINDOWS_PROCESS_NAMES = ("agentpulse.exe", "agentpulse")


def _find_service_processes() -> list:
    import psutil

    hits = []
    for proc in psutil.process_iter(attrs=["name", "cmdline"]):
        try:
            name = (proc.info.get("name") or "").lower()
            cmdline = " ".join(proc.info.get("cmdline") or []).lower()
            if name in WINDOWS_PROCESS_NAMES or "agentpulse" in cmdline:
                hits.append(proc)
        except Exception:  # noqa: BLE001
            continue
    return hits


def _launch_windows() -> None:
    exe = shutil.which("agentpulse") or str(
        Path.home() / ".local" / "bin" / "agentpulse.exe"
    )
    config = Path.home() / ".claude" / "agentpulse" / "config.json"
    subprocess.Popen([exe, "--config", str(config)])


def stop_service() -> None:
    if sys.platform == "linux":
        subprocess.run(["systemctl", "--user", "stop", SYSTEMD_UNIT], check=False)
        return
    if sys.platform == "win32":
        for proc in _find_service_processes():
            try:
                proc.terminate()
            except Exception:  # noqa: BLE001
                logger.exception("terminate failed")
        return
    logger.warning("unsupported platform: %s", sys.platform)


def restart_service() -> None:
    if sys.platform == "linux":
        subprocess.run(["systemctl", "--user", "restart", SYSTEMD_UNIT], check=False)
        return
    if sys.platform == "win32":
        for proc in _find_service_processes():
            try:
                proc.terminate()
            except Exception:  # noqa: BLE001
                logger.exception("terminate failed")
        _launch_windows()
        return
    logger.warning("unsupported platform: %s", sys.platform)
