# Generated By: Claude Code (Claude Opus 4.7)
"""WebSocket client loop for the tray icon.

Seeds active-session count via GET /api/v1/summary, then listens on the
/ws stream and updates TrayState on each message. Reconnects with
exponential backoff on disconnect.
"""

import asyncio
import json
import logging

from agentpulse.tray.state import TrayState

logger = logging.getLogger(__name__)


def _make_http_client():  # type: ignore[no-untyped-def]
    """Factory for httpx.AsyncClient — patched in tests."""
    import httpx

    return httpx.AsyncClient(timeout=5.0)


def _backoff(attempt: int) -> float:
    """Exponential backoff capped at 30s: 1, 2, 4, 8, 16, 30, 30, ..."""
    return min(30.0, 2.0**attempt)


def apply_bootstrap(state: TrayState, *, summary: dict) -> None:
    state.set_active_sessions(int(summary.get("active_sessions", 0)))


async def seed_from_summary(state: TrayState, *, base_url: str) -> bool:
    """Fetch /api/v1/summary once. Returns True on success."""
    try:
        async with _make_http_client() as client:
            resp = await client.get(f"{base_url}/api/v1/summary")
            if resp.status_code != 200:
                state.set_error(f"summary http {resp.status_code}")
                return False
            apply_bootstrap(state, summary=resp.json())
            return True
    except Exception as exc:  # noqa: BLE001
        state.set_error(str(exc))
        return False


async def _listen_once(
    state: TrayState, *, ws_url: str, stop_event: asyncio.Event
) -> None:
    """One connect + receive loop. Returns on disconnect or stop."""
    import websockets

    try:
        async with websockets.connect(ws_url) as ws:
            state.set_connected(True)
            state.set_error(None)
            while not stop_event.is_set():
                recv = asyncio.create_task(ws.recv())
                wait_stop = asyncio.create_task(stop_event.wait())
                done, pending = await asyncio.wait(
                    {recv, wait_stop}, return_when=asyncio.FIRST_COMPLETED
                )
                for p in pending:
                    p.cancel()
                if wait_stop in done:
                    return
                try:
                    raw = recv.result()
                except Exception:  # noqa: BLE001
                    return
                try:
                    msg = json.loads(raw)
                except json.JSONDecodeError:
                    continue
                state.handle_message(msg)
    except Exception as exc:  # noqa: BLE001
        state.set_error(str(exc))
    finally:
        state.set_connected(False)


async def run_forever(
    state: TrayState, *, host: str, port: int, stop_event: asyncio.Event
) -> None:
    """Seed + listen + reconnect loop. Returns when stop_event is set."""
    base_url = f"http://{host}:{port}"
    ws_url = f"ws://{host}:{port}/ws"
    attempt = 0
    while not stop_event.is_set():
        await seed_from_summary(state, base_url=base_url)
        await _listen_once(state, ws_url=ws_url, stop_event=stop_event)
        if stop_event.is_set():
            return
        delay = _backoff(attempt)
        attempt = min(attempt + 1, 6)
        try:
            await asyncio.wait_for(stop_event.wait(), timeout=delay)
            return
        except asyncio.TimeoutError:
            pass
