# Generated By: Claude Code (Claude Opus 4.6)
"""FastAPI application factory."""

import asyncio
import logging
from contextlib import asynccontextmanager
from typing import AsyncIterator

import aiosqlite
from fastapi import FastAPI

from agentpulse import __version__
from agentpulse import pidfile
from agentpulse.api.claude import router as claude_api_router
from agentpulse.api.sessions import router as sessions_router
from agentpulse.api.v2 import router as v2_router
from agentpulse.api.v2 import ws_router as v2_ws_router
from agentpulse.api.v2.throttle import hook_throttle
from agentpulse.config import get_settings
from agentpulse.db import close_db, init_db
from agentpulse.platforms.claude.discovery import run_discovery_tick
from agentpulse.platforms.claude.hooks import router as hooks_router
from agentpulse.platforms.claude.pid_watcher import run_pid_watcher_tick
from agentpulse.ui import router as ui_router
from agentpulse.websocket import router as ws_router

SERVICE_PIDFILE_NAME = "agentpulse"

logger = logging.getLogger(__name__)


class _SuppressConnectionReset(logging.Filter):
    """Filter out ConnectionResetError from asyncio's ProactorEventLoop.

    Hook relay clients disconnect before reading the full response,
    which triggers a harmless ConnectionResetError on Windows.
    """

    def filter(self, record: logging.LogRecord) -> bool:
        if record.exc_info and record.exc_info[1]:
            if isinstance(record.exc_info[1], ConnectionResetError):
                return False
        return "ConnectionResetError" not in record.getMessage()


logging.getLogger("asyncio").addFilter(_SuppressConnectionReset())

# Suppress noisy third-party debug logging
logging.getLogger("aiosqlite").setLevel(logging.WARNING)


async def _discovery_loop(
    db: aiosqlite.Connection,
    *,
    interval: int,
) -> None:
    """Background task: run session discovery on a timer."""
    while True:
        try:
            await run_discovery_tick(db)
        except Exception:
            logger.exception("discovery tick failed")
        await asyncio.sleep(interval)


async def _pid_watcher_loop(
    db: aiosqlite.Connection,
    *,
    interval: int,
) -> None:
    """Background task: v2 PID death detection on a timer."""
    while True:
        try:
            await run_pid_watcher_tick(db)
            hook_throttle.sweep_stale()
        except Exception:
            logger.exception("pid watcher tick failed")
        await asyncio.sleep(interval)


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    """Manage startup and shutdown."""
    settings = get_settings()
    hook_throttle._debounce_seconds = settings.broadcast_debounce_ms / 1000.0
    logger.info(
        "starting host=%s port=%d db=%s log_level=%s"
        " discovery_interval=%ds fetch_limits=%s broadcast_debounce=%dms",
        settings.host,
        settings.port,
        settings.db_path,
        settings.log_level,
        settings.discovery_interval_seconds,
        settings.fetch_limits,
        settings.broadcast_debounce_ms,
    )
    try:
        db = await init_db(db_path=settings.db_path)
    except Exception:
        logger.exception("Failed to initialize database at %s", settings.db_path)
        raise

    pidfile.set_base_dir(settings.pidfile_dir)
    try:
        pidfile.write_pid(SERVICE_PIDFILE_NAME)
    except OSError:
        logger.exception(
            "failed to write pidfile %s",
            pidfile.pidfile_path(SERVICE_PIDFILE_NAME),
        )
        await close_db()
        raise
    logger.info("wrote pidfile %s", pidfile.pidfile_path(SERVICE_PIDFILE_NAME))

    discovery_task = asyncio.create_task(
        _discovery_loop(db, interval=settings.discovery_interval_seconds)
    )
    pid_watcher_task = asyncio.create_task(
        _pid_watcher_loop(db, interval=settings.discovery_interval_seconds)
    )
    logger.info(
        "discovery + pid watcher loops started interval=%ds",
        settings.discovery_interval_seconds,
    )

    try:
        yield
    finally:
        logger.info("shutting down")
        hook_throttle.shutdown()
        discovery_task.cancel()
        pid_watcher_task.cancel()
        for task in (discovery_task, pid_watcher_task):
            try:
                await asyncio.wait_for(asyncio.shield(task), timeout=3.0)
            except (asyncio.CancelledError, asyncio.TimeoutError):
                pass
        await close_db()
        pidfile.remove_pid(SERVICE_PIDFILE_NAME)


def create_app() -> FastAPI:
    """Create and configure the FastAPI application."""
    app = FastAPI(
        title="AgentPulse",
        version=__version__,
        lifespan=lifespan,
    )
    app.include_router(hooks_router)
    app.include_router(sessions_router)
    app.include_router(claude_api_router)
    app.include_router(v2_router)
    app.include_router(v2_ws_router)
    app.include_router(ws_router)
    app.include_router(ui_router)
    return app
