# Generated By: Claude Code (Claude Opus 4.6)
"""FastAPI application factory."""

import asyncio
import logging
from contextlib import asynccontextmanager
from typing import AsyncIterator

import aiosqlite
from fastapi import FastAPI

from agentpulse import __version__
from agentpulse.api.claude import router as claude_api_router
from agentpulse.api.sessions import router as sessions_router
from agentpulse.config import get_settings
from agentpulse.db import close_db, init_db
from agentpulse.platforms.claude.discovery import run_discovery_tick
from agentpulse.platforms.claude.hooks import router as hooks_router
from agentpulse.websocket import router as ws_router

logger = logging.getLogger(__name__)


class _SuppressConnectionReset(logging.Filter):
    """Filter out ConnectionResetError from asyncio's ProactorEventLoop.

    Hook relay clients disconnect before reading the full response,
    which triggers a harmless ConnectionResetError on Windows.
    """

    def filter(self, record: logging.LogRecord) -> bool:
        if record.exc_info and record.exc_info[1]:
            if isinstance(record.exc_info[1], ConnectionResetError):
                return False
        return "ConnectionResetError" not in record.getMessage()


logging.getLogger("asyncio").addFilter(_SuppressConnectionReset())


async def _discovery_loop(
    db: aiosqlite.Connection,
    *,
    interval: int,
) -> None:
    """Background task: run session discovery on a timer."""
    while True:
        try:
            await run_discovery_tick(db)
        except Exception:
            logger.exception("discovery tick failed")
        await asyncio.sleep(interval)


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    """Manage startup and shutdown."""
    settings = get_settings()
    logger.info(
        "starting host=%s port=%d db=%s log_level=%s discovery_interval=%ds",
        settings.host,
        settings.port,
        settings.db_path,
        settings.log_level,
        settings.discovery_interval_seconds,
    )
    db = await init_db(db_path=settings.db_path)

    discovery_task = asyncio.create_task(
        _discovery_loop(db, interval=settings.discovery_interval_seconds)
    )
    logger.info(
        "discovery loop started interval=%ds", settings.discovery_interval_seconds
    )

    yield

    logger.info("shutting down")
    discovery_task.cancel()
    try:
        await asyncio.wait_for(asyncio.shield(discovery_task), timeout=3.0)
    except (asyncio.CancelledError, asyncio.TimeoutError):
        pass
    await close_db()


def create_app() -> FastAPI:
    """Create and configure the FastAPI application."""
    app = FastAPI(
        title="AgentPulse",
        version=__version__,
        lifespan=lifespan,
    )
    app.include_router(hooks_router)
    app.include_router(sessions_router)
    app.include_router(claude_api_router)
    app.include_router(ws_router)
    return app
