# Generated By: Claude Code (Claude Opus 4.7)
"""Shared helpers for first-run setup."""

import shutil
from pathlib import Path


def ensure_config(*, target: Path, example: Path) -> bool:
    """Copy example to target if target doesn't exist.

    Returns True if a new file was created, False if the target already existed.
    Raises FileNotFoundError if example doesn't exist.
    """
    if not example.exists():
        raise FileNotFoundError(f"example config not found: {example}")
    if target.exists():
        return False
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(example, target)
    return True
