# Generated By: Claude Code (Claude Opus 4.7)
"""`agentpulse init` subcommand — one-shot config scaffolder."""

import argparse
from pathlib import Path

from agentpulse.bootstrap import ensure_config

DEFAULT_TARGET = Path(".claude") / "agentpulse" / "config.json"
_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
_BUNDLED_EXAMPLE = _PROJECT_ROOT / "config.example.json"


def init_main(*, argv: list[str], example: Path | None = None) -> int:
    """Create default config if missing. Returns exit code."""
    parser = argparse.ArgumentParser(prog="agentpulse init")
    parser.add_argument(
        "--config",
        type=Path,
        default=None,
        help="Path to write config.json (default: ~/.claude/agentpulse/config.json)",
    )
    args = parser.parse_args(argv)

    target = args.config or (Path.home() / DEFAULT_TARGET)
    example_path = example or _BUNDLED_EXAMPLE

    created = ensure_config(target=target, example=example_path)
    if created:
        print(f"created {target}")
        print("edit the file to customize host/port/fetch_limits.")
    else:
        print(f"config already exists at {target}")
    return 0
