# Generated By: Claude Code (Claude Opus 4.6)
"""Configuration, paths, and defaults for AgentPulse."""

import json
import platform
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

IS_WINDOWS = platform.system() == "Windows"
IS_LINUX = platform.system() == "Linux"

SUBPROCESS_FLAGS: int = getattr(subprocess, "CREATE_NO_WINDOW", 0)

CLAUDE_HOME = Path.home() / ".claude"
SESSIONS_DIR = CLAUDE_HOME / "sessions"

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 17385
DEFAULT_DB_PATH = CLAUDE_HOME / "agentpulse" / "agentpulse.db"
DEFAULT_LOG_FILE = CLAUDE_HOME / "agentpulse" / "agentpulse.log"
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_DISCOVERY_INTERVAL_SECONDS = 5


@dataclass
class Settings:
    """AgentPulse service settings. Loaded exclusively from a config file."""

    host: str = DEFAULT_HOST
    port: int = DEFAULT_PORT
    db_path: Path = field(default_factory=lambda: DEFAULT_DB_PATH)
    log_file: Path = field(default_factory=lambda: DEFAULT_LOG_FILE)
    log_level: str = DEFAULT_LOG_LEVEL
    discovery_interval_seconds: int = DEFAULT_DISCOVERY_INTERVAL_SECONDS
    fetch_limits: bool = False

    @classmethod
    def from_config(cls, *, config_path: Path) -> "Settings":
        """Load settings from a JSON config file."""
        data: dict = {}
        resolved = config_path.expanduser()
        if resolved.exists():
            try:
                raw = json.loads(resolved.read_text(encoding="utf-8"))
                if isinstance(raw, dict):
                    data = raw
            except (json.JSONDecodeError, OSError):
                pass

        db_path_str = data.get("db_path")
        db_path = Path(db_path_str).expanduser() if db_path_str else DEFAULT_DB_PATH

        log_file_str = data.get("log_file")
        log_file = Path(log_file_str).expanduser() if log_file_str else DEFAULT_LOG_FILE

        log_level = data.get("log_level", DEFAULT_LOG_LEVEL)

        return cls(
            host=data.get("host", DEFAULT_HOST),
            port=int(data.get("port", DEFAULT_PORT)),
            db_path=db_path,
            log_file=log_file,
            log_level=str(log_level).upper(),
            discovery_interval_seconds=int(
                data.get(
                    "discovery_interval_seconds",
                    DEFAULT_DISCOVERY_INTERVAL_SECONDS,
                )
            ),
            fetch_limits=str(data.get("fetch_limits", "")).lower()
            in ("1", "true", "yes"),
        )


_settings: Settings | None = None
_config_path: Path | None = None


def set_config_path(*, config_path: Path) -> None:
    """Set the config file path. Must be called before get_settings()."""
    global _config_path
    _config_path = config_path


def get_settings() -> Settings:
    """Return the global settings singleton."""
    global _settings
    if _settings is None:
        if _config_path is None:
            raise RuntimeError("Config path not set. Call set_config_path() first.")
        _settings = Settings.from_config(config_path=_config_path)
    return _settings


def reset_settings() -> None:
    """Reset settings singleton (for testing)."""
    global _settings
    _settings = None
