# Generated By: Claude Code (Claude Opus 4.6)
"""SQLite connection management."""

from pathlib import Path

import aiosqlite

from agentpulse.platforms.claude.schema import create_tables

_db: aiosqlite.Connection | None = None


async def init_db(*, db_path: Path) -> aiosqlite.Connection:
    """Open the SQLite database, enable WAL mode, and create tables."""
    global _db

    db_path.parent.mkdir(parents=True, exist_ok=True)
    _db = await aiosqlite.connect(str(db_path))
    await _db.execute("PRAGMA journal_mode=WAL")
    _db.row_factory = aiosqlite.Row
    await create_tables(_db)
    return _db


async def get_db() -> aiosqlite.Connection:
    """Return the active database connection."""
    if _db is None:
        raise RuntimeError("Database not initialized. Call init_db first.")
    return _db


async def close_db() -> None:
    """Close the database connection."""
    global _db
    if _db is not None:
        await _db.close()
        _db = None
