# Generated By: Claude Code (Claude Opus 4.6)
"""Normalized (cross-platform) response models."""

from pydantic import BaseModel


class SessionResponse(BaseModel):
    """Normalized session for cross-platform queries."""

    session_id: str
    platform: str
    pid: int
    cwd: str
    entrypoint: str
    started_at: int
    last_event: str | None = None
    last_tool: str | None = None
    last_event_at: float | None = None
    pid_alive: bool = True
    ended_at: float | None = None
    branch: str = ""
    source_system: str = ""
    cost_usd: float | None = None
    context_used_pct: float | None = None
    model_name: str | None = None
    total_input_tokens: int | None = None
    total_output_tokens: int | None = None
    lines_added: int | None = None
    lines_removed: int | None = None
    agent_count: int = 0
    derived_state: str | None = None


class AgentResponse(BaseModel):
    """Normalized agent."""

    agent_id: str
    session_id: str
    platform: str
    agent_type: str = ""
    last_event: str | None = None
    last_tool: str | None = None
    last_event_at: float | None = None
    started_at: float | None = None
    ended_at: float | None = None
    derived_state: str | None = None


class SessionDetailResponse(BaseModel):
    """Session with embedded agents."""

    session_id: str
    platform: str
    pid: int
    cwd: str
    entrypoint: str
    started_at: int
    last_event: str | None = None
    last_tool: str | None = None
    last_event_at: float | None = None
    pid_alive: bool = True
    ended_at: float | None = None
    branch: str = ""
    source_system: str = ""
    cost_usd: float | None = None
    context_used_pct: float | None = None
    model_name: str | None = None
    total_input_tokens: int | None = None
    total_output_tokens: int | None = None
    lines_added: int | None = None
    lines_removed: int | None = None
    agent_count: int = 0
    derived_state: str | None = None
    agents: list[AgentResponse] = []


class EventResponse(BaseModel):
    """Normalized event."""

    id: int
    session_id: str
    platform: str
    agent_id: str | None = None
    event_name: str
    tool_name: str | None = None
    cwd: str = ""
    received_at: float


class SummaryResponse(BaseModel):
    """Aggregate stats across all platforms."""

    active_sessions: int = 0
    state_breakdown: dict[str, int] = {}
    total_agents: int = 0
    limits: dict | None = None


class WebSocketMessage(BaseModel):
    """Real-time event pushed via WebSocket."""

    type: str
    platform: str
    session_id: str
    event_name: str | None = None
    tool_name: str | None = None
    agent_id: str | None = None
    cwd: str | None = None
    timestamp: float
