# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""PID files for identifying AgentPulse processes precisely.

Before this existed, the tray supervisor matched any process whose
command line contained the string "agentpulse" and terminated it,
which would also kill VS Code (workspace folder path), git bash
running in the repo, the tray itself, etc. The pidfile pins the
target to exactly one PID written by the process itself at startup.
"""

import logging
import os
from pathlib import Path

logger = logging.getLogger(__name__)

_BASE_DIR = Path.home() / ".claude" / "agentpulse"


def pidfile_path(name: str) -> Path:
    return _BASE_DIR / f"{name}.pid"


def write_pid(name: str, *, pid: int | None = None) -> Path:
    """Write `pid` (or os.getpid()) to the named pidfile. Creates dir if needed."""
    path = pidfile_path(name)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(str(pid if pid is not None else os.getpid()))
    return path


def read_pid(name: str) -> int | None:
    """Return PID from file, or None if missing/corrupt."""
    path = pidfile_path(name)
    try:
        return int(path.read_text().strip())
    except (FileNotFoundError, ValueError):
        return None


def remove_pid(name: str) -> None:
    """Remove the named pidfile. Idempotent."""
    try:
        pidfile_path(name).unlink()
    except FileNotFoundError:
        pass


def is_process_ours(pid: int, *, must_contain: str = "agentpulse") -> bool:
    """Verify `pid` exists AND looks like one of ours.

    A process is considered ours if either:
    - the executable name starts with `must_contain` (the pipx shim,
      e.g. ``agentpulse.exe``), or
    - the executable is a Python interpreter AND the cmdline runs the
      matching module (``-m agentpulse`` or ``agentpulse/__main__.py``).

    Critically, we do NOT match on the mere presence of `must_contain`
    anywhere in the cmdline — that would treat VS Code opened on a
    folder named "agentpulse", git bash with that cwd, Claude Code
    running in the repo, etc. as ours.
    """
    try:
        import psutil
    except ImportError:
        return False

    try:
        proc = psutil.Process(pid)
        name = (proc.name() or "").lower()
        cmdline = [str(c) for c in (proc.cmdline() or [])]
    except (psutil.NoSuchProcess, psutil.AccessDenied, psutil.ZombieProcess):
        return False

    needle = must_contain.lower()

    # Exe-name match (e.g. "agentpulse.exe" shim from pipx)
    if name.startswith(needle):
        return True

    # python -m <module> form
    if "python" in name:
        joined = " ".join(c.lower() for c in cmdline)
        if f"-m {needle}" in joined:
            return True
        # Direct __main__.py invocation (.../agentpulse/__main__.py)
        for token in cmdline:
            low = token.lower().replace("\\", "/")
            if low.endswith(f"/{needle}/__main__.py"):
                return True
            if low.endswith(f"/{needle}/tray/__main__.py"):
                return True

    return False
