# Generated By: Claude Code (Claude Opus 4.6 (1M context))
"""Global cost, token, and activity aggregation for the dashboard.

Cost data comes from the v2 sessions API (``get_sessions``), which
handles session-cumulative cost_usd, --resume baselines, and counter
resets. Each session carries ``cost_by_day`` — daily deltas that sum
to the session's total_cost_usd.

Token counts come from the v2 processes API (``get_processes``) —
process-lifetime totals attributed to the last active day.

Activity data (session_count, message_count) is not yet on either
projection, so it still queries ``claude_log_hooks`` directly.
"""

from datetime import date

import aiosqlite

from agentpulse.api.v2.queries.processes import get_processes
from agentpulse.api.v2.queries.sessions import get_sessions


def _empty_row(day: str, *, cwd: str | None = None) -> dict:
    row: dict = {
        "day": day,
        "session_count": 0,
        "message_count": 0,
        "total_tokens": 0,
        "total_cost_usd": 0.0,
    }
    if cwd is not None:
        row["cwd"] = cwd
    return row


async def _activity_by_day(db: aiosqlite.Connection) -> dict[str, dict]:
    cursor = await db.execute("""
        SELECT
            date(received_at, 'unixepoch', 'localtime') AS day,
            COUNT(DISTINCT session_id) AS session_count,
            SUM(CASE WHEN event_name = 'Stop' AND agent_id IS NULL
                THEN 1 ELSE 0 END) * 2 AS message_count
        FROM claude_log_hooks
        GROUP BY day
        """)
    return {
        r["day"]: {
            "session_count": int(r["session_count"]),
            "message_count": int(r["message_count"]),
        }
        for r in await cursor.fetchall()
    }


async def _activity_by_day_cwd(
    db: aiosqlite.Connection,
) -> dict[tuple[str, str], dict]:
    cursor = await db.execute("""
        SELECT
            date(received_at, 'unixepoch', 'localtime') AS day,
            cwd,
            COUNT(DISTINCT session_id) AS session_count,
            SUM(CASE WHEN event_name = 'Stop' AND agent_id IS NULL
                THEN 1 ELSE 0 END) * 2 AS message_count
        FROM claude_log_hooks
        GROUP BY day, cwd
        """)
    return {
        (r["day"], r["cwd"]): {
            "session_count": int(r["session_count"]),
            "message_count": int(r["message_count"]),
        }
        for r in await cursor.fetchall()
    }


def _process_token_day(proc: dict) -> str | None:
    """Day to attribute a process's token snapshot to."""
    cost_by_day: dict[str, float] = proc.get("cost_by_day") or {}
    if cost_by_day:
        return max(cost_by_day.keys())
    last_activity: float | None = proc.get("last_activity_at")
    if last_activity is not None:
        return date.fromtimestamp(last_activity).isoformat()
    return None


async def costs_by_day(db: aiosqlite.Connection) -> list[dict]:
    """Summary metrics per day (server local time).

    Returns rows ordered by ``day`` descending. Each row has ``day``,
    ``session_count``, ``message_count``, ``total_tokens``,
    ``total_cost_usd``.
    """
    sessions = await get_sessions(db)
    processes = await get_processes(db)

    merged: dict[str, dict] = {}
    for sess in sessions:
        for day, cost in (sess.get("cost_by_day") or {}).items():
            if day not in merged:
                merged[day] = _empty_row(day)
            merged[day]["total_cost_usd"] += cost

    for proc in processes:
        token_day = _process_token_day(proc)
        if token_day:
            if token_day not in merged:
                merged[token_day] = _empty_row(token_day)
            merged[token_day]["total_tokens"] += (
                proc.get("total_input_tokens") or 0
            ) + (proc.get("total_output_tokens") or 0)

    activity = await _activity_by_day(db)
    for day, act in activity.items():
        if day not in merged:
            merged[day] = _empty_row(day)
        merged[day]["session_count"] = act["session_count"]
        merged[day]["message_count"] = act["message_count"]

    for row in merged.values():
        row["total_cost_usd"] = round(row["total_cost_usd"], 6)

    return sorted(merged.values(), key=lambda x: x["day"], reverse=True)


async def costs_by_day_cwd(db: aiosqlite.Connection) -> list[dict]:
    """Summary metrics per (day, cwd).

    Returns rows ordered by ``day`` descending then ``cwd`` ascending.
    Each row has ``day``, ``cwd``, plus the same fields as
    ``costs_by_day``.
    """
    sessions = await get_sessions(db)
    processes = await get_processes(db)

    merged: dict[tuple[str, str], dict] = {}
    for sess in sessions:
        cwd = sess.get("cwd") or ""
        for day, cost in (sess.get("cost_by_day") or {}).items():
            key = (day, cwd)
            if key not in merged:
                merged[key] = _empty_row(day, cwd=cwd)
            merged[key]["total_cost_usd"] += cost

    for proc in processes:
        cwd = proc.get("cwd") or ""
        token_day = _process_token_day(proc)
        if token_day:
            key = (token_day, cwd)
            if key not in merged:
                merged[key] = _empty_row(token_day, cwd=cwd)
            merged[key]["total_tokens"] += (proc.get("total_input_tokens") or 0) + (
                proc.get("total_output_tokens") or 0
            )

    activity = await _activity_by_day_cwd(db)
    for (day, cwd), act in activity.items():
        key = (day, cwd)
        if key not in merged:
            merged[key] = _empty_row(day, cwd=cwd)
        merged[key]["session_count"] = act["session_count"]
        merged[key]["message_count"] = act["message_count"]

    for row in merged.values():
        row["total_cost_usd"] = round(row["total_cost_usd"], 6)

    result = sorted(merged.values(), key=lambda x: x["cwd"])
    result.sort(key=lambda x: x["day"], reverse=True)
    return result
