# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Global cost and token aggregation queries for the dashboard.

Mirrors the per-instance daily-delta logic used in
``agentpulse.api.v2.queries.processes._cost_by_day`` and
``...sessions._session_cost_by_day``, but at the global level — sums
across every (pid, source_system, cwd) instance window in the database.

Why a single CTE instead of reusing the v2 helpers: the dashboard is an
optional surface and the rest of the service should remain operable when
this module is removed. Keeping the SQL self-contained avoids creating a
hidden coupling.

cost_usd and the token counters (total_input_tokens, total_output_tokens,
cache_read_tokens, cache_creation_tokens) are all monotonic per instance
window — a contiguous span of activity on a (pid, source_system, cwd)
tuple bounded by claude_log_pid_deaths rows. Across windows the counters
reset, so we group by ``(pid, source_system, cwd, prior_death)`` and
compute deltas separately within each group.

COALESCE(..., 0) on the token MAX values means an instance day with no
token data contributes 0 to the day's total — keeps the SUM clean
without surfacing nulls in API responses. cost_usd uses NULL filtering
instead because rows without cost data shouldn't define an instance at
all.
"""

import aiosqlite

# date(received_at, 'unixepoch', 'localtime') buckets by server local
# time, matching how the v2 per-process and per-session helpers bucket.
_BASE_CTE = """
WITH instance_rows AS (
    SELECT
        s.cwd AS cwd,
        s.cost_usd AS cost_usd,
        s.total_input_tokens AS total_input_tokens,
        s.total_output_tokens AS total_output_tokens,
        s.cache_read_tokens AS cache_read_tokens,
        s.cache_creation_tokens AS cache_creation_tokens,
        s.received_at AS received_at,
        s.pid AS pid,
        s.source_system AS source_system,
        COALESCE(
            (SELECT MAX(observed_at) FROM claude_log_pid_deaths d
             WHERE d.pid = s.pid
                   AND d.source_system = s.source_system
                   AND d.cwd = s.cwd
                   AND d.observed_at < s.received_at),
            -1.0
        ) AS prior_death
    FROM claude_log_statuslines s
    WHERE s.cost_usd IS NOT NULL
),
day_max AS (
    SELECT
        date(received_at, 'unixepoch', 'localtime') AS day,
        cwd,
        pid,
        source_system,
        prior_death,
        MAX(cost_usd) AS day_max_cost,
        COALESCE(MAX(total_input_tokens), 0) AS day_max_input,
        COALESCE(MAX(total_output_tokens), 0) AS day_max_output,
        COALESCE(MAX(cache_read_tokens), 0) AS day_max_cache_read,
        COALESCE(MAX(cache_creation_tokens), 0) AS day_max_cache_creation
    FROM instance_rows
    GROUP BY pid, source_system, cwd, prior_death, day
),
deltas AS (
    SELECT
        day,
        cwd,
        day_max_cost - LAG(day_max_cost, 1, 0.0)
            OVER w AS cost_delta,
        day_max_input - LAG(day_max_input, 1, 0)
            OVER w AS input_delta,
        day_max_output - LAG(day_max_output, 1, 0)
            OVER w AS output_delta,
        day_max_cache_read - LAG(day_max_cache_read, 1, 0)
            OVER w AS cache_read_delta,
        day_max_cache_creation - LAG(day_max_cache_creation, 1, 0)
            OVER w AS cache_creation_delta
    FROM day_max
    WINDOW w AS (
        PARTITION BY pid, source_system, cwd, prior_death ORDER BY day
    )
)
"""


def _row_to_dict(r: aiosqlite.Row, *, include_cwd: bool) -> dict:
    out = {
        "day": r["day"],
        "total_cost_usd": float(r["total_cost_usd"]),
        "input_tokens": int(r["input_tokens"] or 0),
        "output_tokens": int(r["output_tokens"] or 0),
        "cache_read_tokens": int(r["cache_read_tokens"] or 0),
        "cache_creation_tokens": int(r["cache_creation_tokens"] or 0),
    }
    if include_cwd:
        out["cwd"] = r["cwd"]
    return out


async def costs_by_day(db: aiosqlite.Connection) -> list[dict]:
    """Total cost and token usage per day (server local time).

    Returns rows ordered by ``day`` descending. Each row has ``day``,
    ``total_cost_usd``, ``input_tokens``, ``output_tokens``,
    ``cache_read_tokens``, ``cache_creation_tokens``.
    """
    cursor = await db.execute(_BASE_CTE + """
        SELECT day,
               ROUND(SUM(cost_delta), 6) AS total_cost_usd,
               SUM(input_delta) AS input_tokens,
               SUM(output_delta) AS output_tokens,
               SUM(cache_read_delta) AS cache_read_tokens,
               SUM(cache_creation_delta) AS cache_creation_tokens
        FROM deltas
        GROUP BY day
        ORDER BY day DESC
        """)
    rows = await cursor.fetchall()
    return [_row_to_dict(r, include_cwd=False) for r in rows]


async def costs_by_day_cwd(db: aiosqlite.Connection) -> list[dict]:
    """Cost and token usage per (day, cwd).

    Returns rows ordered by ``day`` descending then ``cwd`` ascending.
    Each row has ``day``, ``cwd``, plus the same cost/token fields as
    ``costs_by_day``.
    """
    cursor = await db.execute(_BASE_CTE + """
        SELECT day, cwd,
               ROUND(SUM(cost_delta), 6) AS total_cost_usd,
               SUM(input_delta) AS input_tokens,
               SUM(output_delta) AS output_tokens,
               SUM(cache_read_delta) AS cache_read_tokens,
               SUM(cache_creation_delta) AS cache_creation_tokens
        FROM deltas
        GROUP BY day, cwd
        ORDER BY day DESC, cwd ASC
        """)
    rows = await cursor.fetchall()
    return [_row_to_dict(r, include_cwd=True) for r in rows]
