# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""HTTP surface for the optional dashboard.

All routes live under ``/ui`` so removing this router (a single
``include_router`` line in ``app.py``) takes the entire feature with it.
JSON endpoints sit under ``/ui/api/...`` rather than ``/api/v2/...`` for
the same reason: nothing in the v2 surface depends on this module.
"""

from fastapi import APIRouter
from fastapi.responses import HTMLResponse

from agentpulse.db import get_db
from agentpulse.ui import costs
from agentpulse.ui.page import PAGE_HTML

router = APIRouter(prefix="/ui")


@router.get("/api/costs/by-day")
async def get_costs_by_day() -> list[dict]:
    db = await get_db()
    return await costs.costs_by_day(db)


@router.get("/api/costs/by-day-cwd")
async def get_costs_by_day_cwd() -> list[dict]:
    db = await get_db()
    return await costs.costs_by_day_cwd(db)


@router.get("/costs", response_class=HTMLResponse)
async def costs_page() -> HTMLResponse:
    return HTMLResponse(content=PAGE_HTML)
