# Generated By: Claude Code (Claude Opus 4.6)

.PHONY: check help clean format install install-dev install-pipx uninstall uninstall-pipx run

PACKAGE_NAME ?= agentpulse
PROJECT_NAME ?= $(PACKAGE_NAME)
SRC_DIR ?= src/$(PACKAGE_NAME)
CONFIG_FILE ?= ~/.claude/$(PACKAGE_NAME)/config.json

ifeq ($(OS),Windows_NT)
    VENV_DIR ?= .venv
    PYTHON ?= $(VENV_DIR)/Scripts/python.exe
else
    VENV_DIR ?= .venv
    PYTHON ?= $(VENV_DIR)/bin/python
endif

# Subsystem fragments — noun-based.
-include make/hooks.mk
-include make/service.mk
-include make/tray.mk
# Standard test targets pulled out for readability.
-include make/test.mk

$(info venv: $(VENV_DIR))

check: test-format test-lint test-typecheck test-unit test-coverage  ## Run full quality gate (default)

.DEFAULT_GOAL := check

help:  ## Show available targets
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-32s\033[0m %s\n", $$1, $$2}'

$(PYTHON):
	python3 -m venv $(VENV_DIR)

clean:  ## Remove build artifacts and caches
	rm -rf build/ dist/ *.egg-info
	find . -type d -name __pycache__ -exec rm -r {} + 2>/dev/null || true
	find . -type f -name "*.pyc" -delete 2>/dev/null || true

format: install-dev  ## Rewrite sources with black
	$(PYTHON) -m black $(SRC_DIR) tests

install-dev: $(PYTHON)  ## Editable install + dev + tray extras
	$(PYTHON) -m pip install -e ".[dev]"

install-pipx:  ## Install globally via pipx
	python3 -m pipx install . --force

uninstall-pipx:  ## Uninstall the pipx install
	python3 -m pipx uninstall $(PROJECT_NAME)

##
## Project-specific composites.
## `install`, `uninstall`, `run` install/teardown/launch every subsystem of
## AgentPulse. Standard template default would have `install` = venv install;
## this project mutates it to mean "set up the whole thing for end-user use."
##

install: install-pipx install-hooks install-autostart-service  ## Install everything (pipx + hooks + service autostart)

uninstall: uninstall-autostart-service uninstall-autostart-tray uninstall-pipx  ## Uninstall everything

run: $(PYTHON)  ## Run everything (service + tray; Ctrl-C exits both)
	@$(PYTHON) -m $(PACKAGE_NAME).tray --config $(CONFIG_FILE) & \
	 trap 'kill %1 2>/dev/null || true' EXIT; \
	 $(PYTHON) -m $(PACKAGE_NAME) --config $(CONFIG_FILE)
