# Generated By: Claude Code (Claude Opus 4.7)
"""AgentPulse client library — see ``docs/design/clients.md``.

Public surface re-exports:

- ``AsyncAgentPulseClient`` — async core
- ``AgentPulseClient`` — sync facade (daemon thread + marshaler)
- ``ClientConfig`` / ``load_client_config`` — config schema and loader
- ``Session``, ``Epoch``, ``Agent``, ``Limits``, ``ConnectionState`` — snapshot types
- low-level REST helpers re-exported under ``agentpulse.client.rest``
"""

from agentpulse.client.aio import AsyncAgentPulseClient
from agentpulse.client.config import (
    DEFAULT_PATH,
    ClientConfig,
    load_client_config,
)
from agentpulse.client.sync import AgentPulseClient, Marshaler
from agentpulse.client.types import (
    Agent,
    ConnectionState,
    Epoch,
    Limits,
    Session,
)

__all__ = [
    "Agent",
    "AgentPulseClient",
    "AsyncAgentPulseClient",
    "ClientConfig",
    "ConnectionState",
    "DEFAULT_PATH",
    "Epoch",
    "Limits",
    "Marshaler",
    "Session",
    "load_client_config",
]
