# Generated By: Claude Code (Claude Opus 4.7)
"""Internal store + frame application for AgentPulse client.

Holds the canonical ``dict[session_id, Session]`` plus a
``process_id -> set[session_id]`` index for ``pid_death_logged``
fan-out. Applies WS frames and bootstrap REST payloads, and dispatches
callbacks (single ``on_change`` plus typed hooks) on every mutation.

This module is platform/IO-free: callers (``aio``, ``sync``) drive it
with already-parsed dicts. That keeps the frame logic unit-testable
without a real WebSocket or HTTP stack.

Locking
-------
The store uses a single ``threading.RLock``. Mutations AND callback
dispatch run under the lock so the order callbacks are delivered to
consumers matches the order mutations land — even when multiple writer
threads race. ``RLock`` (not plain ``Lock``) lets callbacks invoke
snapshot accessors (``sessions()``, ``limits()``, ``connection_state()``)
without re-entry deadlock.

Callbacks **must not block**. They run on the calling thread (the
mutator) while the lock is held; a slow callback stalls every other
thread that needs the store. Consumers that want async work should
queue the work and return immediately. The sync facade's ``marshaler``
is the supported way to deliver callbacks on a UI thread without
blocking the asyncio loop.
"""

from __future__ import annotations

import dataclasses
import logging
import threading
from collections.abc import Callable, Mapping, Sequence
from datetime import datetime
from typing import Any

from agentpulse.client.types import (
    Agent,
    ConnectionState,
    Epoch,
    Limits,
    Session,
)

logger = logging.getLogger(__name__)


def _today_local() -> str:
    """Today's date as ``YYYY-MM-DD`` in local time."""
    return datetime.now().strftime("%Y-%m-%d")


def _epoch_from_dict(d: Mapping[str, Any]) -> Epoch:
    return Epoch(
        epoch_id=d["epoch_id"],
        session_id=d["session_id"],
        process_id=d["process_id"],
        pid=d["pid"],
        source_system=d["source_system"],
        cwd=d["cwd"],
        entrypoint=d.get("entrypoint"),
        started_at=float(d["started_at"]),
        ended_at=d.get("ended_at"),
        event_count=int(d.get("event_count") or 0),
    )


def _agent_from_dict(d: Mapping[str, Any]) -> Agent:
    return Agent(
        agent_id=d["agent_id"],
        session_id=d["session_id"],
        process_id=d["process_id"],
        agent_type=d.get("agent_type"),
        started_at=float(d["started_at"]),
        ended_at=d.get("ended_at"),
        last_event=d.get("last_event"),
        last_tool=d.get("last_tool"),
        last_event_at=d.get("last_event_at"),
        derived_state=d.get("derived_state"),
    )


def _session_from_response(d: Mapping[str, Any]) -> Session:
    """Construct a ``Session`` from a v2 ``SessionResponse`` dict.

    Statusline-derived counters (tokens, lines) aren't on
    ``SessionResponse`` and seed to 0 — they fill in from
    ``statusline_logged`` frames or a separate statuslines bootstrap
    fetch.
    """
    epochs = tuple(_epoch_from_dict(e) for e in (d.get("epochs") or ()))
    agents = tuple(_agent_from_dict(a) for a in (d.get("agents") or ()))
    return Session(
        session_id=d["session_id"],
        process_id=d["process_id"],
        pid=int(d.get("pid") or 0),
        source_system=d.get("source_system") or "",
        cwd=d.get("cwd") or "",
        started_at=float(d.get("started_at") or 0.0),
        last_activity_at=float(d.get("last_activity_at") or 0.0),
        ended_at=d.get("ended_at"),
        last_event=d.get("last_event"),
        last_tool=d.get("last_tool"),
        last_event_at=d.get("last_event_at"),
        context_used_pct=d.get("context_used_pct"),
        context_window_size=d.get("context_window_size"),
        model_id=d.get("model_id"),
        model_name=d.get("model_name"),
        derived_state=d.get("derived_state"),
        total_cost_usd=float(d.get("total_cost_usd") or 0.0),
        cost_by_day=dict(d.get("cost_by_day") or {}),
        total_input_tokens=0,
        total_output_tokens=0,
        lines_added=0,
        lines_removed=0,
        epochs=epochs,
        agents=agents,
    )


def _limits_from_dict(d: Mapping[str, Any]) -> Limits:
    return Limits(
        five_hour_utilization=d.get("five_hour_utilization"),
        five_hour_resets_at=d.get("five_hour_resets_at"),
        seven_day_utilization=d.get("seven_day_utilization"),
        seven_day_resets_at=d.get("seven_day_resets_at"),
        received_at=float(d.get("received_at") or 0.0),
    )


def _session_with(session: Session, **changes: Any) -> Session:
    """Return a new Session with selected fields overridden.

    ``Session`` is frozen — every mutation produces a fresh dataclass.
    Thin wrapper over ``dataclasses.replace`` for readability at call sites.
    """
    return dataclasses.replace(session, **changes)


# Callback type aliases — sync only. Consumers wrap async work themselves.
OnChange = Callable[[], None]
OnSession = Callable[[Session], None]
OnProcessId = Callable[[str], None]
OnLimits = Callable[[Limits], None]
OnConnectionState = Callable[[ConnectionState], None]


class ClientStore:
    """Thread-safe store for client-side session/limits snapshots.

    Snapshot accessors return frozen dataclasses; mutations replace
    entries wholesale. A single ``threading.Lock`` guards both the
    ``_sessions`` map and ``_process_index``. Callbacks fire outside
    the lock to avoid re-entry deadlocks when a callback inspects the
    store.
    """

    def __init__(self) -> None:
        # RLock so callbacks fired under the lock can call snapshot
        # accessors (which also take the lock) without deadlocking.
        self._lock = threading.RLock()
        self._sessions: dict[str, Session] = {}
        self._process_index: dict[str, set[str]] = {}
        self._limits: Limits | None = None
        self._connection_state: ConnectionState = ConnectionState.DISCONNECTED

        self._on_change: list[OnChange] = []
        self._on_session_added: list[OnSession] = []
        self._on_session_ended: list[OnSession] = []
        self._on_process_ended: list[OnProcessId] = []
        self._on_limits_changed: list[OnLimits] = []
        self._on_connection_state: list[OnConnectionState] = []

    # ------------------------------------------------------------------
    # Snapshots
    # ------------------------------------------------------------------

    def sessions(self) -> tuple[Session, ...]:
        with self._lock:
            return tuple(self._sessions.values())

    def session(self, session_id: str) -> Session | None:
        with self._lock:
            return self._sessions.get(session_id)

    def limits(self) -> Limits | None:
        with self._lock:
            return self._limits

    def connection_state(self) -> ConnectionState:
        with self._lock:
            return self._connection_state

    # ------------------------------------------------------------------
    # Callback registration
    # ------------------------------------------------------------------

    def on_change(self, fn: OnChange) -> None:
        with self._lock:
            self._on_change.append(fn)

    def on_session_added(self, fn: OnSession) -> None:
        with self._lock:
            self._on_session_added.append(fn)

    def on_session_ended(self, fn: OnSession) -> None:
        with self._lock:
            self._on_session_ended.append(fn)

    def on_process_ended(self, fn: OnProcessId) -> None:
        with self._lock:
            self._on_process_ended.append(fn)

    def on_limits_changed(self, fn: OnLimits) -> None:
        with self._lock:
            self._on_limits_changed.append(fn)

    def on_connection_state(self, fn: OnConnectionState) -> None:
        with self._lock:
            self._on_connection_state.append(fn)

    # ------------------------------------------------------------------
    # Mutations driven by REST bootstrap
    # ------------------------------------------------------------------

    def replace_sessions(self, responses: Sequence[Mapping[str, Any]]) -> None:
        """Replace the session map with the bootstrap REST payload.

        Existing statusline-derived fields (tokens, lines) for sessions
        already in the store are preserved when their session_id reappears
        — they aren't on ``SessionResponse`` and refetching loses them.
        """
        with self._lock:
            previous = self._sessions
            new_sessions: dict[str, Session] = {}
            new_index: dict[str, set[str]] = {}
            added: list[Session] = []
            for resp in responses:
                sid = resp.get("session_id")
                if not sid:
                    continue
                fresh = _session_from_response(resp)
                prior = previous.get(sid)
                if prior is not None:
                    fresh = _session_with(
                        fresh,
                        total_input_tokens=prior.total_input_tokens,
                        total_output_tokens=prior.total_output_tokens,
                        lines_added=prior.lines_added,
                        lines_removed=prior.lines_removed,
                    )
                else:
                    added.append(fresh)
                new_sessions[sid] = fresh
                new_index.setdefault(fresh.process_id, set()).add(sid)
            self._sessions = new_sessions
            self._process_index = new_index
            for session in added:
                self._fire(self._on_session_added, session)
            self._fire_change()

    def apply_statusline_log_seed(self, rows: Sequence[Mapping[str, Any]]) -> None:
        """Seed tokens/lines/cost from a descending statuslines log fetch.

        The endpoint returns rows ordered newest-first; we apply only the
        first row per ``session_id``. Bootstrap concern only — live frames
        go through ``apply_statusline_logged``.
        """
        with self._lock:
            seen: set[str] = set()
            for row in rows:
                sid = row.get("session_id")
                if not sid or sid in seen:
                    continue
                target = self._sessions.get(sid)
                if target is None:
                    continue
                self._sessions[sid] = _apply_statusline_fields(target, row)
                seen.add(sid)
            self._fire_change()

    def replace_limits(self, payload: Mapping[str, Any] | None) -> None:
        """Replace the limits snapshot from REST. ``None`` clears it."""
        with self._lock:
            new_limits = _limits_from_dict(payload) if payload else None
            self._limits = new_limits
            if new_limits is not None:
                self._fire(self._on_limits_changed, new_limits)
            self._fire_change()

    # ------------------------------------------------------------------
    # WebSocket frame application
    # ------------------------------------------------------------------

    def apply_hook_logged(self, frame: Mapping[str, Any]) -> bool:
        """Apply a ``hook_logged`` frame.

        Returns ``False`` if the session is unknown — the caller should
        kick off a ``refresh_session`` to fetch it. Returns ``True`` when
        the frame was applied (may have been a no-op if fields were
        already at the new values).
        """
        session_id = frame.get("session_id")
        if not session_id:
            return True  # no-op; ignore malformed
        with self._lock:
            current = self._sessions.get(session_id)
            if current is None:
                return False
            event_name = frame.get("event_name") or ""
            received_at = float(frame.get("received_at") or 0.0)
            changes: dict[str, Any] = {
                "last_event": event_name,
                "last_event_at": received_at,
                "last_activity_at": max(current.last_activity_at, received_at),
                "derived_state": frame.get("derived_state"),
            }
            tool_name = frame.get("tool_name")
            if tool_name is not None:
                changes["last_tool"] = tool_name
            ended_session: Session | None = None
            if event_name == "SessionEnd" and current.ended_at is None:
                changes["ended_at"] = received_at
            updated = _session_with(current, **changes)
            self._sessions[session_id] = updated
            self._process_index.setdefault(current.process_id, set()).add(session_id)
            if event_name == "SessionEnd" and current.ended_at is None:
                ended_session = updated
            if ended_session is not None:
                self._fire(self._on_session_ended, ended_session)
            self._fire_change()
        return True

    def apply_statusline_logged(self, frame: Mapping[str, Any]) -> None:
        """Apply a ``statusline_logged`` frame.

        Creates a pending session entry if the ``session_id`` is unknown
        (statuslines can race ahead of hooks). Replaces — does not
        accumulate — cost/token/line fields with the values from the frame.
        """
        session_id = frame.get("session_id")
        if not session_id:
            return
        with self._lock:
            current = self._sessions.get(session_id)
            added: Session | None = None
            if current is None:
                current = _pending_session_from_statusline(frame)
                self._sessions[session_id] = current
                self._process_index.setdefault(current.process_id, set()).add(
                    session_id
                )
                added = current
            updated = _apply_statusline_fields(current, frame)
            self._sessions[session_id] = updated
            if added is not None:
                self._fire(self._on_session_added, added)
            self._fire_change()

    def apply_pid_death_logged(self, frame: Mapping[str, Any]) -> None:
        """Apply a ``pid_death_logged`` frame.

        Marks every session under the dead ``process_id`` as ended unless
        it already has an ``ended_at`` (e.g. from a prior ``SessionEnd``).
        Fires ``on_process_ended`` once after the fan-out.
        """
        process_id = frame.get("process_id")
        if not process_id:
            return
        observed_at = float(frame.get("observed_at") or 0.0)
        with self._lock:
            ended: list[Session] = []
            session_ids = self._process_index.get(process_id, set())
            for sid in session_ids:
                current = self._sessions.get(sid)
                if current is None or current.ended_at is not None:
                    continue
                updated = _session_with(current, ended_at=observed_at)
                self._sessions[sid] = updated
                ended.append(updated)
            for session in ended:
                self._fire(self._on_session_ended, session)
            self._fire(self._on_process_ended, process_id)
            self._fire_change()

    def apply_api_limits_logged(self, frame: Mapping[str, Any]) -> None:
        """Apply an ``api_limits_logged`` frame — replace snapshot."""
        with self._lock:
            new_limits = _limits_from_dict(frame)
            self._limits = new_limits
            self._fire(self._on_limits_changed, new_limits)
            self._fire_change()

    # ------------------------------------------------------------------
    # Connection state
    # ------------------------------------------------------------------

    def set_connection_state(self, state: ConnectionState) -> None:
        """Update connection state; fires ``on_connection_state`` on change."""
        with self._lock:
            if self._connection_state == state:
                return
            self._connection_state = state
            self._fire(self._on_connection_state, state)

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _fire_change(self) -> None:
        for fn in list(self._on_change):
            try:
                fn()
            except Exception:
                logger.exception("on_change callback raised")

    def _fire(self, listeners: list[Callable[..., None]], *args: Any) -> None:
        for fn in list(listeners):
            try:
                fn(*args)
            except Exception:
                logger.exception("client callback raised")


# Statusline frame fields that map onto the Session dataclass. Used by
# both the live frame handler and the statuslines log seed to keep the
# replacement semantics in sync.
_STATUSLINE_FIELDS: tuple[tuple[str, str], ...] = (
    ("model_id", "model_id"),
    ("model_name", "model_name"),
    ("context_used_pct", "context_used_pct"),
    ("context_window_size", "context_window_size"),
    ("total_input_tokens", "total_input_tokens"),
    ("total_output_tokens", "total_output_tokens"),
    ("lines_added", "lines_added"),
    ("lines_removed", "lines_removed"),
)


def _apply_statusline_fields(session: Session, frame: Mapping[str, Any]) -> Session:
    """Return a new Session with statusline-derived fields replaced."""
    changes: dict[str, Any] = {}
    for src, dst in _STATUSLINE_FIELDS:
        val = frame.get(src)
        if val is not None:
            changes[dst] = val

    session_total = frame.get("session_total_cost_usd")
    if session_total is not None:
        changes["total_cost_usd"] = float(session_total)

    today_cost = frame.get("session_today_cost_usd")
    if today_cost is not None:
        cost_by_day = dict(session.cost_by_day)
        cost_by_day[_today_local()] = float(today_cost)
        changes["cost_by_day"] = cost_by_day

    received_at = frame.get("received_at")
    if received_at is not None:
        changes["last_activity_at"] = max(session.last_activity_at, float(received_at))

    return _session_with(session, **changes)


def _pending_session_from_statusline(frame: Mapping[str, Any]) -> Session:
    """Synthesize a Session from a statusline arriving before any hook.

    Most fields default to zero / None; statusline-derived fields are
    filled in by the caller via ``_apply_statusline_fields``.
    """
    received_at = float(frame.get("received_at") or 0.0)
    return Session(
        session_id=frame["session_id"],
        process_id=frame.get("process_id") or "",
        pid=int(frame.get("pid") or 0),
        source_system=frame.get("source_system") or "",
        cwd=frame.get("cwd") or "",
        started_at=received_at,
        last_activity_at=received_at,
        ended_at=None,
        last_event=None,
        last_tool=None,
        last_event_at=None,
        context_used_pct=None,
        context_window_size=None,
        model_id=None,
        model_name=None,
        derived_state=None,
        total_cost_usd=0.0,
        cost_by_day={},
        total_input_tokens=0,
        total_output_tokens=0,
        lines_added=0,
        lines_removed=0,
    )
