# Generated By: Claude Code (Claude Opus 4.7)
"""Client-side reader for ``~/.claude/agentpulse/config.json``.

Distinct from ``agentpulse.config`` (the server-side ``Settings``) — same
file, different scope. The client only reads ``host``, ``port``, and
``fetch_limits``; everything else (db_path, pidfile_dir, etc.) is server
business.

``load_client_config`` returns ``None`` for missing or malformed files —
consumers treat that as "client disabled" rather than raising.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)

DEFAULT_PATH = Path.home() / ".claude" / "agentpulse" / "config.json"


@dataclass(frozen=True)
class ClientConfig:
    """Parsed client config plus reconnect/timeout knobs."""

    host: str
    port: int
    fetch_limits: bool = True
    initial_backoff_s: float = 1.0
    backoff_cap_s: float = 30.0
    http_timeout_s: float = 5.0


def load_client_config(path: Path = DEFAULT_PATH) -> ClientConfig | None:
    """Read host/port/fetch_limits from the AgentPulse config file.

    Returns ``None`` when the file is missing, malformed, or lacks the
    required ``host``/``port`` keys. ``fetch_limits`` defaults to True
    when absent.
    """
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        logger.debug("client config unreadable at %s: %s", path, exc)
        return None
    host = data.get("host")
    port = data.get("port")
    if not host or not port:
        logger.debug("client config at %s missing host or port", path)
        return None
    return ClientConfig(
        host=str(host),
        port=int(port),
        fetch_limits=bool(data.get("fetch_limits", True)),
    )
