# Generated By: Claude Code (Claude Opus 4.7)
"""Sync facade over ``AsyncAgentPulseClient``.

Runs the async core in a daemon thread. Snapshot reads are thread-safe
(the store uses its own lock). Callbacks fire on the asyncio thread by
default; pass ``marshaler`` to redirect them to e.g. a Tk main loop.
"""

from __future__ import annotations

import asyncio
import logging
import threading
from collections.abc import Callable, Mapping
from typing import Any

from agentpulse.client._state import (
    OnChange,
    OnConnectionState,
    OnLimits,
    OnProcessId,
    OnSession,
)
from agentpulse.client.aio import AsyncAgentPulseClient
from agentpulse.client.config import ClientConfig
from agentpulse.client.types import ConnectionState, Limits, Session

logger = logging.getLogger(__name__)

Marshaler = Callable[[Callable[[], None]], None]


class AgentPulseClient:
    """Daemon-thread wrapper around ``AsyncAgentPulseClient``.

    ``marshaler`` runs callbacks on the consumer's preferred thread:

    - Tk: ``marshaler=lambda f: root.after(0, f)``
    - Qt: ``marshaler=lambda f: QTimer.singleShot(0, f)`` (or signals)
    - None (default): callbacks fire on the asyncio loop's thread.
    """

    def __init__(
        self,
        config: ClientConfig,
        *,
        marshaler: Marshaler | None = None,
    ) -> None:
        self._config = config
        self._marshaler = marshaler
        self._loop: asyncio.AbstractEventLoop | None = None
        self._client: AsyncAgentPulseClient | None = None
        self._thread: threading.Thread | None = None
        self._ready = threading.Event()

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def start(self) -> None:
        """Spawn the asyncio daemon thread and wait for first bootstrap."""
        if self._thread is not None:
            return
        self._thread = threading.Thread(
            target=self._run, daemon=True, name="agentpulse-client"
        )
        self._thread.start()
        self._ready.wait(timeout=10.0)

    def stop(self) -> None:
        """Signal stop and join the thread (best-effort). Idempotent."""
        if self._loop is None or self._client is None:
            return
        if self._loop.is_closed():
            return
        try:
            future = asyncio.run_coroutine_threadsafe(self._client.stop(), self._loop)
            future.result(timeout=5.0)
        except RuntimeError:
            # Loop may have closed mid-call; treat as already-stopped.
            pass
        except Exception:
            logger.debug("client.stop() did not return cleanly", exc_info=True)
        try:
            self._loop.call_soon_threadsafe(self._loop.stop)
        except RuntimeError:
            pass
        if self._thread is not None:
            self._thread.join(timeout=5.0)
            self._thread = None

    # ------------------------------------------------------------------
    # Snapshot accessors — thread-safe, read straight from the store
    # ------------------------------------------------------------------

    def sessions(self) -> tuple[Session, ...]:
        if self._client is None:
            return ()
        return self._client.sessions()

    def session(self, session_id: str) -> Session | None:
        if self._client is None:
            return None
        return self._client.session(session_id)

    def limits(self) -> Limits | None:
        if self._client is None:
            return None
        return self._client.limits()

    def connection_state(self) -> ConnectionState:
        if self._client is None:
            return ConnectionState.DISCONNECTED
        return self._client.connection_state()

    # ------------------------------------------------------------------
    # Blocking operations — submitted to the loop, awaited
    # ------------------------------------------------------------------

    def refresh(self) -> None:
        self._submit_blocking(lambda c: c.refresh())

    def refresh_session(self, session_id: str) -> None:
        self._submit_blocking(lambda c: c.refresh_session(session_id))

    def post_statusline(self, payload: Mapping[str, Any]) -> bool:
        result = self._submit_blocking(
            lambda c: c.post_statusline(payload), default=False
        )
        return bool(result)

    def post_hook(self, payload: Mapping[str, Any]) -> bool:
        result = self._submit_blocking(lambda c: c.post_hook(payload), default=False)
        return bool(result)

    # ------------------------------------------------------------------
    # Callback registration — wraps each fn through the marshaler
    # ------------------------------------------------------------------

    def on_change(self, fn: OnChange) -> None:
        if self._client is None:
            return
        self._client.on_change(self._wrap0(fn))

    def on_session_added(self, fn: OnSession) -> None:
        if self._client is None:
            return
        self._client.on_session_added(self._wrap1(fn))

    def on_session_ended(self, fn: OnSession) -> None:
        if self._client is None:
            return
        self._client.on_session_ended(self._wrap1(fn))

    def on_process_ended(self, fn: OnProcessId) -> None:
        if self._client is None:
            return
        self._client.on_process_ended(self._wrap1(fn))

    def on_limits_changed(self, fn: OnLimits) -> None:
        if self._client is None:
            return
        self._client.on_limits_changed(self._wrap1(fn))

    def on_connection_state(self, fn: OnConnectionState) -> None:
        if self._client is None:
            return
        self._client.on_connection_state(self._wrap1(fn))

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _run(self) -> None:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        self._loop = loop
        self._client = AsyncAgentPulseClient(self._config)
        try:
            loop.run_until_complete(self._startup())
            self._ready.set()
            loop.run_forever()
        except Exception:
            logger.exception("AgentPulse client thread crashed")
            self._ready.set()
        finally:
            try:
                loop.run_until_complete(loop.shutdown_asyncgens())
            except Exception:
                pass
            loop.close()

    async def _startup(self) -> None:
        assert self._client is not None
        await self._client.start()

    def _submit_blocking(
        self,
        fn: Callable[[AsyncAgentPulseClient], Any],
        *,
        default: Any = None,
    ) -> Any:
        if self._loop is None or self._client is None:
            return default
        coro = fn(self._client)
        future = asyncio.run_coroutine_threadsafe(coro, self._loop)
        try:
            return future.result(timeout=self._config.http_timeout_s + 5.0)
        except Exception:
            logger.debug("client operation failed", exc_info=True)
            return default

    def _wrap0(self, fn: Callable[[], None]) -> Callable[[], None]:
        if self._marshaler is None:
            return fn
        marshaler = self._marshaler

        def wrapped() -> None:
            marshaler(fn)

        return wrapped

    def _wrap1(self, fn: Callable[[Any], None]) -> Callable[[Any], None]:
        if self._marshaler is None:
            return fn
        marshaler = self._marshaler

        def wrapped(arg: Any) -> None:
            marshaler(lambda: fn(arg))

        return wrapped
