# Generated By: Claude Code (Claude Opus 4.6)
"""Claude Code platform-specific raw endpoints."""

from fastapi import APIRouter

from agentpulse.db import get_db
from agentpulse.platforms.claude.models import (
    ClaudeEventRow,
    ClaudeSessionRow,
)
from agentpulse.platforms.claude import schema

router = APIRouter(prefix="/api/v1/claude")


@router.get("/sessions")
async def list_claude_sessions() -> list[ClaudeSessionRow]:
    """Return raw claude_sessions rows."""
    db = await get_db()
    rows = await schema.get_all_sessions(db)
    return [ClaudeSessionRow(**row) for row in rows]


@router.get("/events")
async def list_claude_events(
    *,
    session_id: str | None = None,
    event_name: str | None = None,
    since: float | None = None,
    until: float | None = None,
    limit: int = 100,
    offset: int = 0,
) -> list[ClaudeEventRow]:
    """Return raw claude_events with filtering."""
    db = await get_db()
    rows = await schema.get_all_events(
        db,
        session_id=session_id,
        event_name=event_name,
        since=since,
        until=until,
        limit=limit,
        offset=offset,
    )
    return [ClaudeEventRow(**row) for row in rows]
