# Generated By: Claude Code (Claude Opus 4.6)
"""Shared fixtures and safety guards for all tests."""

import asyncio
import subprocess
from pathlib import Path
from typing import Any, Coroutine
from unittest.mock import patch

import pytest

_PROJECT_ROOT = Path(__file__).resolve().parent.parent


@pytest.fixture(autouse=True)
def _block_subprocess() -> None:  # type: ignore[misc]
    """Block subprocess globally — no real commands in tests."""

    def _blocked(*args, **kwargs):  # type: ignore[no-untyped-def]
        cmd = args[0] if args else kwargs.get("args", "?")
        raise RuntimeError(f"subprocess blocked by conftest: {cmd!r}. Mock it instead.")

    with (
        patch.object(subprocess, "run", side_effect=_blocked),
        patch.object(subprocess, "Popen", side_effect=_blocked),
        patch.object(subprocess, "call", side_effect=_blocked),
        patch.object(subprocess, "check_call", side_effect=_blocked),
        patch.object(subprocess, "check_output", side_effect=_blocked),
    ):
        yield


@pytest.fixture(autouse=True)
def _block_real_filesystem(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Prevent tests from writing outside tmp_path."""

    def _is_allowed(path: Path) -> bool:
        resolved = path.resolve()
        return str(resolved).startswith(str(tmp_path)) or str(resolved).startswith(
            str(_PROJECT_ROOT / ".venv")
        )

    def _guard(original):  # type: ignore[no-untyped-def]
        def guarded(self, *args, **kwargs):  # type: ignore[no-untyped-def]
            if not _is_allowed(self):
                raise PermissionError(f"Test tried to write outside tmp_path: {self}")
            return original(self, *args, **kwargs)

        return guarded

    for method in (
        "write_text",
        "write_bytes",
        "rename",
        "unlink",
        "rmdir",
        "mkdir",
    ):
        monkeypatch.setattr(Path, method, _guard(getattr(Path, method)))


@pytest.fixture(autouse=True)
def _block_http(monkeypatch: pytest.MonkeyPatch) -> None:
    """Block real HTTP requests."""
    import httpx

    def _blocked(*args, **kwargs):  # type: ignore[no-untyped-def]
        raise RuntimeError("HTTP blocked by conftest. Mock it instead.")

    monkeypatch.setattr(httpx, "get", _blocked)
    monkeypatch.setattr(httpx, "post", _blocked)
    monkeypatch.setattr(httpx, "Client", _blocked)
    monkeypatch.setattr(httpx, "AsyncClient", _blocked)


@pytest.fixture(autouse=True)
def _isolate_db(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Point DB path at tmp_path so tests get an isolated database."""
    import agentpulse.config as config

    config.reset_settings()
    monkeypatch.setattr(config, "DEFAULT_DB_PATH", tmp_path / "test.db")


def run_async(coro: Coroutine[Any, Any, Any]) -> Any:
    """Run an async coroutine from a sync test context.

    Uses asyncio.get_event_loop().run_until_complete() — the standard
    pattern for sync TestClient tests that need to call async DB helpers.
    """
    return asyncio.get_event_loop().run_until_complete(coro)
