# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for claude_* schema and query functions."""

from pathlib import Path

import pytest

from agentpulse.db import close_db, init_db
from agentpulse.platforms.claude import schema


@pytest.fixture
async def db(tmp_path: Path):
    """Provide an initialized test database."""
    db_path = tmp_path / "test.db"
    conn = await init_db(db_path=db_path)
    yield conn
    await close_db()


class TestCreateTables:
    async def test_creates_all_tables(self, db) -> None:
        cursor = await db.execute(
            "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"
        )
        tables = [row[0] for row in await cursor.fetchall()]
        assert "claude_sessions" in tables
        assert "claude_agents" in tables
        assert "claude_events" in tables
        assert "claude_costs" in tables

    async def test_idempotent(self, db) -> None:
        await schema.create_tables(db)
        await schema.create_tables(db)
        cursor = await db.execute(
            "SELECT count(*) FROM sqlite_master WHERE name='claude_sessions'"
        )
        row = await cursor.fetchone()
        assert row[0] == 1


class TestSessionCrud:
    async def test_upsert_inserts_new(self, db) -> None:
        await schema.upsert_session(
            db,
            session_id="s1",
            pid=1234,
            cwd="/tmp/proj",
            entrypoint="cli",
            started_at=1000,
            last_event="PreToolUse",
            last_tool="Bash",
            last_event_at=1.0,
        )
        row = await schema.get_session(db, session_id="s1")
        assert row is not None
        assert row["pid"] == 1234
        assert row["last_event"] == "PreToolUse"
        assert row["last_tool"] == "Bash"

    async def test_upsert_updates_existing(self, db) -> None:
        await schema.upsert_session(
            db,
            session_id="s1",
            pid=1234,
            cwd="/tmp/proj",
            last_event="PreToolUse",
            last_tool="Bash",
            last_event_at=1.0,
        )
        await schema.upsert_session(
            db,
            session_id="s1",
            last_event="Stop",
            last_tool=None,
            last_event_at=2.0,
        )
        row = await schema.get_session(db, session_id="s1")
        assert row["last_event"] == "Stop"
        assert row["last_tool"] == "Bash"  # COALESCE keeps old value
        assert row["pid"] == 1234

    async def test_end_session(self, db) -> None:
        await schema.upsert_session(db, session_id="s1", pid=1234, cwd="/tmp")
        await schema.end_session(db, session_id="s1", ended_at=99.0)
        row = await schema.get_session(db, session_id="s1")
        assert row["ended_at"] == 99.0

    async def test_update_pid_alive(self, db) -> None:
        await schema.upsert_session(db, session_id="s1", pid=1234, cwd="/tmp")
        await schema.update_session_pid_alive(db, session_id="s1", pid_alive=False)
        row = await schema.get_session(db, session_id="s1")
        assert row["pid_alive"] == 0

    async def test_get_all_sessions_active_filter(self, db) -> None:
        await schema.upsert_session(db, session_id="alive", pid=1, cwd="/a")
        await schema.upsert_session(db, session_id="dead", pid=2, cwd="/b")
        await schema.update_session_pid_alive(db, session_id="dead", pid_alive=False)

        active = await schema.get_all_sessions(db, active=True)
        assert len(active) == 1
        assert active[0]["session_id"] == "alive"

        inactive = await schema.get_all_sessions(db, active=False)
        assert len(inactive) == 1
        assert inactive[0]["session_id"] == "dead"

    async def test_get_session_not_found(self, db) -> None:
        row = await schema.get_session(db, session_id="nonexistent")
        assert row is None

    async def test_get_sessions_needing_pid_check(self, db) -> None:
        await schema.upsert_session(db, session_id="alive", pid=1, cwd="/a")
        await schema.upsert_session(db, session_id="ended", pid=2, cwd="/b")
        await schema.end_session(db, session_id="ended")

        rows = await schema.get_sessions_needing_pid_check(db)
        assert len(rows) == 1
        assert rows[0]["session_id"] == "alive"

    async def test_update_session_discovery(self, db) -> None:
        await schema.update_session_discovery(
            db,
            session_id="s1",
            pid=5678,
            cwd="/project",
            entrypoint="vscode",
            started_at=2000,
            pid_alive=True,
            branch="feature/foo",
        )
        row = await schema.get_session(db, session_id="s1")
        assert row["pid"] == 5678
        assert row["branch"] == "feature/foo"
        assert row["entrypoint"] == "vscode"

    async def test_clear_session(self, db) -> None:
        await schema.upsert_session(
            db,
            session_id="s1",
            pid=1,
            cwd="/tmp",
            last_event="PreToolUse",
            last_tool="Bash",
            last_event_at=1.0,
        )
        await schema.upsert_agent(
            db,
            agent_id="a1",
            session_id="s1",
            last_event="PreToolUse",
        )
        await schema.clear_session(db, session_id="s1", cleared_at=99.0)

        row = await schema.get_session(db, session_id="s1")
        assert row["last_event"] is None
        assert row["last_tool"] is None
        assert row["last_event_at"] is None
        assert row["pid"] == 1  # PID preserved

        agents = await schema.get_session_agents(db, session_id="s1")
        assert agents[0]["ended_at"] == 99.0

    async def test_source_system(self, db) -> None:
        await schema.upsert_session(
            db,
            session_id="s1",
            pid=1,
            cwd="/tmp",
            source_system="host-a",
        )
        row = await schema.get_session(db, session_id="s1")
        assert row["source_system"] == "host-a"

        # Update preserves source_system when not provided
        await schema.upsert_session(
            db,
            session_id="s1",
            last_event="Stop",
        )
        row = await schema.get_session(db, session_id="s1")
        assert row["source_system"] == "host-a"


class TestAgentCrud:
    async def test_upsert_inserts_new(self, db) -> None:
        await schema.upsert_session(db, session_id="s1", pid=1, cwd="/tmp")
        await schema.upsert_agent(
            db,
            agent_id="a1",
            session_id="s1",
            agent_type="Explore",
            last_event="PreToolUse",
            last_tool="Grep",
            last_event_at=1.0,
        )
        agents = await schema.get_session_agents(db, session_id="s1")
        assert len(agents) == 1
        assert agents[0]["agent_type"] == "Explore"

    async def test_upsert_updates_existing(self, db) -> None:
        await schema.upsert_session(db, session_id="s1", pid=1, cwd="/tmp")
        await schema.upsert_agent(
            db,
            agent_id="a1",
            session_id="s1",
            agent_type="Explore",
            last_event="PreToolUse",
            last_event_at=1.0,
        )
        await schema.upsert_agent(
            db,
            agent_id="a1",
            session_id="s1",
            last_event="Stop",
            last_event_at=2.0,
        )
        agents = await schema.get_session_agents(db, session_id="s1")
        assert agents[0]["last_event"] == "Stop"
        assert agents[0]["agent_type"] == "Explore"

    async def test_end_agent(self, db) -> None:
        await schema.upsert_session(db, session_id="s1", pid=1, cwd="/tmp")
        await schema.upsert_agent(db, agent_id="a1", session_id="s1")
        await schema.end_agent(db, agent_id="a1", ended_at=99.0)
        agents = await schema.get_session_agents(db, session_id="s1")
        assert agents[0]["ended_at"] == 99.0


class TestEventCrud:
    async def test_insert_and_query(self, db) -> None:
        await schema.insert_event(
            db,
            session_id="s1",
            event_name="PreToolUse",
            tool_name="Bash",
            cwd="/tmp",
            received_at=1.0,
            raw_payload='{"test": true}',
        )
        events = await schema.get_session_events(db, session_id="s1")
        assert len(events) == 1
        assert events[0]["event_name"] == "PreToolUse"
        assert events[0]["raw_payload"] == '{"test": true}'

    async def test_pagination(self, db) -> None:
        for i in range(5):
            await schema.insert_event(
                db,
                session_id="s1",
                event_name=f"Event{i}",
                received_at=float(i),
            )
        page = await schema.get_session_events(db, session_id="s1", limit=2, offset=0)
        assert len(page) == 2

    async def test_since_filter(self, db) -> None:
        await schema.insert_event(
            db,
            session_id="s1",
            event_name="Old",
            received_at=1.0,
        )
        await schema.insert_event(
            db,
            session_id="s1",
            event_name="New",
            received_at=10.0,
        )
        events = await schema.get_session_events(db, session_id="s1", since=5.0)
        assert len(events) == 1
        assert events[0]["event_name"] == "New"

    async def test_get_all_events_filters(self, db) -> None:
        await schema.insert_event(
            db,
            session_id="s1",
            event_name="PreToolUse",
            received_at=1.0,
        )
        await schema.insert_event(
            db,
            session_id="s2",
            event_name="Stop",
            received_at=2.0,
        )
        results = await schema.get_all_events(db, session_id="s1")
        assert len(results) == 1

        results = await schema.get_all_events(db, event_name="Stop")
        assert len(results) == 1
        assert results[0]["session_id"] == "s2"
