# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for the events broadcast abstraction."""

from unittest.mock import AsyncMock, patch

import pytest


@pytest.fixture
def mock_broadcast():
    with patch("agentpulse.events.manager.broadcast", new_callable=AsyncMock) as m:
        yield m


class TestBroadcastSessionDiscovered:
    async def test_message_shape(self, mock_broadcast) -> None:
        from agentpulse.events import broadcast_session_discovered

        await broadcast_session_discovered(session_id="s1", cwd="/tmp", timestamp=1.0)
        msg = mock_broadcast.call_args[0][0]
        assert msg["type"] == "session_discovered"
        assert msg["platform"] == "claude"
        assert msg["session_id"] == "s1"
        assert msg["cwd"] == "/tmp"
        assert msg["timestamp"] == 1.0
        assert msg["event_name"] is None
        assert msg["tool_name"] is None
        assert msg["agent_id"] is None


class TestBroadcastSessionEnded:
    async def test_message_shape(self, mock_broadcast) -> None:
        from agentpulse.events import broadcast_session_ended

        await broadcast_session_ended(session_id="s1", cwd="/tmp", timestamp=2.0)
        msg = mock_broadcast.call_args[0][0]
        assert msg["type"] == "session_ended"
        assert msg["session_id"] == "s1"


class TestBroadcastSessionCleared:
    async def test_message_shape(self, mock_broadcast) -> None:
        from agentpulse.events import broadcast_session_cleared

        await broadcast_session_cleared(session_id="s1", cwd="/tmp", timestamp=3.0)
        msg = mock_broadcast.call_args[0][0]
        assert msg["type"] == "session_cleared"
        assert msg["event_name"] == "clear_state"


class TestBroadcastHookEvent:
    async def test_default_type(self, mock_broadcast) -> None:
        from agentpulse.events import broadcast_hook_event

        await broadcast_hook_event(
            session_id="s1",
            event_name="PreToolUse",
            tool_name="Bash",
            agent_id=None,
            cwd="/tmp",
            timestamp=4.0,
        )
        msg = mock_broadcast.call_args[0][0]
        assert msg["type"] == "hook_event"
        assert msg["event_name"] == "PreToolUse"
        assert msg["tool_name"] == "Bash"

    async def test_session_end_maps_to_session_ended(self, mock_broadcast) -> None:
        from agentpulse.events import broadcast_hook_event

        await broadcast_hook_event(
            session_id="s1",
            event_name="SessionEnd",
            tool_name=None,
            agent_id=None,
            cwd=None,
            timestamp=5.0,
        )
        msg = mock_broadcast.call_args[0][0]
        assert msg["type"] == "session_ended"

    async def test_subagent_start_maps_to_agent_started(self, mock_broadcast) -> None:
        from agentpulse.events import broadcast_hook_event

        await broadcast_hook_event(
            session_id="s1",
            event_name="SubagentStart",
            tool_name=None,
            agent_id="a1",
            cwd=None,
            timestamp=6.0,
        )
        msg = mock_broadcast.call_args[0][0]
        assert msg["type"] == "agent_started"

    async def test_subagent_stop_maps_to_agent_stopped(self, mock_broadcast) -> None:
        from agentpulse.events import broadcast_hook_event

        await broadcast_hook_event(
            session_id="s1",
            event_name="SubagentStop",
            tool_name=None,
            agent_id="a1",
            cwd=None,
            timestamp=7.0,
        )
        msg = mock_broadcast.call_args[0][0]
        assert msg["type"] == "agent_stopped"


class TestBroadcastStatuslineUpdate:
    async def test_message_shape(self, mock_broadcast) -> None:
        from agentpulse.events import broadcast_statusline_update

        await broadcast_statusline_update(
            session_id="s1",
            cost_usd=0.05,
            context_used_pct=42.0,
            model_name="Sonnet",
            total_input_tokens=1000,
            total_output_tokens=500,
            lines_added=10,
            lines_removed=3,
            timestamp=8.0,
        )
        msg = mock_broadcast.call_args[0][0]
        assert msg["type"] == "statusline_update"
        assert msg["cost_usd"] == 0.05
        assert msg["model_name"] == "Sonnet"
        assert msg["total_input_tokens"] == 1000


class TestBroadcastLimitsUpdated:
    async def test_message_shape(self, mock_broadcast) -> None:
        from agentpulse.events import broadcast_limits_updated

        await broadcast_limits_updated(
            limits={"daily": 100, "monthly": 1000},
            timestamp=9.0,
        )
        msg = mock_broadcast.call_args[0][0]
        assert msg["type"] == "limits_updated"
        assert msg["platform"] == "claude"
        assert msg["limits"]["daily"] == 100
