# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for session discovery."""

import json
from pathlib import Path
from unittest.mock import patch

import pytest

from agentpulse.db import close_db, init_db
from agentpulse.platforms.claude.discovery import (
    detect_branch,
    discover_sessions,
    run_discovery_tick,
    validate_pid,
)
from agentpulse.platforms.claude import schema


@pytest.fixture
async def db(tmp_path: Path):
    conn = await init_db(db_path=tmp_path / "test.db")
    yield conn
    await close_db()


def _write_session_file(
    directory: Path,
    *,
    pid: int = 1234,
    session_id: str = "s1",
    cwd: str = "/tmp/proj",
    started_at: int = 1000,
    entrypoint: str = "cli",
) -> Path:
    """Write a mock session JSON file."""
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"{session_id}.json"
    path.write_text(
        json.dumps(
            {
                "pid": pid,
                "sessionId": session_id,
                "cwd": cwd,
                "startedAt": started_at,
                "entrypoint": entrypoint,
            }
        ),
        encoding="utf-8",
    )
    return path


class TestDiscoverSessions:
    def test_reads_session_files(self, tmp_path: Path) -> None:
        sessions_dir = tmp_path / "sessions"
        _write_session_file(sessions_dir, session_id="s1", pid=100)
        _write_session_file(sessions_dir, session_id="s2", pid=200)

        result = discover_sessions(sessions_dir=sessions_dir)
        assert len(result) == 2
        ids = {s["session_id"] for s in result}
        assert ids == {"s1", "s2"}

    def test_skips_malformed_json(self, tmp_path: Path) -> None:
        sessions_dir = tmp_path / "sessions"
        sessions_dir.mkdir(parents=True)
        bad = sessions_dir / "bad.json"
        bad.write_text("{not valid json", encoding="utf-8")
        _write_session_file(sessions_dir, session_id="good")

        result = discover_sessions(sessions_dir=sessions_dir)
        assert len(result) == 1

    def test_skips_missing_fields(self, tmp_path: Path) -> None:
        sessions_dir = tmp_path / "sessions"
        sessions_dir.mkdir(parents=True)
        incomplete = sessions_dir / "incomplete.json"
        incomplete.write_text(
            json.dumps({"pid": 0, "sessionId": ""}),
            encoding="utf-8",
        )
        _write_session_file(sessions_dir, session_id="complete")

        result = discover_sessions(sessions_dir=sessions_dir)
        assert len(result) == 1

    def test_nonexistent_dir(self, tmp_path: Path) -> None:
        result = discover_sessions(sessions_dir=tmp_path / "nonexistent")
        assert result == []


class TestValidatePid:
    def test_alive_claude_process(self) -> None:
        with patch("agentpulse.platforms.claude.discovery.psutil") as mock_psutil:
            mock_psutil.pid_exists.return_value = True
            mock_proc = mock_psutil.Process.return_value
            mock_proc.name.return_value = "claude"
            assert validate_pid(pid=1234) is True

    def test_dead_process(self) -> None:
        with patch("agentpulse.platforms.claude.discovery.psutil") as mock_psutil:
            mock_psutil.pid_exists.return_value = False
            assert validate_pid(pid=9999) is False

    def test_non_claude_process(self) -> None:
        with patch("agentpulse.platforms.claude.discovery.psutil") as mock_psutil:
            mock_psutil.pid_exists.return_value = True
            mock_proc = mock_psutil.Process.return_value
            mock_proc.name.return_value = "bash"
            assert validate_pid(pid=1234) is False


class TestDetectBranch:
    def test_normal_branch(self, tmp_path: Path) -> None:
        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        head = git_dir / "HEAD"
        head.write_text("ref: refs/heads/feature/foo\n")

        assert detect_branch(cwd=str(tmp_path)) == "feature/foo"

    def test_detached_head(self, tmp_path: Path) -> None:
        git_dir = tmp_path / ".git"
        git_dir.mkdir()
        head = git_dir / "HEAD"
        head.write_text("abc123def456\n")

        assert detect_branch(cwd=str(tmp_path)) == ""

    def test_not_a_git_repo(self, tmp_path: Path) -> None:
        assert detect_branch(cwd=str(tmp_path)) == ""


class TestRunDiscoveryTick:
    async def test_discovers_new_sessions(self, tmp_path: Path, db) -> None:
        sessions_dir = tmp_path / "sessions"
        _write_session_file(sessions_dir, session_id="new-1", pid=100)

        with patch(
            "agentpulse.platforms.claude.discovery.validate_pid",
            return_value=True,
        ):
            new = await run_discovery_tick(db, sessions_dir=sessions_dir)

        assert len(new) == 1
        assert new[0]["session_id"] == "new-1"

        row = await schema.get_session(db, session_id="new-1")
        assert row is not None
        assert row["pid_alive"] == 1

    async def test_existing_session_not_in_new_list(self, tmp_path: Path, db) -> None:
        sessions_dir = tmp_path / "sessions"
        _write_session_file(sessions_dir, session_id="existing", pid=100)

        with patch(
            "agentpulse.platforms.claude.discovery.validate_pid",
            return_value=True,
        ):
            new1 = await run_discovery_tick(db, sessions_dir=sessions_dir)
            new2 = await run_discovery_tick(db, sessions_dir=sessions_dir)

        assert len(new1) == 1
        assert len(new2) == 0

    async def test_dead_pid_ends_session(self, tmp_path: Path, db) -> None:
        sessions_dir = tmp_path / "sessions"
        _write_session_file(sessions_dir, session_id="will-die", pid=100)

        # First tick: alive
        with patch(
            "agentpulse.platforms.claude.discovery.validate_pid",
            return_value=True,
        ):
            await run_discovery_tick(db, sessions_dir=sessions_dir)

        # Remove session file and make PID dead
        (sessions_dir / "will-die.json").unlink()

        with patch(
            "agentpulse.platforms.claude.discovery.validate_pid",
            return_value=False,
        ):
            await run_discovery_tick(db, sessions_dir=sessions_dir)

        row = await schema.get_session(db, session_id="will-die")
        assert row["pid_alive"] == 0
        assert row["ended_at"] is not None
