# Generated By: Claude Code (Claude Opus 4.7)
"""Tests for agentpulse.bootstrap.ensure_config."""

from pathlib import Path

import pytest

from agentpulse.bootstrap import ensure_config


def test_ensure_config_creates_from_example(tmp_path: Path) -> None:
    example = tmp_path / "config.example.json"
    example.write_text('{"host": "127.0.0.1"}')
    target = tmp_path / "claude" / "agentpulse" / "config.json"

    created = ensure_config(target=target, example=example)

    assert created is True
    assert target.exists()
    assert target.read_text() == '{"host": "127.0.0.1"}'


def test_ensure_config_skips_when_present(tmp_path: Path) -> None:
    example = tmp_path / "config.example.json"
    example.write_text('{"host": "example"}')
    target = tmp_path / "config.json"
    target.write_text('{"host": "user-edit"}')

    created = ensure_config(target=target, example=example)

    assert created is False
    assert target.read_text() == '{"host": "user-edit"}'


def test_ensure_config_raises_when_example_missing(tmp_path: Path) -> None:
    target = tmp_path / "config.json"
    example = tmp_path / "missing.json"

    with pytest.raises(FileNotFoundError):
        ensure_config(target=target, example=example)
