# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for the FastAPI app factory."""

from agentpulse import __version__
from agentpulse.app import create_app


class TestCreateApp:
    def test_returns_fastapi_app(self) -> None:
        app = create_app()
        assert app.title == "AgentPulse"
        assert app.version == __version__

    def test_has_routes(self) -> None:
        app = create_app()
        paths = [route.path for route in app.routes]
        assert "/hooks/claude" in paths
        assert "/api/v1/sessions" in paths
        assert "/api/v1/claude/sessions" in paths
        assert "/ws" in paths
