# Generated By: Claude Code (Claude Opus 4.7)
"""Tests for the `agentpulse init` subcommand."""

from pathlib import Path

import pytest

from agentpulse.cli_init import init_main


def test_init_creates_config(tmp_path: Path, capsys: pytest.CaptureFixture) -> None:
    example = tmp_path / "config.example.json"
    example.write_text('{"host": "127.0.0.1"}')
    target = tmp_path / "agentpulse" / "config.json"

    exit_code = init_main(argv=["--config", str(target)], example=example)

    out = capsys.readouterr().out
    assert exit_code == 0
    assert target.exists()
    assert "created" in out.lower()
    assert str(target) in out


def test_init_idempotent(tmp_path: Path, capsys: pytest.CaptureFixture) -> None:
    example = tmp_path / "config.example.json"
    example.write_text("{}")
    target = tmp_path / "config.json"
    target.write_text('{"user": "edit"}')

    exit_code = init_main(argv=["--config", str(target)], example=example)

    out = capsys.readouterr().out
    assert exit_code == 0
    assert target.read_text() == '{"user": "edit"}'
    assert "already exists" in out.lower()


def test_init_default_target_uses_home(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    example = tmp_path / "config.example.json"
    example.write_text("{}")
    fake_home = tmp_path / "home"
    fake_home.mkdir()
    monkeypatch.setattr("pathlib.Path.home", lambda: fake_home)

    exit_code = init_main(argv=[], example=example)

    assert exit_code == 0
    assert (fake_home / ".claude" / "agentpulse" / "config.json").exists()
