# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for the POST /hooks/claude endpoint."""

from pathlib import Path

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from agentpulse.db import close_db, init_db
from agentpulse.platforms.claude.hooks import router as hooks_router
from agentpulse.platforms.claude import schema
from tests.conftest import run_async


@pytest.fixture
async def db(tmp_path: Path):
    conn = await init_db(db_path=tmp_path / "test.db")
    yield conn
    await close_db()


@pytest.fixture
def client(db) -> TestClient:
    app = FastAPI()
    app.include_router(hooks_router)
    return TestClient(app)


class TestReceiveHook:
    def test_valid_payload_creates_session(self, client) -> None:
        resp = client.post(
            "/hooks/claude",
            json={
                "session_id": "s1",
                "hook_event_name": "PreToolUse",
                "tool_name": "Bash",
                "cwd": "/tmp/proj",
            },
        )
        assert resp.status_code == 200
        assert resp.json() == {"status": "ok"}

    def test_second_event_updates_session(self, client, db) -> None:
        client.post(
            "/hooks/claude",
            json={
                "session_id": "s1",
                "hook_event_name": "PreToolUse",
                "tool_name": "Bash",
            },
        )
        client.post(
            "/hooks/claude",
            json={
                "session_id": "s1",
                "hook_event_name": "PostToolUse",
                "tool_name": "Read",
            },
        )
        row = run_async(schema.get_session(db, session_id="s1"))
        assert row["last_event"] == "PostToolUse"
        assert row["last_tool"] == "Read"

    def test_agent_event_creates_agent(self, client, db) -> None:
        client.post(
            "/hooks/claude",
            json={
                "session_id": "s1",
                "hook_event_name": "PreToolUse",
                "tool_name": "Grep",
                "agent_id": "agent-1",
                "agent_type": "Explore",
            },
        )
        agents = run_async(schema.get_session_agents(db, session_id="s1"))
        assert len(agents) == 1
        assert agents[0]["agent_type"] == "Explore"

    def test_subagent_stop_ends_agent(self, client, db) -> None:
        client.post(
            "/hooks/claude",
            json={
                "session_id": "s1",
                "hook_event_name": "SubagentStart",
                "agent_id": "agent-1",
                "agent_type": "Explore",
            },
        )
        client.post(
            "/hooks/claude",
            json={
                "session_id": "s1",
                "hook_event_name": "SubagentStop",
                "agent_id": "agent-1",
            },
        )
        agents = run_async(schema.get_session_agents(db, session_id="s1"))
        assert agents[0]["ended_at"] is not None

    def test_session_end_sets_ended_at(self, client, db) -> None:
        client.post(
            "/hooks/claude",
            json={
                "session_id": "s1",
                "hook_event_name": "PreToolUse",
            },
        )
        client.post(
            "/hooks/claude",
            json={
                "session_id": "s1",
                "hook_event_name": "SessionEnd",
            },
        )
        row = run_async(schema.get_session(db, session_id="s1"))
        assert row["ended_at"] is not None

    def test_events_appended_to_log(self, client, db) -> None:
        client.post(
            "/hooks/claude",
            json={
                "session_id": "s1",
                "hook_event_name": "PreToolUse",
                "tool_name": "Bash",
            },
        )
        client.post(
            "/hooks/claude",
            json={
                "session_id": "s1",
                "hook_event_name": "PostToolUse",
            },
        )
        events = run_async(schema.get_session_events(db, session_id="s1"))
        assert len(events) == 2

    def test_invalid_json_returns_422(self, client) -> None:
        resp = client.post(
            "/hooks/claude",
            json={"not_a_valid": "payload"},
        )
        assert resp.status_code == 422

    def test_costs_endpoint_returns_501(self, client) -> None:
        resp = client.post("/costs/claude")
        assert resp.status_code == 501
