# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for POST /statusline/claude endpoint."""

from pathlib import Path

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from agentpulse.db import close_db, init_db
from agentpulse.platforms.claude.hooks import router as hooks_router
from agentpulse.platforms.claude import schema
from tests.conftest import run_async

_SAMPLE_STATUSLINE = {
    "session_id": "s1",
    "transcript_path": "/tmp/s1.jsonl",
    "cwd": "/tmp/project",
    "model": {
        "id": "claude-opus-4-6[1m]",
        "display_name": "Opus 4.6 (1M context)",
    },
    "workspace": {
        "current_dir": "/tmp/project",
        "project_dir": "/tmp/project",
        "added_dirs": ["/tmp/project"],
    },
    "version": "2.1.104",
    "cost": {
        "total_cost_usd": 5.25,
        "total_duration_ms": 120000,
        "total_api_duration_ms": 30000,
        "total_lines_added": 100,
        "total_lines_removed": 20,
    },
    "context_window": {
        "total_input_tokens": 10000,
        "total_output_tokens": 50000,
        "context_window_size": 1000000,
        "current_usage": {
            "input_tokens": 5,
            "output_tokens": 200,
            "cache_creation_input_tokens": 500,
            "cache_read_input_tokens": 9000,
        },
        "used_percentage": 25,
        "remaining_percentage": 75,
    },
    "exceeds_200k_tokens": False,
}


@pytest.fixture
async def db(tmp_path: Path):
    conn = await init_db(db_path=tmp_path / "test.db")
    yield conn
    await close_db()


@pytest.fixture
def client(db) -> TestClient:
    app = FastAPI()
    app.include_router(hooks_router)
    return TestClient(app)


class TestReceiveStatusline:
    def test_stores_statusline_data(self, client, db) -> None:
        # First create the session via a hook event
        client.post(
            "/hooks/claude",
            json={
                "session_id": "s1",
                "hook_event_name": "PreToolUse",
                "tool_name": "Bash",
            },
        )
        resp = client.post("/statusline/claude", json=_SAMPLE_STATUSLINE)
        assert resp.status_code == 200
        assert resp.json()["status"] == "ok"

    def test_enriches_session(self, client, db) -> None:
        client.post(
            "/hooks/claude",
            json={
                "session_id": "s1",
                "hook_event_name": "PreToolUse",
            },
        )
        client.post("/statusline/claude", json=_SAMPLE_STATUSLINE)

        row = run_async(schema.get_session(db, session_id="s1"))
        assert row["cost_usd"] == 5.25
        assert row["context_used_pct"] == 25
        assert row["model_name"] == "Opus 4.6 (1M context)"
        assert row["total_input_tokens"] == 10000
        assert row["total_output_tokens"] == 50000

    def test_extracts_numerics_in_history(self, client, db) -> None:
        client.post("/statusline/claude", json=_SAMPLE_STATUSLINE)

        cursor = run_async(
            db.execute("SELECT * FROM claude_statusline WHERE session_id = 's1'")
        )
        rows = run_async(cursor.fetchall())
        assert len(rows) == 1
        row = dict(rows[0])
        assert row["cost_usd"] == 5.25
        assert row["total_input_tokens"] == 10000
        assert row["total_output_tokens"] == 50000
        assert row["context_used_pct"] == 25
        assert row["context_window_size"] == 1000000
        assert row["cache_read_tokens"] == 9000
        assert row["cache_creation_tokens"] == 500
        assert row["duration_ms"] == 120000
        assert row["api_duration_ms"] == 30000
        assert row["lines_added"] == 100
        assert row["lines_removed"] == 20
        assert row["model_name"] == "Opus 4.6 (1M context)"

    def test_ignores_empty_session_id(self, client) -> None:
        data = {**_SAMPLE_STATUSLINE, "session_id": ""}
        resp = client.post("/statusline/claude", json=data)
        assert resp.json()["status"] == "ignored"

    def test_ignores_missing_session_id(self, client) -> None:
        data = {k: v for k, v in _SAMPLE_STATUSLINE.items() if k != "session_id"}
        resp = client.post("/statusline/claude", json=data)
        assert resp.json()["status"] == "ignored"

    def test_handles_minimal_payload(self, client, db) -> None:
        resp = client.post(
            "/statusline/claude",
            json={"session_id": "s2", "model": {"display_name": "Sonnet"}},
        )
        assert resp.status_code == 200

    def test_multiple_updates_create_history(self, client, db) -> None:
        for cost in [1.0, 2.0, 3.0]:
            data = {
                **_SAMPLE_STATUSLINE,
                "cost": {"total_cost_usd": cost},
            }
            client.post("/statusline/claude", json=data)

        cursor = run_async(
            db.execute(
                "SELECT cost_usd FROM claude_statusline"
                " WHERE session_id = 's1' ORDER BY received_at"
            )
        )
        rows = run_async(cursor.fetchall())
        costs = [dict(r)["cost_usd"] for r in rows]
        assert costs == [1.0, 2.0, 3.0]
