# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for agentpulse.db lifecycle."""

from pathlib import Path

import pytest

from agentpulse.db import close_db, get_db, init_db


@pytest.fixture
async def db(tmp_path: Path):
    """Provide an initialized test database."""
    db_path = tmp_path / "test.db"
    conn = await init_db(db_path=db_path)
    yield conn
    await close_db()


class TestDbLifecycle:
    async def test_init_creates_file(self, tmp_path: Path) -> None:
        db_path = tmp_path / "sub" / "test.db"
        await init_db(db_path=db_path)
        assert db_path.exists()
        await close_db()

    async def test_get_db_returns_connection(self, db) -> None:
        conn = await get_db()
        assert conn is db

    async def test_get_db_raises_before_init(self) -> None:
        await close_db()
        with pytest.raises(RuntimeError, match="not initialized"):
            await get_db()

    async def test_close_db_idempotent(self, db) -> None:
        await close_db()
        await close_db()  # Should not raise

    async def test_wal_mode_enabled(self, db) -> None:
        cursor = await db.execute("PRAGMA journal_mode")
        row = await cursor.fetchone()
        assert row[0] == "wal"
