# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for POST /statusline/claude endpoint."""

from pathlib import Path
from unittest.mock import patch

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from agentpulse.db import close_db, init_db
from agentpulse.platforms.claude.hooks import router as hooks_router
from agentpulse.platforms.claude import schema
from tests.conftest import run_async

_SAMPLE_STATUSLINE = {
    "session_id": "s1",
    "transcript_path": "/tmp/s1.jsonl",
    "cwd": "/tmp/project",
    "model": {
        "id": "claude-opus-4-6[1m]",
        "display_name": "Opus 4.6 (1M context)",
    },
    "workspace": {
        "current_dir": "/tmp/project",
        "project_dir": "/tmp/project",
        "added_dirs": ["/tmp/project"],
    },
    "version": "2.1.104",
    "cost": {
        "total_cost_usd": 5.25,
        "total_duration_ms": 120000,
        "total_api_duration_ms": 30000,
        "total_lines_added": 100,
        "total_lines_removed": 20,
    },
    "context_window": {
        "total_input_tokens": 10000,
        "total_output_tokens": 50000,
        "context_window_size": 1000000,
        "current_usage": {
            "input_tokens": 5,
            "output_tokens": 200,
            "cache_creation_input_tokens": 500,
            "cache_read_input_tokens": 9000,
        },
        "used_percentage": 25,
        "remaining_percentage": 75,
    },
    "exceeds_200k_tokens": False,
}


@pytest.fixture
async def db(tmp_path: Path):
    conn = await init_db(db_path=tmp_path / "test.db")
    yield conn
    await close_db()


@pytest.fixture
def client(db) -> TestClient:
    app = FastAPI()
    app.include_router(hooks_router)
    return TestClient(app)


class TestReceiveStatusline:
    def test_stores_statusline_data(self, client, db) -> None:
        # First create the session via a hook event
        client.post(
            "/hooks/claude",
            json={
                "session_id": "s1",
                "hook_event_name": "PreToolUse",
                "tool_name": "Bash",
            },
        )
        resp = client.post("/statusline/claude", json=_SAMPLE_STATUSLINE)
        assert resp.status_code == 200
        assert resp.json()["status"] == "ok"

    def test_enriches_session(self, client, db) -> None:
        client.post(
            "/hooks/claude",
            json={
                "session_id": "s1",
                "hook_event_name": "PreToolUse",
            },
        )
        client.post("/statusline/claude", json=_SAMPLE_STATUSLINE)

        row = run_async(schema.get_session(db, session_id="s1"))
        assert row["cost_usd"] == 5.25
        assert row["context_used_pct"] == 25
        assert row["model_name"] == "Opus 4.6 (1M context)"
        assert row["total_input_tokens"] == 10000
        assert row["total_output_tokens"] == 50000

    def test_extracts_numerics_in_history(self, client, db) -> None:
        client.post("/statusline/claude", json=_SAMPLE_STATUSLINE)

        cursor = run_async(
            db.execute("SELECT * FROM claude_statusline WHERE session_id = 's1'")
        )
        rows = run_async(cursor.fetchall())
        assert len(rows) == 1
        row = dict(rows[0])
        assert row["cost_usd"] == 5.25
        assert row["total_input_tokens"] == 10000
        assert row["total_output_tokens"] == 50000
        assert row["context_used_pct"] == 25
        assert row["context_window_size"] == 1000000
        assert row["cache_read_tokens"] == 9000
        assert row["cache_creation_tokens"] == 500
        assert row["duration_ms"] == 120000
        assert row["api_duration_ms"] == 30000
        assert row["lines_added"] == 100
        assert row["lines_removed"] == 20
        assert row["model_name"] == "Opus 4.6 (1M context)"

    def test_ignores_empty_session_id(self, client) -> None:
        data = {**_SAMPLE_STATUSLINE, "session_id": ""}
        resp = client.post("/statusline/claude", json=data)
        assert resp.json()["status"] == "ignored"

    def test_ignores_missing_session_id(self, client) -> None:
        data = {k: v for k, v in _SAMPLE_STATUSLINE.items() if k != "session_id"}
        resp = client.post("/statusline/claude", json=data)
        assert resp.json()["status"] == "ignored"

    def test_handles_minimal_payload(self, client, db) -> None:
        resp = client.post(
            "/statusline/claude",
            json={"session_id": "s2", "model": {"display_name": "Sonnet"}},
        )
        assert resp.status_code == 200

    def test_multiple_updates_create_history(self, client, db) -> None:
        for cost in [1.0, 2.0, 3.0]:
            data = {
                **_SAMPLE_STATUSLINE,
                "cost": {"total_cost_usd": cost},
            }
            client.post("/statusline/claude", json=data)

        cursor = run_async(
            db.execute(
                "SELECT cost_usd FROM claude_statusline"
                " WHERE session_id = 's1' ORDER BY received_at"
            )
        )
        rows = run_async(cursor.fetchall())
        costs = [dict(r)["cost_usd"] for r in rows]
        assert costs == [1.0, 2.0, 3.0]


class TestStatuslineSessionDiscovery:
    """Statusline creates sessions when they don't exist yet."""

    def test_creates_session_for_unknown_id(self, client, db) -> None:
        resp = client.post("/statusline/claude", json=_SAMPLE_STATUSLINE)
        assert resp.status_code == 200

        row = run_async(schema.get_session(db, session_id="s1"))
        assert row is not None
        assert row["cwd"] == "/tmp/project"
        assert row["pid"] == 0
        assert row["entrypoint"] == "cli"

    def test_broadcasts_session_discovered_for_new(self, client, db) -> None:
        with patch("agentpulse.platforms.claude.hooks.manager.broadcast") as mock_bc:
            client.post("/statusline/claude", json=_SAMPLE_STATUSLINE)

        calls = [c.args[0] for c in mock_bc.call_args_list]
        discovered = [c for c in calls if c["type"] == "session_discovered"]
        assert len(discovered) == 1
        assert discovered[0]["session_id"] == "s1"
        assert discovered[0]["cwd"] == "/tmp/project"
        assert discovered[0]["platform"] == "claude"

    def test_no_duplicate_discovery_for_existing(self, client, db) -> None:
        # Create session via hook first
        client.post(
            "/hooks/claude",
            json={
                "session_id": "s1",
                "hook_event_name": "PreToolUse",
                "tool_name": "Bash",
            },
        )
        with patch("agentpulse.platforms.claude.hooks.manager.broadcast") as mock_bc:
            client.post("/statusline/claude", json=_SAMPLE_STATUSLINE)

        calls = [c.args[0] for c in mock_bc.call_args_list]
        discovered = [c for c in calls if c["type"] == "session_discovered"]
        assert len(discovered) == 0
        updates = [c for c in calls if c["type"] == "statusline_update"]
        assert len(updates) == 1

    def test_hook_enriches_statusline_created_session(self, client, db) -> None:
        # Create via statusline (pid=0)
        client.post("/statusline/claude", json=_SAMPLE_STATUSLINE)
        row = run_async(schema.get_session(db, session_id="s1"))
        assert row["pid"] == 0

        # Hook arrives with real pid
        client.post(
            "/hooks/claude",
            json={
                "session_id": "s1",
                "hook_event_name": "PreToolUse",
                "tool_name": "Bash",
                "pid": 12345,
                "cwd": "/tmp/project",
                "source_system": "myhost",
            },
        )
        row = run_async(schema.get_session(db, session_id="s1"))
        assert row["pid"] == 12345
        assert row["source_system"] == "myhost"

    def test_cwd_fallback_chain(self, client, db) -> None:
        # No workspace, but top-level cwd
        data = {
            "session_id": "s-fallback",
            "cwd": "/fallback/path",
            "model": {"display_name": "Sonnet"},
        }
        client.post("/statusline/claude", json=data)

        row = run_async(schema.get_session(db, session_id="s-fallback"))
        assert row is not None
        assert row["cwd"] == "/fallback/path"

    def test_statusline_with_injected_pid_and_source(self, client, db) -> None:
        data = {
            **_SAMPLE_STATUSLINE,
            "session_id": "s-injected",
            "pid": 9999,
            "source_system": "remote-host",
        }
        with patch(
            "agentpulse.platforms.claude.hooks.detect_entrypoint",
            return_value="vscode",
        ):
            client.post("/statusline/claude", json=data)

        row = run_async(schema.get_session(db, session_id="s-injected"))
        assert row["pid"] == 9999
        assert row["source_system"] == "remote-host"
        assert row["entrypoint"] == "vscode"
