# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for agentpulse.config."""

import json
from pathlib import Path

import pytest

from agentpulse.config import (
    DEFAULT_DISCOVERY_INTERVAL_SECONDS,
    DEFAULT_HOST,
    DEFAULT_LOG_LEVEL,
    DEFAULT_PORT,
    Settings,
    get_settings,
    reset_settings,
    set_config_path,
)


class TestSettings:
    def test_defaults_when_file_missing(self) -> None:
        settings = Settings.from_config(config_path=Path("/nonexistent"))
        assert settings.host == DEFAULT_HOST
        assert settings.port == DEFAULT_PORT
        assert settings.log_level == DEFAULT_LOG_LEVEL
        assert settings.discovery_interval_seconds == (
            DEFAULT_DISCOVERY_INTERVAL_SECONDS
        )

    def test_from_config_file(self, tmp_path: Path) -> None:
        config = tmp_path / "config.json"
        config.write_text(json.dumps({"host": "0.0.0.0", "port": 9000}))
        settings = Settings.from_config(config_path=config)
        assert settings.host == "0.0.0.0"
        assert settings.port == 9000

    def test_log_level_from_file(self, tmp_path: Path) -> None:
        config = tmp_path / "config.json"
        config.write_text(json.dumps({"log_level": "debug"}))
        settings = Settings.from_config(config_path=config)
        assert settings.log_level == "DEBUG"

    def test_log_file_from_config(self, tmp_path: Path) -> None:
        config = tmp_path / "config.json"
        config.write_text(json.dumps({"log_file": "/tmp/custom.log"}))
        settings = Settings.from_config(config_path=config)
        assert settings.log_file == Path("/tmp/custom.log")

    def test_db_path_from_file(self, tmp_path: Path) -> None:
        config = tmp_path / "config.json"
        config.write_text(json.dumps({"db_path": "/custom/path.db"}))
        settings = Settings.from_config(config_path=config)
        assert settings.db_path == Path("/custom/path.db")

    def test_db_path_is_path_object(self) -> None:
        settings = Settings()
        assert isinstance(settings.db_path, Path)

    def test_invalid_json_uses_defaults(self, tmp_path: Path) -> None:
        config = tmp_path / "config.json"
        config.write_text("{bad json")
        settings = Settings.from_config(config_path=config)
        assert settings.host == DEFAULT_HOST


class TestGetSettings:
    def test_returns_singleton(self, tmp_path: Path) -> None:
        reset_settings()
        config = tmp_path / "config.json"
        config.write_text(json.dumps({}))
        set_config_path(config_path=config)
        s1 = get_settings()
        s2 = get_settings()
        assert s1 is s2

    def test_reset_clears_singleton(self, tmp_path: Path) -> None:
        reset_settings()
        config = tmp_path / "config.json"
        config.write_text(json.dumps({}))
        set_config_path(config_path=config)
        s1 = get_settings()
        reset_settings()
        s2 = get_settings()
        assert s1 is not s2

    def test_raises_without_config_path(self) -> None:
        import agentpulse.config as cfg

        cfg._settings = None
        cfg._config_path = None
        with pytest.raises(RuntimeError, match="Config path not set"):
            get_settings()
