# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Tests for pidfile module — identification must be precise."""

from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from agentpulse import pidfile


@pytest.fixture(autouse=True)
def _isolate_pidfile_dir(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(pidfile, "_BASE_DIR", tmp_path / "pidfiles")


class TestReadWriteRemove:
    def test_write_creates_dir_and_file(self) -> None:
        path = pidfile.write_pid("svc", pid=12345)
        assert path.exists()
        assert path.read_text() == "12345"

    def test_read_returns_pid(self) -> None:
        pidfile.write_pid("svc", pid=999)
        assert pidfile.read_pid("svc") == 999

    def test_read_missing_returns_none(self) -> None:
        assert pidfile.read_pid("nope") is None

    def test_read_corrupt_returns_none(self) -> None:
        path = pidfile.pidfile_path("corrupt")
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("not-a-number")
        assert pidfile.read_pid("corrupt") is None

    def test_remove_is_idempotent(self) -> None:
        pidfile.remove_pid("never-existed")
        pidfile.write_pid("tmp", pid=42)
        pidfile.remove_pid("tmp")
        pidfile.remove_pid("tmp")
        assert pidfile.read_pid("tmp") is None

    def test_write_defaults_to_current_pid(self) -> None:
        import os

        pidfile.write_pid("self")
        assert pidfile.read_pid("self") == os.getpid()


class TestIsProcessOurs:
    def test_nonexistent_pid_returns_false(self) -> None:
        import psutil

        with patch("psutil.Process", side_effect=psutil.NoSuchProcess(pid=0)):
            assert pidfile.is_process_ours(99999) is False

    def test_access_denied_returns_false(self) -> None:
        import psutil

        with patch("psutil.Process", side_effect=psutil.AccessDenied(pid=0)):
            assert pidfile.is_process_ours(1) is False

    def test_matches_on_name(self) -> None:
        fake = MagicMock()
        fake.name.return_value = "agentpulse.exe"
        fake.cmdline.return_value = []
        with patch("psutil.Process", return_value=fake):
            assert pidfile.is_process_ours(1234) is True

    def test_matches_python_dash_m_form(self) -> None:
        fake = MagicMock()
        fake.name.return_value = "python.exe"
        fake.cmdline.return_value = ["python.exe", "-m", "agentpulse", "--config", "x"]
        with patch("psutil.Process", return_value=fake):
            assert pidfile.is_process_ours(1234) is True

    def test_matches_python_main_module(self) -> None:
        fake = MagicMock()
        fake.name.return_value = "python3"
        fake.cmdline.return_value = [
            "/usr/bin/python3",
            "/home/u/src/agentpulse/__main__.py",
            "--config",
            "x",
        ]
        with patch("psutil.Process", return_value=fake):
            assert pidfile.is_process_ours(1234) is True

    def test_rejects_vscode_with_agentpulse_workspace(self) -> None:
        """Regression: VS Code opened on a folder named 'agentpulse' has the
        folder path in its cmdline. It must NOT be treated as ours, even if
        the service pidfile's PID is stale and got recycled to this process."""
        fake = MagicMock()
        fake.name.return_value = "Code.exe"
        fake.cmdline.return_value = [
            "Code.exe",
            "C:\\Users\\jewza\\source\\agentpulse",
        ]
        with patch("psutil.Process", return_value=fake):
            assert pidfile.is_process_ours(1234) is False

    def test_rejects_git_bash_in_agentpulse_dir(self) -> None:
        """Regression: git bash running in the agentpulse folder should not
        be terminated by a stale pidfile match."""
        fake = MagicMock()
        fake.name.return_value = "bash.exe"
        fake.cmdline.return_value = [
            "C:\\Program Files\\Git\\bin\\bash.exe",
            "--login",
            "-i",
        ]
        with patch("psutil.Process", return_value=fake):
            assert pidfile.is_process_ours(1234) is False

    def test_rejects_claude_code_in_agentpulse_dir(self) -> None:
        """Regression: Claude Code invoked with agentpulse in its argv (e.g.
        as a working directory) should not match."""
        fake = MagicMock()
        fake.name.return_value = "claude.exe"
        fake.cmdline.return_value = [
            "claude.exe",
            "--cwd",
            "C:\\Users\\jewza\\source\\agentpulse",
        ]
        with patch("psutil.Process", return_value=fake):
            assert pidfile.is_process_ours(1234) is False

    def test_rejects_plain_python_without_module(self) -> None:
        fake = MagicMock()
        fake.name.return_value = "python.exe"
        fake.cmdline.return_value = ["python.exe", "-c", "print('agentpulse')"]
        with patch("psutil.Process", return_value=fake):
            assert pidfile.is_process_ours(1234) is False
