# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for normalized session API endpoints."""

from pathlib import Path

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from agentpulse.api.sessions import router as sessions_router
from agentpulse.db import close_db, init_db
from agentpulse.platforms.claude.hooks import router as hooks_router
from agentpulse.platforms.claude import schema
from tests.conftest import run_async


@pytest.fixture
async def db(tmp_path: Path):
    conn = await init_db(db_path=tmp_path / "test.db")
    yield conn
    await close_db()


@pytest.fixture
def client(db) -> TestClient:
    app = FastAPI()
    app.include_router(sessions_router)
    app.include_router(hooks_router)
    return TestClient(app)


async def _seed_session(
    db,
    *,
    session_id: str = "s1",
    pid: int = 1234,
    cwd: str = "/tmp/proj",
    last_event: str = "PreToolUse",
    last_tool: str = "Bash",
) -> None:
    await schema.upsert_session(
        db,
        session_id=session_id,
        pid=pid,
        cwd=cwd,
        entrypoint="cli",
        started_at=1000,
        last_event=last_event,
        last_tool=last_tool,
        last_event_at=1.0,
    )


class TestListSessions:
    def test_empty(self, client) -> None:
        resp = client.get("/api/v1/sessions")
        assert resp.status_code == 200
        assert resp.json() == []

    def test_returns_sessions(self, client, db) -> None:
        run_async(_seed_session(db, session_id="s1"))
        resp = client.get("/api/v1/sessions")
        data = resp.json()
        assert len(data) == 1
        assert data[0]["session_id"] == "s1"
        assert data[0]["platform"] == "claude"
        assert data[0]["derived_state"] == "working"

    def test_active_filter(self, client, db) -> None:
        run_async(_seed_session(db, session_id="alive"))
        run_async(_seed_session(db, session_id="dead"))
        run_async(
            schema.update_session_pid_alive(db, session_id="dead", pid_alive=False)
        )

        resp = client.get("/api/v1/sessions?active=true")
        data = resp.json()
        assert len(data) == 1
        assert data[0]["session_id"] == "alive"


class TestGetSession:
    def test_found(self, client, db) -> None:
        run_async(_seed_session(db))
        resp = client.get("/api/v1/sessions/s1")
        assert resp.status_code == 200
        data = resp.json()
        assert data["session_id"] == "s1"
        assert "agents" in data

    def test_not_found(self, client) -> None:
        resp = client.get("/api/v1/sessions/nonexistent")
        assert resp.status_code == 404

    def test_includes_agents(self, client, db) -> None:
        run_async(_seed_session(db))
        run_async(
            schema.upsert_agent(
                db,
                agent_id="a1",
                session_id="s1",
                agent_type="Explore",
                last_event="PreToolUse",
                last_tool="Grep",
            )
        )

        resp = client.get("/api/v1/sessions/s1")
        data = resp.json()
        assert data["agent_count"] == 1
        assert len(data["agents"]) == 1
        assert data["agents"][0]["agent_type"] == "Explore"


class TestGetSessionEvents:
    def test_returns_events(self, client, db) -> None:
        run_async(_seed_session(db))
        run_async(
            schema.insert_event(
                db,
                session_id="s1",
                event_name="PreToolUse",
                tool_name="Bash",
                received_at=1.0,
            )
        )

        resp = client.get("/api/v1/sessions/s1/events")
        assert resp.status_code == 200
        data = resp.json()
        assert len(data) == 1
        assert data[0]["event_name"] == "PreToolUse"

    def test_session_not_found(self, client) -> None:
        resp = client.get("/api/v1/sessions/nonexistent/events")
        assert resp.status_code == 404


class TestGetSessionAgents:
    def test_returns_agents(self, client, db) -> None:
        run_async(_seed_session(db))
        run_async(schema.upsert_agent(db, agent_id="a1", session_id="s1"))

        resp = client.get("/api/v1/sessions/s1/agents")
        assert resp.status_code == 200
        assert len(resp.json()) == 1


class TestSummary:
    def test_empty(self, client) -> None:
        resp = client.get("/api/v1/summary")
        data = resp.json()
        assert data["active_sessions"] == 0
        assert data["total_agents"] == 0

    def test_with_sessions(self, client, db) -> None:
        run_async(
            _seed_session(
                db,
                session_id="s1",
                last_event="PreToolUse",
                last_tool="Bash",
            )
        )
        run_async(
            _seed_session(
                db,
                session_id="s2",
                last_event="Stop",
                last_tool="",
            )
        )

        resp = client.get("/api/v1/summary")
        data = resp.json()
        assert data["active_sessions"] == 2
        assert "working" in data["state_breakdown"]


class TestClearSession:
    def test_clears_state(self, client, db) -> None:
        run_async(
            _seed_session(
                db, session_id="s1", last_event="PreToolUse", last_tool="Bash"
            )
        )
        run_async(
            schema.upsert_agent(
                db,
                agent_id="a1",
                session_id="s1",
                agent_type="Explore",
                last_event="PreToolUse",
            )
        )

        resp = client.post("/api/v1/sessions/s1/clear")
        assert resp.status_code == 200
        assert resp.json()["status"] == "cleared"

        # Session state should be wiped
        row = run_async(schema.get_session(db, session_id="s1"))
        assert row["last_event"] is None
        assert row["last_tool"] is None
        assert row["last_event_at"] is None

        # Agent should be ended
        agents = run_async(schema.get_session_agents(db, session_id="s1"))
        assert agents[0]["ended_at"] is not None

        # A clear_state event should exist
        events = run_async(schema.get_session_events(db, session_id="s1"))
        assert any(e["event_name"] == "clear_state" for e in events)

    def test_not_found(self, client) -> None:
        resp = client.post("/api/v1/sessions/nonexistent/clear")
        assert resp.status_code == 404


class TestSourceSystem:
    def test_session_includes_source_system(self, client, db) -> None:
        run_async(
            schema.upsert_session(
                db,
                session_id="s1",
                pid=1234,
                cwd="/tmp",
                source_system="my-workstation",
            )
        )
        resp = client.get("/api/v1/sessions/s1")
        data = resp.json()
        assert data["source_system"] == "my-workstation"

    def test_hook_sets_source_system(self, client, db) -> None:
        client.post(
            "/hooks/claude",
            json={
                "session_id": "s1",
                "hook_event_name": "PreToolUse",
                "tool_name": "Bash",
                "source_system": "remote-vm",
            },
        )
        row = run_async(schema.get_session(db, session_id="s1"))
        assert row["source_system"] == "remote-vm"
