# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Tests for prior_cost_usd split (cost before today's local midnight)."""

from pathlib import Path
from unittest.mock import patch

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from agentpulse.api.sessions import router as sessions_router
from agentpulse.db import close_db, init_db
from agentpulse.platforms.claude.hooks import router as hooks_router
from agentpulse.platforms.claude import schema
from agentpulse.timeutil import local_midnight_epoch
from tests.conftest import run_async


@pytest.fixture
async def db(tmp_path: Path):
    conn = await init_db(db_path=tmp_path / "test.db")
    yield conn
    await close_db()


@pytest.fixture
def client(db) -> TestClient:
    app = FastAPI()
    app.include_router(sessions_router)
    app.include_router(hooks_router)
    return TestClient(app)


async def _seed_session(db, *, session_id: str = "s1") -> None:
    await schema.upsert_session(
        db,
        session_id=session_id,
        pid=1234,
        cwd="/tmp/proj",
        entrypoint="cli",
        started_at=1000,
        last_event="PreToolUse",
        last_tool="Bash",
        last_event_at=1.0,
    )


async def _seed_statusline(
    db,
    *,
    session_id: str,
    received_at: float,
    cost_usd: float,
) -> None:
    await schema.insert_statusline(
        db,
        session_id=session_id,
        received_at=received_at,
        cost_usd=cost_usd,
        raw_payload="{}",
    )


class TestLocalMidnightEpoch:
    def test_returns_float(self) -> None:
        ts = local_midnight_epoch()
        assert isinstance(ts, float)

    def test_is_in_the_past(self) -> None:
        import time as _time

        assert local_midnight_epoch() <= _time.time()


class TestGetPriorCost:
    async def test_no_statusline_returns_zero(self, db) -> None:
        result = await schema.get_prior_cost(
            db, session_id="missing", before_ts=9999999999.0
        )
        assert result == 0.0

    async def test_returns_max_before_ts(self, db) -> None:
        await _seed_session(db)
        await _seed_statusline(db, session_id="s1", received_at=100.0, cost_usd=1.0)
        await _seed_statusline(db, session_id="s1", received_at=200.0, cost_usd=3.0)
        await _seed_statusline(db, session_id="s1", received_at=300.0, cost_usd=5.0)

        result = await schema.get_prior_cost(db, session_id="s1", before_ts=250.0)
        assert result == 3.0

    async def test_strict_inequality_at_boundary(self, db) -> None:
        """Rows at exactly before_ts do NOT count as prior."""
        await _seed_session(db)
        await _seed_statusline(db, session_id="s1", received_at=500.0, cost_usd=2.0)

        at_boundary = await schema.get_prior_cost(db, session_id="s1", before_ts=500.0)
        past_boundary = await schema.get_prior_cost(
            db, session_id="s1", before_ts=500.0001
        )
        assert at_boundary == 0.0
        assert past_boundary == 2.0

    async def test_ignores_null_cost(self, db) -> None:
        await _seed_session(db)
        await schema.insert_statusline(
            db, session_id="s1", received_at=100.0, cost_usd=None, raw_payload="{}"
        )
        result = await schema.get_prior_cost(db, session_id="s1", before_ts=200.0)
        assert result == 0.0


class TestGetPriorCostsByIds:
    async def test_empty_list(self, db) -> None:
        result = await schema.get_prior_costs_by_session_ids(
            db, session_ids=[], before_ts=1.0
        )
        assert result == {}

    async def test_groups_by_session(self, db) -> None:
        await _seed_session(db, session_id="a")
        await _seed_session(db, session_id="b")
        await _seed_statusline(db, session_id="a", received_at=100.0, cost_usd=1.0)
        await _seed_statusline(db, session_id="a", received_at=200.0, cost_usd=4.0)
        await _seed_statusline(db, session_id="b", received_at=100.0, cost_usd=7.0)

        result = await schema.get_prior_costs_by_session_ids(
            db, session_ids=["a", "b", "c"], before_ts=300.0
        )
        assert result == {"a": 4.0, "b": 7.0}


class TestApiListSessions:
    def test_prior_cost_zero_when_no_statusline(self, client, db) -> None:
        run_async(_seed_session(db, session_id="s1"))
        resp = client.get("/api/v1/sessions")
        assert resp.status_code == 200
        data = resp.json()
        assert data[0]["session_id"] == "s1"
        assert data[0]["prior_cost_usd"] == 0.0

    def test_prior_cost_splits_across_midnight(self, client, db) -> None:
        run_async(_seed_session(db, session_id="s1"))
        midnight = local_midnight_epoch()
        run_async(
            _seed_statusline(
                db, session_id="s1", received_at=midnight - 3600, cost_usd=2.5
            )
        )
        run_async(
            _seed_statusline(
                db, session_id="s1", received_at=midnight - 60, cost_usd=4.0
            )
        )
        run_async(
            _seed_statusline(
                db, session_id="s1", received_at=midnight + 60, cost_usd=7.0
            )
        )
        run_async(schema.update_session_statusline(db, session_id="s1", cost_usd=7.0))

        resp = client.get("/api/v1/sessions")
        data = resp.json()
        assert data[0]["cost_usd"] == 7.0
        assert data[0]["prior_cost_usd"] == 4.0

    def test_session_only_today_has_zero_prior(self, client, db) -> None:
        run_async(_seed_session(db, session_id="s1"))
        midnight = local_midnight_epoch()
        run_async(
            _seed_statusline(
                db, session_id="s1", received_at=midnight + 10, cost_usd=1.5
            )
        )
        run_async(schema.update_session_statusline(db, session_id="s1", cost_usd=1.5))

        resp = client.get("/api/v1/sessions")
        data = resp.json()
        assert data[0]["cost_usd"] == 1.5
        assert data[0]["prior_cost_usd"] == 0.0


class TestApiSessionDetail:
    def test_detail_includes_prior_cost(self, client, db) -> None:
        run_async(_seed_session(db, session_id="s1"))
        midnight = local_midnight_epoch()
        run_async(
            _seed_statusline(
                db, session_id="s1", received_at=midnight - 3600, cost_usd=9.9
            )
        )
        run_async(
            _seed_statusline(
                db, session_id="s1", received_at=midnight + 10, cost_usd=12.0
            )
        )
        run_async(schema.update_session_statusline(db, session_id="s1", cost_usd=12.0))

        resp = client.get("/api/v1/sessions/s1")
        data = resp.json()
        assert data["prior_cost_usd"] == 9.9
        assert data["cost_usd"] == 12.0


class TestBroadcastPriorCost:
    def test_statusline_broadcast_includes_prior_cost(self, client, db) -> None:
        run_async(_seed_session(db, session_id="s1"))
        midnight = local_midnight_epoch()
        run_async(
            _seed_statusline(
                db, session_id="s1", received_at=midnight - 100, cost_usd=6.0
            )
        )

        payload = {
            "session_id": "s1",
            "cost": {"total_cost_usd": 8.5},
            "model": {"display_name": "Opus"},
        }
        with patch("agentpulse.events.manager.broadcast") as mock_bc:
            client.post("/statusline/claude", json=payload)

        updates = [
            c.args[0]
            for c in mock_bc.call_args_list
            if c.args[0]["type"] == "statusline_update"
        ]
        assert len(updates) == 1
        assert updates[0]["cost_usd"] == 8.5
        assert updates[0]["prior_cost_usd"] == 6.0

    def test_statusline_broadcast_zero_when_no_prior(self, client, db) -> None:
        payload = {
            "session_id": "fresh",
            "cost": {"total_cost_usd": 2.0},
            "model": {"display_name": "Sonnet"},
        }
        with patch("agentpulse.events.manager.broadcast") as mock_bc:
            client.post("/statusline/claude", json=payload)

        updates = [
            c.args[0]
            for c in mock_bc.call_args_list
            if c.args[0]["type"] == "statusline_update"
        ]
        assert updates[0]["prior_cost_usd"] == 0.0
