# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""/api/v2/* endpoints — derived processes, sessions, raw log streams.

Slice A3 of the v2 rollout. Wires the queries module's projections to
FastAPI routes.
"""

import logging

from fastapi import APIRouter, HTTPException, Query

from agentpulse.api.v2 import queries
from agentpulse.api.v2.models import (
    AgentResponse,
    ApiLimitsResponse,
    EpochResponse,
    EventResponse,
    PidDeathResponse,
    ProcessResponse,
    SessionResponse,
    StatuslineResponse,
)
from agentpulse.db import get_db

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v2")


def _epoch_to_response(d: dict) -> EpochResponse:
    return EpochResponse(**d)


def _agent_to_response(d: dict, *, process_id: str) -> AgentResponse:
    return AgentResponse(
        agent_id=d["agent_id"],
        session_id=d["session_id"],
        process_id=process_id,
        agent_type=d["agent_type"],
        started_at=d["started_at"],
        ended_at=d["ended_at"],
        last_event=d["last_event"],
        last_tool=d["last_tool"],
        last_event_at=d["last_event_at"],
        derived_state=d["derived_state"],
    )


def _session_to_response(d: dict) -> SessionResponse:
    epochs = (
        [_epoch_to_response(e) for e in d["epochs"]]
        if d["epochs"] is not None
        else None
    )
    agents = (
        [_agent_to_response(a, process_id=d["process_id"]) for a in d["agents"]]
        if d["agents"] is not None
        else None
    )
    return SessionResponse(
        session_id=d["session_id"],
        process_id=d["process_id"],
        pid=d["pid"],
        source_system=d["source_system"],
        cwd=d["cwd"],
        started_at=d["started_at"],
        last_activity_at=d["last_activity_at"],
        ended_at=d["ended_at"],
        last_event=d["last_event"],
        last_tool=d["last_tool"],
        last_event_at=d["last_event_at"],
        context_used_pct=d["context_used_pct"],
        context_window_size=d["context_window_size"],
        model_id=d["model_id"],
        model_name=d["model_name"],
        agent_count=d["agent_count"],
        derived_state=d["derived_state"],
        epoch_count=d["epoch_count"],
        epochs=epochs,
        agents=agents,
    )


def _process_to_response(d: dict) -> ProcessResponse:
    sessions = (
        [_session_to_response(s) for s in d["sessions"]]
        if d["sessions"] is not None
        else None
    )
    return ProcessResponse(
        process_id=d["process_id"],
        pid=d["pid"],
        source_system=d["source_system"],
        cwd=d["cwd"],
        entrypoint=d["entrypoint"],
        claude_version=d["claude_version"],
        permission_mode=d["permission_mode"],
        started_at=d["started_at"],
        last_activity_at=d["last_activity_at"],
        ended_at=d["ended_at"],
        pid_alive=d["pid_alive"],
        current_session_id=d["current_session_id"],
        derived_state=d["derived_state"],
        cost_usd=d["cost_usd"],
        cost_by_day=d["cost_by_day"],
        total_input_tokens=d["total_input_tokens"],
        total_output_tokens=d["total_output_tokens"],
        lines_added=d["lines_added"],
        lines_removed=d["lines_removed"],
        model_id=d["model_id"],
        model_name=d["model_name"],
        session_count=d["session_count"],
        epoch_count=d["epoch_count"],
        sessions=sessions,
    )


# ---- /processes --------------------------------------------------------------


@router.get("/processes", response_model=list[ProcessResponse])
async def list_processes(
    active: bool = False,
    source_system: str | None = None,
    cwd: str | None = None,
    since: float | None = None,
) -> list[ProcessResponse]:
    db = await get_db()
    procs = await queries.get_processes(
        db,
        active_only=active,
        source_system=source_system,
        cwd=cwd,
        since=since,
    )
    return [_process_to_response(p) for p in procs]


@router.get("/processes/{process_id}", response_model=ProcessResponse)
async def get_process(process_id: str) -> ProcessResponse:
    db = await get_db()
    detail = await queries.get_process_by_id(db, process_id=process_id)
    if detail is None:
        raise HTTPException(status_code=404, detail="process not found")
    return _process_to_response(detail)


# ---- /sessions ---------------------------------------------------------------


@router.get("/sessions", response_model=list[SessionResponse])
async def list_sessions(
    active: bool = False,
    process_id: str | None = None,
    since: float | None = None,
) -> list[SessionResponse]:
    db = await get_db()
    sessions = await queries.get_sessions(
        db, active_only=active, process_id=process_id, since=since
    )
    return [_session_to_response(s) for s in sessions]


@router.get("/sessions/{session_id}", response_model=SessionResponse)
async def get_session(session_id: str) -> SessionResponse:
    db = await get_db()
    sess = await queries.get_session_by_id(db, session_id=session_id)
    if sess is None:
        raise HTTPException(status_code=404, detail="session not found")
    return _session_to_response(sess)


# ---- /log/hooks --------------------------------------------------------------


@router.get("/log/hooks", response_model=list[EventResponse])
async def list_log_hooks(
    since: float | None = None,
    until: float | None = None,
    session_id: str | None = None,
    pid: int | None = None,
    source_system: str | None = None,
    cwd: str | None = None,
    agent_id: str | None = None,
    event_name: str | None = None,
    tool_name: str | None = None,
    limit: int = Query(default=100, ge=1, le=1000),
    offset: int = Query(default=0, ge=0),
) -> list[EventResponse]:
    db = await get_db()
    rows = await queries.get_log_hooks(
        db,
        since=since,
        until=until,
        session_id=session_id,
        pid=pid,
        source_system=source_system,
        cwd=cwd,
        agent_id=agent_id,
        event_name=event_name,
        tool_name=tool_name,
        limit=limit,
        offset=offset,
    )
    enricher = queries.IdEnricher(db)
    out: list[EventResponse] = []
    for r in rows:
        proc_id = await enricher.process_id(
            pid=r["pid"],
            source_system=r["source_system"],
            cwd=r["cwd"],
            received_at=r["received_at"],
        )
        epoch_id = await enricher.epoch_id(
            session_id=r["session_id"],
            pid=r["pid"],
            source_system=r["source_system"],
            cwd=r["cwd"],
        )
        out.append(
            EventResponse(
                id=r["id"],
                session_id=r["session_id"],
                process_id=proc_id,
                epoch_id=epoch_id,
                agent_id=r["agent_id"],
                pid=r["pid"],
                source_system=r["source_system"],
                cwd=r["cwd"],
                event_name=r["event_name"],
                tool_name=r["tool_name"],
                permission_mode=r["permission_mode"],
                claude_version=r["claude_version"],
                received_at=r["received_at"],
                received_by=r["received_by"],
                raw_payload=r.get("raw_payload"),
            )
        )
    return out


# ---- /log/statuslines --------------------------------------------------------


@router.get("/log/statuslines", response_model=list[StatuslineResponse])
async def list_log_statuslines(
    since: float | None = None,
    until: float | None = None,
    session_id: str | None = None,
    pid: int | None = None,
    source_system: str | None = None,
    cwd: str | None = None,
    limit: int = Query(default=100, ge=1, le=1000),
    offset: int = Query(default=0, ge=0),
) -> list[StatuslineResponse]:
    db = await get_db()
    rows = await queries.get_log_statuslines(
        db,
        since=since,
        until=until,
        session_id=session_id,
        pid=pid,
        source_system=source_system,
        cwd=cwd,
        limit=limit,
        offset=offset,
    )
    enricher = queries.IdEnricher(db)
    out: list[StatuslineResponse] = []
    for r in rows:
        proc_id = await enricher.process_id(
            pid=r["pid"],
            source_system=r["source_system"],
            cwd=r["cwd"],
            received_at=r["received_at"],
        )
        epoch_id = await enricher.epoch_id(
            session_id=r["session_id"],
            pid=r["pid"],
            source_system=r["source_system"],
            cwd=r["cwd"],
        )
        out.append(
            StatuslineResponse(
                id=r["id"],
                session_id=r["session_id"],
                process_id=proc_id,
                epoch_id=epoch_id,
                pid=r["pid"],
                source_system=r["source_system"],
                cwd=r["cwd"],
                project_dir=r["project_dir"],
                model_id=r["model_id"],
                model_name=r["model_name"],
                claude_version=r["claude_version"],
                cost_usd=r["cost_usd"],
                total_input_tokens=r["total_input_tokens"],
                total_output_tokens=r["total_output_tokens"],
                context_used_pct=r["context_used_pct"],
                context_window_size=r["context_window_size"],
                cache_read_tokens=r["cache_read_tokens"],
                cache_creation_tokens=r["cache_creation_tokens"],
                duration_seconds=r["duration_seconds"],
                api_duration_seconds=r["api_duration_seconds"],
                lines_added=r["lines_added"],
                lines_removed=r["lines_removed"],
                exceeds_200k_tokens=bool(r["exceeds_200k_tokens"]),
                received_at=r["received_at"],
                received_by=r["received_by"],
                raw_payload=r.get("raw_payload"),
            )
        )
    return out


# ---- /log/pid-deaths --------------------------------------------------------


@router.get("/log/pid-deaths", response_model=list[PidDeathResponse])
async def list_log_pid_deaths(
    since: float | None = None,
    until: float | None = None,
    pid: int | None = None,
    source_system: str | None = None,
    cwd: str | None = None,
    limit: int = Query(default=100, ge=1, le=1000),
    offset: int = Query(default=0, ge=0),
) -> list[PidDeathResponse]:
    """Raw read of claude_log_pid_deaths. since/until bound observed_at."""
    db = await get_db()
    rows = await queries.get_log_pid_deaths(
        db,
        since=since,
        until=until,
        pid=pid,
        source_system=source_system,
        cwd=cwd,
        limit=limit,
        offset=offset,
    )
    enricher = queries.IdEnricher(db)
    out: list[PidDeathResponse] = []
    for r in rows:
        # Pass observed_at as the "row time" — the death belongs to the
        # instance that was alive immediately before observed_at, which
        # _instance_started_at_for resolves correctly.
        proc_id = await enricher.process_id(
            pid=r["pid"],
            source_system=r["source_system"],
            cwd=r["cwd"],
            received_at=r["observed_at"],
        )
        out.append(
            PidDeathResponse(
                id=r["id"],
                pid=r["pid"],
                source_system=r["source_system"],
                cwd=r["cwd"],
                process_id=proc_id,
                observed_at=r["observed_at"],
                observed_by=r["observed_by"],
            )
        )
    return out


# ---- /log/api-limits --------------------------------------------------------


@router.get("/log/api-limits", response_model=list[ApiLimitsResponse])
async def list_log_api_limits(
    since: float | None = None,
    until: float | None = None,
    limit: int = Query(default=100, ge=1, le=1000),
    offset: int = Query(default=0, ge=0),
) -> list[ApiLimitsResponse]:
    """Raw read of claude_log_api_limits. Account-scoped — no identity filters.

    since/until bound received_at. raw_response is included by default.
    """
    db = await get_db()
    rows = await queries.get_log_api_limits(
        db, since=since, until=until, limit=limit, offset=offset
    )
    return [
        ApiLimitsResponse(
            id=r["id"],
            received_at=r["received_at"],
            received_by=r["received_by"],
            five_hour_utilization=r["five_hour_utilization"],
            five_hour_resets_at=r["five_hour_resets_at"],
            seven_day_utilization=r["seven_day_utilization"],
            seven_day_resets_at=r["seven_day_resets_at"],
            raw_response=r["raw_response"],
        )
        for r in rows
    ]
