# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Derived state for v2 — session and effective-state computation.

Mirrors docs/reference/state-transitions.md. Differs from v1 in two places:

1. `Stop` maps to `ready` (transient). v1 maps to `idle`.
2. Priority is `permission_required > awaiting_input > ready > working > idle`.
   v1 had `working > ready` (legacy mistake — see plan-v2-refactor.md).

Also handles the synthetic `clear_state` event which v1 didn't have.
"""

# State priority — lower number = higher priority. Matches the v2 ordering
# in api.md: ready outranks working (main session "done" beats a background
# agent still ticking).
_STATE_PRIORITY: dict[str, int] = {
    "permission_required": 0,
    "awaiting_input": 1,
    "ready": 2,
    "working": 3,
    "idle": 4,
}


def derive_state(
    event_name: str,
    *,
    tool_name: str = "",
    agent_id: str = "",
) -> str | None:
    """Derive a state string from a single hook event.

    Returns None for events that don't map to a state (e.g. SessionEnd,
    SubagentStop) — those are terminal markers, not states.

    The agent flag biases derivation: an unknown event with an agent_id
    means "an agent is doing something" → working. Without an agent it's
    just unknown.
    """
    if event_name == "PreToolUse":
        if tool_name == "AskUserQuestion":
            return "awaiting_input"
        return "working"

    if event_name == "PermissionRequest":
        if tool_name == "AskUserQuestion":
            return "awaiting_input"
        return "permission_required"

    if event_name in ("UserPromptSubmit", "PostToolUse", "PostToolUseFailure"):
        return "working"

    if event_name in ("Stop", "StopFailure"):
        return "ready"

    if event_name == "clear_state":
        return "idle"

    if event_name == "SubagentStart":
        return "working"

    if event_name in ("SessionEnd", "SubagentStop"):
        return None

    if agent_id:
        return "working"
    return None


def compute_effective_state(
    session_state: str | None,
    agent_states: list[str | None],
) -> str | None:
    """Highest-priority state across the session and any active agents.

    Returns None if no state is known (no hooks yet, or all are terminal).
    """
    candidates = [session_state, *agent_states]
    best: str | None = None
    best_priority = 999
    for s in candidates:
        if s is None:
            continue
        p = _STATE_PRIORITY.get(s, 999)
        if p < best_priority:
            best = s
            best_priority = p
    return best
