# Generated By: Claude Code (Claude Opus 4.6)
"""Broadcast throttle for hook_logged events.

Debounces same-state events per (session_id, agent_id) scope.
State changes and lifecycle events bypass the throttle and broadcast
immediately. Same-state events buffer behind a configurable timer;
the latest buffered event broadcasts when the window expires.

Storage is unaffected — all events are still written to
claude_log_hooks. Only the WebSocket broadcast is coalesced.
"""

import asyncio
import logging
import time
from dataclasses import dataclass, field

from agentpulse.api.v2.events import broadcast_hook_logged
from agentpulse.api.v2.state import derive_state

logger = logging.getLogger(__name__)

_IMMEDIATE_EVENTS: frozenset[str] = frozenset(
    {
        "SessionStart",
        "SessionEnd",
        "SubagentStart",
        "SubagentStop",
        "UserPromptSubmit",
        "clear_state",
        "Notification",
    }
)

_TERMINAL_EVENTS: frozenset[str] = frozenset(
    {
        "SessionEnd",
        "SubagentStop",
    }
)


@dataclass
class _Slot:
    last_broadcast_state: str | None = None
    pending_event: dict | None = None
    timer_handle: asyncio.TimerHandle | None = None
    last_activity_at: float = field(default_factory=time.time)


class HookBroadcastThrottle:
    """Debounces hook_logged broadcasts per (session_id, agent_id).

    Immediate broadcast on state changes and lifecycle events.
    Same-state events coalesce within a configurable debounce window.
    """

    def __init__(self, *, debounce_seconds: float = 0.5) -> None:
        self._debounce_seconds = debounce_seconds
        self._slots: dict[tuple[str, str], _Slot] = {}

    @property
    def slot_count(self) -> int:
        return len(self._slots)

    async def submit(self, **kwargs: object) -> None:
        """Accept a hook event and decide whether to broadcast or buffer."""
        event_name: str = kwargs.get("event_name", "")  # type: ignore[assignment]
        session_id: str = kwargs.get("session_id", "")  # type: ignore[assignment]
        agent_id: str = kwargs.get("agent_id") or ""  # type: ignore[assignment]
        tool_name: str = kwargs.get("tool_name") or ""  # type: ignore[assignment]

        derived = derive_state(event_name, tool_name=tool_name, agent_id=agent_id)
        kwargs["derived_state"] = derived

        if self._debounce_seconds <= 0:
            await broadcast_hook_logged(**kwargs)  # type: ignore[arg-type]
            return

        key = (session_id, agent_id)
        slot = self._slots.get(key)

        is_immediate = (
            event_name in _IMMEDIATE_EVENTS
            or derived is None
            or slot is None
            or derived != slot.last_broadcast_state
        )

        if is_immediate or slot is None:
            self._cancel_pending(key)
            if slot is None:
                slot = _Slot()
                self._slots[key] = slot
            slot.last_broadcast_state = derived
            slot.last_activity_at = time.time()
            await broadcast_hook_logged(**kwargs)  # type: ignore[arg-type]
            if event_name in _TERMINAL_EVENTS:
                self._remove_scope(session_id, agent_id)
        else:
            slot.pending_event = dict(kwargs)  # type: ignore[arg-type]
            slot.last_activity_at = time.time()
            if slot.timer_handle is None:
                loop = asyncio.get_running_loop()

                def _schedule_flush(k: tuple[str, str] = key) -> None:
                    asyncio.ensure_future(self._flush_slot(k))

                slot.timer_handle = loop.call_later(
                    self._debounce_seconds, _schedule_flush
                )

    async def _flush_slot(self, key: tuple[str, str]) -> None:
        """Timer callback — broadcast the latest buffered event."""
        slot = self._slots.get(key)
        if slot is None or slot.pending_event is None:
            return
        kwargs = slot.pending_event
        slot.pending_event = None
        slot.timer_handle = None
        slot.last_broadcast_state = kwargs.get("derived_state")
        await broadcast_hook_logged(**kwargs)  # type: ignore[arg-type]

    def _cancel_pending(self, key: tuple[str, str]) -> None:
        slot = self._slots.get(key)
        if slot is None:
            return
        if slot.timer_handle is not None:
            slot.timer_handle.cancel()
            slot.timer_handle = None
        slot.pending_event = None

    def _remove_scope(self, session_id: str, agent_id: str) -> None:
        if agent_id:
            key = (session_id, agent_id)
            self._cancel_pending(key)
            self._slots.pop(key, None)
        else:
            keys = [k for k in self._slots if k[0] == session_id]
            for k in keys:
                self._cancel_pending(k)
                self._slots.pop(k, None)

    def clear_session(self, session_id: str) -> None:
        """Remove all slots for a session (e.g. on pid death)."""
        self._remove_scope(session_id, "")

    def sweep_stale(self, *, max_age_seconds: float = 300.0) -> int:
        """Evict slots inactive for longer than max_age_seconds."""
        now = time.time()
        stale = [
            k
            for k, s in self._slots.items()
            if now - s.last_activity_at > max_age_seconds
        ]
        for k in stale:
            self._cancel_pending(k)
            self._slots.pop(k, None)
        if stale:
            logger.debug("throttle: swept %d stale slots", len(stale))
        return len(stale)

    def shutdown(self) -> None:
        """Cancel all pending timers (called during app shutdown)."""
        for key in list(self._slots):
            self._cancel_pending(key)
        self._slots.clear()


hook_throttle = HookBroadcastThrottle()
