# Generated By: Claude Code (Claude Opus 4.6 (1M context))
"""Tests for the UI cost and activity aggregation.

Cost data flows through the v2 sessions API (get_sessions → cost_by_day),
so these tests seed the same hook + statusline rows and verify the
aggregated output matches the session-derived cost_by_day values.
"""

from pathlib import Path

import pytest

from agentpulse.db import close_db, init_db
from agentpulse.platforms.claude import schema
from agentpulse.ui import costs


@pytest.fixture
async def db(tmp_path: Path):
    conn = await init_db(db_path=tmp_path / "test.db")
    yield conn
    await close_db()


DAY1_START = 1777152463.0
DAY2_START = DAY1_START + 86400.0
DAY3_START = DAY1_START + 2 * 86400.0


async def _seed_statusline(
    db,
    *,
    session_id: str,
    pid: int,
    received_at: float,
    cost_usd: float,
    cwd: str = "/proj",
    source_system: str = "host",
    input_tokens: int | None = None,
    output_tokens: int | None = None,
) -> None:
    ctx: dict = {}
    if input_tokens is not None:
        ctx["total_input_tokens"] = input_tokens
    if output_tokens is not None:
        ctx["total_output_tokens"] = output_tokens
    payload = {
        "session_id": session_id,
        "pid": pid,
        "source_system": source_system,
        "cwd": cwd,
        "cost": {"total_cost_usd": cost_usd},
        "context_window": ctx,
    }
    await schema.insert_log_statusline(
        db, payload=payload, received_at=received_at, received_by="test"
    )
    await db.commit()


async def _seed_hook(
    db,
    *,
    session_id: str,
    pid: int,
    received_at: float,
    event_name: str,
    cwd: str = "/proj",
    agent_id: str | None = None,
) -> None:
    payload = {
        "session_id": session_id,
        "pid": pid,
        "source_system": "host",
        "cwd": cwd,
        "hook_event_name": event_name,
    }
    if agent_id is not None:
        payload["agent_id"] = agent_id
    await schema.insert_log_hook(
        db, payload=payload, received_at=received_at, received_by="test"
    )
    await db.commit()


class TestCostsByDay:
    async def test_empty_db_returns_empty_list(self, db) -> None:
        result = await costs.costs_by_day(db)
        assert result == []

    async def test_single_session_one_day(self, db) -> None:
        await _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY1_START + 60, cost_usd=2.5
        )
        result = await costs.costs_by_day(db)
        assert len(result) == 1
        assert result[0]["total_cost_usd"] == pytest.approx(2.5)

    async def test_single_session_two_days_uses_deltas(self, db) -> None:
        await _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY1_START + 60, cost_usd=3.0
        )
        await _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY2_START + 60, cost_usd=5.0
        )
        result = await costs.costs_by_day(db)
        assert len(result) == 2
        assert result[0]["total_cost_usd"] == pytest.approx(2.0)
        assert result[1]["total_cost_usd"] == pytest.approx(3.0)

    async def test_multi_session_same_day_sums(self, db) -> None:
        await _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY1_START + 60, cost_usd=2.0
        )
        await _seed_statusline(
            db, session_id="s2", pid=20, received_at=DAY1_START + 120, cost_usd=3.0
        )
        result = await costs.costs_by_day(db)
        assert len(result) == 1
        assert result[0]["total_cost_usd"] == pytest.approx(5.0)

    async def test_resumed_session_same_day_uses_max(self, db) -> None:
        """cost_usd is session-cumulative — resumed PID inherits the total."""
        await _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY1_START + 60, cost_usd=4.0
        )
        await _seed_statusline(
            db, session_id="s1", pid=20, received_at=DAY1_START + 120, cost_usd=5.5
        )
        result = await costs.costs_by_day(db)
        assert len(result) == 1
        assert result[0]["total_cost_usd"] == pytest.approx(5.5)

    async def test_resumed_session_across_days_no_double_count(self, db) -> None:
        """--resume inherits cumulative cost; don't double-count the baseline."""
        await _seed_hook(
            db,
            session_id="s1",
            pid=10,
            received_at=DAY1_START + 10,
            event_name="SessionStart",
        )
        await _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY1_START + 60, cost_usd=10.0
        )
        await _seed_statusline(
            db, session_id="s1", pid=20, received_at=DAY2_START + 60, cost_usd=15.0
        )
        result = await costs.costs_by_day(db)
        by_day = {row["day"]: row["total_cost_usd"] for row in result}
        days = sorted(by_day.keys())
        assert by_day[days[0]] == pytest.approx(10.0)
        assert by_day[days[1]] == pytest.approx(5.0)

    async def test_resumed_session_inherited_cost_not_on_first_day(self, db) -> None:
        """Session first observed mid-lifecycle — inherited cost excluded."""
        await _seed_hook(
            db,
            session_id="s1",
            pid=10,
            received_at=DAY1_START + 10,
            event_name="UserPromptSubmit",
        )
        await _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY1_START + 60, cost_usd=100.0
        )
        await _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY1_START + 120, cost_usd=100.5
        )
        result = await costs.costs_by_day(db)
        assert len(result) == 1
        assert result[0]["total_cost_usd"] == pytest.approx(0.5)

    async def test_tokens_from_process(self, db) -> None:
        await _seed_statusline(
            db,
            session_id="s1",
            pid=10,
            received_at=DAY1_START + 60,
            cost_usd=2.0,
            input_tokens=1000,
            output_tokens=500,
        )
        result = await costs.costs_by_day(db)
        assert len(result) == 1
        assert result[0]["total_tokens"] == 1500

    async def test_tokens_two_processes_same_day(self, db) -> None:
        await _seed_statusline(
            db,
            session_id="s1",
            pid=10,
            received_at=DAY1_START + 60,
            cost_usd=1.0,
            input_tokens=100,
            output_tokens=50,
        )
        await _seed_statusline(
            db,
            session_id="s2",
            pid=20,
            received_at=DAY1_START + 120,
            cost_usd=1.5,
            input_tokens=200,
            output_tokens=70,
        )
        result = await costs.costs_by_day(db)
        assert len(result) == 1
        assert result[0]["total_tokens"] == 420

    async def test_returns_descending_by_day(self, db) -> None:
        await _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY1_START + 60, cost_usd=1.0
        )
        await _seed_statusline(
            db, session_id="s2", pid=20, received_at=DAY3_START + 60, cost_usd=2.0
        )
        result = await costs.costs_by_day(db)
        days = [row["day"] for row in result]
        assert days == sorted(days, reverse=True)

    async def test_session_count_from_hooks(self, db) -> None:
        await _seed_hook(
            db,
            session_id="s1",
            pid=10,
            received_at=DAY1_START + 10,
            event_name="SessionStart",
        )
        await _seed_hook(
            db,
            session_id="s2",
            pid=20,
            received_at=DAY1_START + 20,
            event_name="SessionStart",
        )
        await _seed_hook(
            db,
            session_id="s3",
            pid=30,
            received_at=DAY2_START + 10,
            event_name="SessionStart",
        )
        result = await costs.costs_by_day(db)
        by_day = {row["day"]: row for row in result}
        days = sorted(by_day.keys())
        assert by_day[days[0]]["session_count"] == 2
        assert by_day[days[1]]["session_count"] == 1

    async def test_message_count_from_stop_events(self, db) -> None:
        for i in range(3):
            await _seed_hook(
                db,
                session_id="s1",
                pid=10,
                received_at=DAY1_START + 10 + i,
                event_name="Stop",
            )
        result = await costs.costs_by_day(db)
        assert len(result) == 1
        assert result[0]["message_count"] == 6

    async def test_subagent_stops_excluded_from_message_count(self, db) -> None:
        await _seed_hook(
            db,
            session_id="s1",
            pid=10,
            received_at=DAY1_START + 10,
            event_name="Stop",
        )
        await _seed_hook(
            db,
            session_id="s1",
            pid=10,
            received_at=DAY1_START + 20,
            event_name="Stop",
            agent_id="agent-123",
        )
        result = await costs.costs_by_day(db)
        assert len(result) == 1
        assert result[0]["message_count"] == 2

    async def test_hooks_only_day_has_zero_cost(self, db) -> None:
        await _seed_hook(
            db,
            session_id="s1",
            pid=10,
            received_at=DAY1_START + 10,
            event_name="SessionStart",
        )
        result = await costs.costs_by_day(db)
        assert len(result) == 1
        assert result[0]["total_cost_usd"] == 0.0
        assert result[0]["total_tokens"] == 0
        assert result[0]["session_count"] == 1

    async def test_cost_only_day_has_zero_activity(self, db) -> None:
        await _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY1_START + 60, cost_usd=3.0
        )
        result = await costs.costs_by_day(db)
        assert len(result) == 1
        assert result[0]["session_count"] == 0
        assert result[0]["message_count"] == 0
        assert result[0]["total_cost_usd"] == pytest.approx(3.0)

    async def test_row_has_all_fields(self, db) -> None:
        await _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY1_START + 60, cost_usd=1.0
        )
        await _seed_hook(
            db,
            session_id="s1",
            pid=10,
            received_at=DAY1_START + 10,
            event_name="Stop",
        )
        result = await costs.costs_by_day(db)
        assert len(result) == 1
        row = result[0]
        assert set(row.keys()) == {
            "day",
            "session_count",
            "message_count",
            "total_tokens",
            "total_cost_usd",
        }


class TestCostsByDayCwd:
    async def test_empty_db_returns_empty_list(self, db) -> None:
        result = await costs.costs_by_day_cwd(db)
        assert result == []

    async def test_single_cwd_single_day(self, db) -> None:
        await _seed_statusline(
            db,
            session_id="s1",
            pid=10,
            received_at=DAY1_START + 60,
            cost_usd=3.0,
            cwd="/proj/a",
        )
        result = await costs.costs_by_day_cwd(db)
        assert len(result) == 1
        assert result[0]["cwd"] == "/proj/a"
        assert result[0]["total_cost_usd"] == pytest.approx(3.0)

    async def test_two_cwds_same_day_split(self, db) -> None:
        await _seed_statusline(
            db,
            session_id="s1",
            pid=10,
            received_at=DAY1_START + 60,
            cost_usd=2.0,
            cwd="/proj/a",
        )
        await _seed_statusline(
            db,
            session_id="s2",
            pid=20,
            received_at=DAY1_START + 120,
            cost_usd=3.0,
            cwd="/proj/b",
        )
        result = await costs.costs_by_day_cwd(db)
        assert len(result) == 2
        by_cwd = {row["cwd"]: row["total_cost_usd"] for row in result}
        assert by_cwd["/proj/a"] == pytest.approx(2.0)
        assert by_cwd["/proj/b"] == pytest.approx(3.0)

    async def test_same_cwd_multi_day(self, db) -> None:
        await _seed_statusline(
            db,
            session_id="s1",
            pid=10,
            received_at=DAY1_START + 60,
            cost_usd=2.0,
            cwd="/proj/a",
        )
        await _seed_statusline(
            db,
            session_id="s1",
            pid=10,
            received_at=DAY2_START + 60,
            cost_usd=5.0,
            cwd="/proj/a",
        )
        result = await costs.costs_by_day_cwd(db)
        assert len(result) == 2
        for row in result:
            assert row["cwd"] == "/proj/a"
        by_day = {row["day"]: row["total_cost_usd"] for row in result}
        days = sorted(by_day.keys())
        assert by_day[days[0]] == pytest.approx(2.0)
        assert by_day[days[1]] == pytest.approx(3.0)

    async def test_returns_descending_by_day_then_cwd(self, db) -> None:
        await _seed_statusline(
            db,
            session_id="s1",
            pid=10,
            received_at=DAY1_START + 60,
            cost_usd=1.0,
            cwd="/proj/a",
        )
        await _seed_statusline(
            db,
            session_id="s2",
            pid=20,
            received_at=DAY1_START + 120,
            cost_usd=1.0,
            cwd="/proj/b",
        )
        await _seed_statusline(
            db,
            session_id="s3",
            pid=30,
            received_at=DAY2_START + 60,
            cost_usd=1.0,
            cwd="/proj/a",
        )
        result = await costs.costs_by_day_cwd(db)
        days = [row["day"] for row in result]
        assert days == sorted(days, reverse=True)

    async def test_session_count_per_cwd(self, db) -> None:
        await _seed_hook(
            db,
            session_id="s1",
            pid=10,
            received_at=DAY1_START + 10,
            event_name="SessionStart",
            cwd="/proj/a",
        )
        await _seed_hook(
            db,
            session_id="s2",
            pid=20,
            received_at=DAY1_START + 20,
            event_name="SessionStart",
            cwd="/proj/a",
        )
        await _seed_hook(
            db,
            session_id="s3",
            pid=30,
            received_at=DAY1_START + 30,
            event_name="SessionStart",
            cwd="/proj/b",
        )
        result = await costs.costs_by_day_cwd(db)
        by_cwd = {row["cwd"]: row for row in result}
        assert by_cwd["/proj/a"]["session_count"] == 2
        assert by_cwd["/proj/b"]["session_count"] == 1

    async def test_row_has_all_fields(self, db) -> None:
        await _seed_statusline(
            db,
            session_id="s1",
            pid=10,
            received_at=DAY1_START + 60,
            cost_usd=1.0,
            cwd="/proj/a",
        )
        result = await costs.costs_by_day_cwd(db)
        assert len(result) == 1
        row = result[0]
        assert set(row.keys()) == {
            "day",
            "cwd",
            "session_count",
            "message_count",
            "total_tokens",
            "total_cost_usd",
        }
