# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for the dashboard UI's HTTP surface (/ui/* routes)."""

from pathlib import Path

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from agentpulse.db import close_db, init_db
from agentpulse.platforms.claude import schema
from agentpulse.ui import router as ui_router
from tests.conftest import run_async


@pytest.fixture
async def db(tmp_path: Path):
    conn = await init_db(db_path=tmp_path / "test.db")
    yield conn
    await close_db()


@pytest.fixture
def client(db) -> TestClient:
    app = FastAPI()
    app.include_router(ui_router)
    return TestClient(app)


DAY1_START = 1777152463.0
DAY2_START = DAY1_START + 86400.0


def _seed_statusline(
    db,
    *,
    session_id: str,
    pid: int,
    received_at: float,
    cost_usd: float,
    cwd: str = "/proj",
    source_system: str = "host",
) -> None:
    payload = {
        "session_id": session_id,
        "pid": pid,
        "source_system": source_system,
        "cwd": cwd,
        "cost": {"total_cost_usd": cost_usd},
    }
    run_async(
        schema.insert_log_statusline(
            db, payload=payload, received_at=received_at, received_by="test"
        )
    )
    run_async(db.commit())


class TestCostsByDayEndpoint:
    def test_empty_db_returns_empty_list(self, client) -> None:
        resp = client.get("/ui/api/costs/by-day")
        assert resp.status_code == 200
        assert resp.json() == []

    def test_returns_per_day_totals(self, client, db) -> None:
        _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY1_START + 60, cost_usd=2.0
        )
        _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY2_START + 60, cost_usd=5.0
        )
        resp = client.get("/ui/api/costs/by-day")
        assert resp.status_code == 200
        data = resp.json()
        assert len(data) == 2
        assert data[0]["total_cost_usd"] == pytest.approx(3.0)
        assert data[1]["total_cost_usd"] == pytest.approx(2.0)
        expected_keys = {
            "day",
            "session_count",
            "message_count",
            "total_tokens",
            "total_cost_usd",
        }
        assert set(data[0].keys()) == expected_keys


class TestCostsByDayCwdEndpoint:
    def test_empty_db_returns_empty_list(self, client) -> None:
        resp = client.get("/ui/api/costs/by-day-cwd")
        assert resp.status_code == 200
        assert resp.json() == []

    def test_returns_per_day_per_cwd_totals(self, client, db) -> None:
        _seed_statusline(
            db,
            session_id="s1",
            pid=10,
            received_at=DAY1_START + 60,
            cost_usd=2.0,
            cwd="/proj/a",
        )
        _seed_statusline(
            db,
            session_id="s2",
            pid=20,
            received_at=DAY1_START + 120,
            cost_usd=3.0,
            cwd="/proj/b",
        )
        resp = client.get("/ui/api/costs/by-day-cwd")
        assert resp.status_code == 200
        data = resp.json()
        assert len(data) == 2
        by_cwd = {row["cwd"]: row["total_cost_usd"] for row in data}
        assert by_cwd["/proj/a"] == pytest.approx(2.0)
        assert by_cwd["/proj/b"] == pytest.approx(3.0)
        expected_keys = {
            "day",
            "cwd",
            "session_count",
            "message_count",
            "total_tokens",
            "total_cost_usd",
        }
        assert set(data[0].keys()) == expected_keys


class TestCostsPage:
    def test_returns_html(self, client) -> None:
        resp = client.get("/ui/costs")
        assert resp.status_code == 200
        assert resp.headers["content-type"].startswith("text/html")

    def test_html_references_endpoints(self, client) -> None:
        resp = client.get("/ui/costs")
        body = resp.text
        assert "/ui/api/costs/by-day" in body
        assert "/ui/api/costs/by-day-cwd" in body
