# Generated By: Claude Code (Claude Opus 4.7)
"""Restore httpx.AsyncClient in client tests.

The root conftest globally blocks ``httpx.AsyncClient`` and friends via
an autouse fixture. Client tests need the real classes back so they can
exercise the rest module against ``httpx.MockTransport``. We capture the
real classes at import time (before any test runs) and re-install them
under the test scope.
"""

from __future__ import annotations

import httpx
import pytest

_REAL_ASYNC_CLIENT = httpx.AsyncClient
_REAL_CLIENT = httpx.Client


@pytest.fixture(autouse=True)
def _restore_httpx(monkeypatch: pytest.MonkeyPatch) -> None:
    """Re-install the real ``httpx.AsyncClient`` for client-test scope."""
    monkeypatch.setattr(httpx, "AsyncClient", _REAL_ASYNC_CLIENT)
    monkeypatch.setattr(httpx, "Client", _REAL_CLIENT)
