# Generated By: Claude Code (Claude Opus 4.7)
"""Tests for agentpulse.client.aio.AsyncAgentPulseClient.

Mocks ``websockets.connect`` and uses ``httpx.MockTransport`` for REST
so the connect → bootstrap → consume flow is exercised end-to-end
without a real server.
"""

from __future__ import annotations

import asyncio
from typing import Any

import httpx
import pytest

import agentpulse.client.aio as aio_module
from agentpulse.client.aio import AsyncAgentPulseClient
from agentpulse.client.config import ClientConfig
from agentpulse.client.types import ConnectionState


class _FakeWebSocket:
    """Async iterable yielding pre-queued frames, then blocking forever."""

    def __init__(self, frames: list[str]) -> None:
        self._frames = list(frames)
        self._closed = asyncio.Event()

    def __aiter__(self) -> "_FakeWebSocket":
        return self

    async def __anext__(self) -> str:
        if self._frames:
            return self._frames.pop(0)
        await self._closed.wait()
        raise StopAsyncIteration

    def close(self) -> None:
        self._closed.set()


class _FakeConnect:
    """async context manager replacement for ``websockets.connect``."""

    def __init__(self, ws: _FakeWebSocket) -> None:
        self._ws = ws

    async def __aenter__(self) -> _FakeWebSocket:
        return self._ws

    async def __aexit__(self, *exc: Any) -> None:
        self._ws.close()


def _config() -> ClientConfig:
    return ClientConfig(
        host="h",
        port=1,
        fetch_limits=True,
        initial_backoff_s=0.01,
        backoff_cap_s=0.05,
        http_timeout_s=1.0,
    )


def _install_mock_transport(client: AsyncAgentPulseClient, handler: Any) -> None:
    """Replace the client's ``httpx.AsyncClient`` with a MockTransport one."""
    client._http = httpx.AsyncClient(transport=httpx.MockTransport(handler))


def _bootstrap_handler(
    sessions: list[dict[str, Any]] | None = None,
    statuslines: list[dict[str, Any]] | None = None,
    limits: list[dict[str, Any]] | None = None,
) -> Any:
    sessions = sessions if sessions is not None else []
    statuslines = statuslines if statuslines is not None else []
    limits = limits if limits is not None else []

    def handler(request: httpx.Request) -> httpx.Response:
        path = request.url.path
        if path == "/api/v2/sessions":
            return httpx.Response(200, json=sessions)
        if path == "/api/v2/log/statuslines":
            return httpx.Response(200, json=statuslines)
        if path == "/api/v2/log/api-limits":
            return httpx.Response(200, json=limits)
        return httpx.Response(404)

    return handler


@pytest.fixture
def patch_websockets(monkeypatch: pytest.MonkeyPatch) -> Any:
    """Patch ``websockets.connect`` to return a controllable fake."""
    holder: dict[str, _FakeWebSocket] = {}

    def patch(frames: list[str] | None = None) -> _FakeWebSocket:
        ws = _FakeWebSocket(frames or [])
        holder["ws"] = ws

        def fake_connect(uri: str, **kwargs: Any) -> _FakeConnect:
            return _FakeConnect(ws)

        monkeypatch.setattr(aio_module.websockets, "connect", fake_connect)
        return ws

    return patch


@pytest.mark.asyncio
async def test_start_runs_bootstrap_and_sets_connected(patch_websockets: Any) -> None:
    patch_websockets()
    client = AsyncAgentPulseClient(_config())
    sessions = [
        {
            "session_id": "s1",
            "process_id": "p1",
            "pid": 1,
            "source_system": "h",
            "cwd": "/c",
            "started_at": 1.0,
            "last_activity_at": 1.0,
            "ended_at": None,
            "last_event": None,
            "last_tool": None,
            "last_event_at": None,
            "context_used_pct": None,
            "context_window_size": None,
            "model_id": None,
            "model_name": None,
            "agent_count": 0,
            "derived_state": None,
            "epoch_count": 0,
            "total_cost_usd": 1.5,
            "cost_by_day": {"2026-04-30": 1.5},
            "epochs": None,
            "agents": None,
        }
    ]
    handler = _bootstrap_handler(sessions=sessions)
    client._http = httpx.AsyncClient(transport=httpx.MockTransport(handler))
    try:
        await client.start()
        await asyncio.sleep(0.05)
        assert client.connection_state() == ConnectionState.CONNECTED
        snapshot = client.sessions()
        assert len(snapshot) == 1
        assert snapshot[0].session_id == "s1"
    finally:
        await client.stop()


@pytest.mark.asyncio
async def test_dispatch_unknown_session_triggers_refresh(
    patch_websockets: Any,
) -> None:
    patch_websockets()
    client = AsyncAgentPulseClient(_config())
    fetched: list[str] = []

    def handler(request: httpx.Request) -> httpx.Response:
        path = request.url.path
        if path == "/api/v2/sessions":
            return httpx.Response(200, json=[])
        if path == "/api/v2/log/statuslines":
            return httpx.Response(200, json=[])
        if path == "/api/v2/log/api-limits":
            return httpx.Response(200, json=[])
        if path.startswith("/api/v2/sessions/"):
            session_id = path.rsplit("/", 1)[-1]
            fetched.append(session_id)
            return httpx.Response(
                200,
                json={
                    "session_id": session_id,
                    "process_id": "p1",
                    "pid": 1,
                    "source_system": "h",
                    "cwd": "/c",
                    "started_at": 1.0,
                    "last_activity_at": 1.0,
                    "ended_at": None,
                    "last_event": None,
                    "last_tool": None,
                    "last_event_at": None,
                    "context_used_pct": None,
                    "context_window_size": None,
                    "model_id": None,
                    "model_name": None,
                    "agent_count": 0,
                    "derived_state": None,
                    "epoch_count": 0,
                    "total_cost_usd": 0.0,
                    "cost_by_day": {},
                    "epochs": None,
                    "agents": None,
                },
            )
        return httpx.Response(404)

    client._http = httpx.AsyncClient(transport=httpx.MockTransport(handler))
    try:
        await client.start()
        # Drive an unknown-session frame through the dispatcher directly.
        await client._dispatch(
            {
                "type": "hook_logged",
                "session_id": "ghost",
                "process_id": "p1",
                "event_name": "PreToolUse",
                "received_at": 5.0,
                "derived_state": "working",
            }
        )
        # refresh_session is fire-and-forget; let it run.
        await asyncio.sleep(0.05)
        assert "ghost" in fetched
        assert client.session("ghost") is not None
    finally:
        await client.stop()


@pytest.mark.asyncio
async def test_dispatch_statusline_logged_creates_pending(
    patch_websockets: Any,
) -> None:
    patch_websockets()
    client = AsyncAgentPulseClient(_config())
    handler = _bootstrap_handler()
    client._http = httpx.AsyncClient(transport=httpx.MockTransport(handler))
    try:
        await client.start()
        await client._dispatch(
            {
                "type": "statusline_logged",
                "session_id": "fresh",
                "process_id": "p1",
                "pid": 1,
                "source_system": "h",
                "cwd": "/c",
                "session_total_cost_usd": 7.5,
                "session_today_cost_usd": 2.0,
                "total_input_tokens": 100,
                "total_output_tokens": 200,
                "lines_added": 5,
                "lines_removed": 1,
                "received_at": 10.0,
            }
        )
        s = client.session("fresh")
        assert s is not None
        assert s.total_cost_usd == 7.5
        assert s.total_input_tokens == 100
    finally:
        await client.stop()


@pytest.mark.asyncio
async def test_dispatch_ignores_unknown_type(patch_websockets: Any) -> None:
    patch_websockets()
    client = AsyncAgentPulseClient(_config())
    handler = _bootstrap_handler()
    client._http = httpx.AsyncClient(transport=httpx.MockTransport(handler))
    try:
        await client.start()
        # Should not raise.
        await client._dispatch({"type": "future_message_type"})
    finally:
        await client.stop()


@pytest.mark.asyncio
async def test_disconnect_preserves_store(patch_websockets: Any) -> None:
    """On disconnect the store must keep its last-known sessions."""
    ws = patch_websockets()
    client = AsyncAgentPulseClient(_config())
    sessions = [
        {
            "session_id": "s1",
            "process_id": "p1",
            "pid": 1,
            "source_system": "h",
            "cwd": "/c",
            "started_at": 1.0,
            "last_activity_at": 1.0,
            "ended_at": None,
            "last_event": None,
            "last_tool": None,
            "last_event_at": None,
            "context_used_pct": None,
            "context_window_size": None,
            "model_id": None,
            "model_name": None,
            "agent_count": 0,
            "derived_state": None,
            "epoch_count": 0,
            "total_cost_usd": 1.5,
            "cost_by_day": {},
            "epochs": None,
            "agents": None,
        }
    ]
    client._http = httpx.AsyncClient(
        transport=httpx.MockTransport(_bootstrap_handler(sessions=sessions))
    )
    try:
        await client.start()
        await asyncio.sleep(0.02)
        ws.close()  # signal end-of-stream
        await asyncio.sleep(0.05)
        # Stop the loop before reconnect noise interferes with assertions.
        await client.stop()
        # Even though the loop tore down, the prior snapshot remains.
        assert client.session("s1") is not None
    finally:
        if client._task is not None:
            await client.stop()


@pytest.mark.asyncio
async def test_fetch_limits_disabled_skips_limits_endpoint(
    patch_websockets: Any,
) -> None:
    patch_websockets()
    config = ClientConfig(
        host="h",
        port=1,
        fetch_limits=False,
        initial_backoff_s=0.01,
        backoff_cap_s=0.05,
        http_timeout_s=1.0,
    )
    client = AsyncAgentPulseClient(config)
    seen_paths: list[str] = []

    def handler(request: httpx.Request) -> httpx.Response:
        seen_paths.append(request.url.path)
        return httpx.Response(200, json=[])

    client._http = httpx.AsyncClient(transport=httpx.MockTransport(handler))
    try:
        await client.start()
        await asyncio.sleep(0.02)
        assert "/api/v2/log/api-limits" not in seen_paths
    finally:
        await client.stop()
