# Generated By: Claude Code (Claude Opus 4.7)
"""Tests for agentpulse.client.rest — uses httpx.MockTransport.

We mock at the transport layer to keep tests honest about HTTP shapes
without spinning up a real server.
"""

from __future__ import annotations

import json
from typing import Any

import httpx
import pytest

from agentpulse.client import rest


def _make_client(handler: Any) -> httpx.AsyncClient:
    return httpx.AsyncClient(transport=httpx.MockTransport(handler))


@pytest.mark.asyncio
async def test_post_statusline_returns_true_on_2xx() -> None:
    received: dict[str, Any] = {}

    def handler(request: httpx.Request) -> httpx.Response:
        received["url"] = str(request.url)
        received["body"] = json.loads(request.content)
        return httpx.Response(200, json={"ok": True})

    async with _make_client(handler) as http:
        ok = await rest.post_statusline(http, "h", 1, {"session_id": "s1"})
    assert ok is True
    assert received["url"] == "http://h:1/statusline/claude"
    assert received["body"] == {"session_id": "s1"}


@pytest.mark.asyncio
async def test_post_statusline_returns_false_on_500() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(500, text="boom")

    async with _make_client(handler) as http:
        ok = await rest.post_statusline(http, "h", 1, {})
    assert ok is False


@pytest.mark.asyncio
async def test_post_statusline_returns_false_on_transport_error() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        raise httpx.ConnectError("refused", request=request)

    async with _make_client(handler) as http:
        ok = await rest.post_statusline(http, "h", 1, {})
    assert ok is False


@pytest.mark.asyncio
async def test_post_hook_targets_hook_endpoint() -> None:
    seen: dict[str, Any] = {}

    def handler(request: httpx.Request) -> httpx.Response:
        seen["url"] = str(request.url)
        return httpx.Response(200)

    async with _make_client(handler) as http:
        await rest.post_hook(http, "h", 1, {"hook_event_name": "Stop"})
    assert seen["url"] == "http://h:1/hooks/claude"


@pytest.mark.asyncio
async def test_fetch_sessions_returns_list() -> None:
    body = [{"session_id": "a"}, {"session_id": "b"}]

    def handler(request: httpx.Request) -> httpx.Response:
        assert "since=12345" in str(request.url)
        return httpx.Response(200, json=body)

    async with _make_client(handler) as http:
        rows = await rest.fetch_sessions(http, "h", 1, since=12345.0)
    assert [r["session_id"] for r in rows] == ["a", "b"]


@pytest.mark.asyncio
async def test_fetch_sessions_returns_empty_on_failure() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(503)

    async with _make_client(handler) as http:
        rows = await rest.fetch_sessions(http, "h", 1, since=0.0)
    assert rows == []


@pytest.mark.asyncio
async def test_fetch_sessions_filters_non_dict_rows() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(200, json=[{"session_id": "a"}, "garbage", 42])

    async with _make_client(handler) as http:
        rows = await rest.fetch_sessions(http, "h", 1, since=0.0)
    assert rows == [{"session_id": "a"}]


@pytest.mark.asyncio
async def test_fetch_sessions_passes_active_and_process_id() -> None:
    captured: dict[str, str] = {}

    def handler(request: httpx.Request) -> httpx.Response:
        captured["query"] = request.url.query.decode("utf-8")
        return httpx.Response(200, json=[])

    async with _make_client(handler) as http:
        await rest.fetch_sessions(
            http, "h", 1, active=True, process_id="p1", since=10.0
        )
    assert "active=true" in captured["query"]
    assert "process_id=p1" in captured["query"]
    assert "since=10" in captured["query"]


@pytest.mark.asyncio
async def test_fetch_sessions_omits_unset_params() -> None:
    captured: dict[str, str] = {}

    def handler(request: httpx.Request) -> httpx.Response:
        captured["query"] = request.url.query.decode("utf-8")
        return httpx.Response(200, json=[])

    async with _make_client(handler) as http:
        await rest.fetch_sessions(http, "h", 1)
    assert captured["query"] == ""


@pytest.mark.asyncio
async def test_fetch_session_returns_none_on_404() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(404)

    async with _make_client(handler) as http:
        row = await rest.fetch_session(http, "h", 1, "missing")
    assert row is None


@pytest.mark.asyncio
async def test_fetch_session_returns_dict_on_200() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(200, json={"session_id": "s1"})

    async with _make_client(handler) as http:
        row = await rest.fetch_session(http, "h", 1, "s1")
    assert row == {"session_id": "s1"}


@pytest.mark.asyncio
async def test_fetch_statuslines_since_uses_desc_order_and_limit() -> None:
    captured: dict[str, str] = {}

    def handler(request: httpx.Request) -> httpx.Response:
        captured["query"] = str(request.url.query.decode("utf-8"))
        return httpx.Response(200, json=[])

    async with _make_client(handler) as http:
        await rest.fetch_statuslines_since(http, "h", 1, 0.0, limit=500)
    assert "order=desc" in captured["query"]
    assert "limit=500" in captured["query"]


@pytest.mark.asyncio
async def test_fetch_limits_latest_returns_first_row() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(
            200,
            json=[
                {"five_hour_utilization": 25.0},
                {"five_hour_utilization": 99.0},  # ignored — only first row
            ],
        )

    async with _make_client(handler) as http:
        row = await rest.fetch_limits_latest(http, "h", 1)
    assert row == {"five_hour_utilization": 25.0}


@pytest.mark.asyncio
async def test_fetch_limits_latest_returns_none_on_empty() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(200, json=[])

    async with _make_client(handler) as http:
        row = await rest.fetch_limits_latest(http, "h", 1)
    assert row is None
