# Generated By: Claude Code (Claude Opus 4.7)
"""Tests for agentpulse.client._state — frame application logic."""

from typing import Any

from agentpulse.client._state import ClientStore, _today_local
from agentpulse.client.types import ConnectionState


def _session_response(
    *,
    session_id: str = "s1",
    process_id: str = "p1",
    pid: int = 1234,
    source_system: str = "host",
    cwd: str = "/cwd",
    total_cost_usd: float = 1.0,
    cost_by_day: dict[str, float] | None = None,
    ended_at: float | None = None,
    last_activity_at: float = 100.0,
) -> dict[str, Any]:
    return {
        "session_id": session_id,
        "process_id": process_id,
        "pid": pid,
        "source_system": source_system,
        "cwd": cwd,
        "started_at": 50.0,
        "last_activity_at": last_activity_at,
        "ended_at": ended_at,
        "last_event": None,
        "last_tool": None,
        "last_event_at": None,
        "context_used_pct": None,
        "context_window_size": None,
        "model_id": None,
        "model_name": None,
        "agent_count": 0,
        "derived_state": None,
        "epoch_count": 0,
        "total_cost_usd": total_cost_usd,
        "cost_by_day": cost_by_day or {},
        "epochs": None,
        "agents": None,
    }


def _hook_frame(
    *,
    session_id: str = "s1",
    process_id: str = "p1",
    event_name: str = "PreToolUse",
    tool_name: str | None = "Bash",
    received_at: float = 200.0,
    derived_state: str | None = "working",
) -> dict[str, Any]:
    return {
        "type": "hook_logged",
        "platform": "claude",
        "timestamp": received_at,
        "process_id": process_id,
        "epoch_id": "e1",
        "pid": 1234,
        "source_system": "host",
        "cwd": "/cwd",
        "session_id": session_id,
        "agent_id": None,
        "event_name": event_name,
        "tool_name": tool_name,
        "received_at": received_at,
        "derived_state": derived_state,
        "log_id": 1,
    }


def _statusline_frame(
    *,
    session_id: str = "s1",
    process_id: str = "p1",
    session_total_cost_usd: float = 5.0,
    session_today_cost_usd: float = 2.0,
    total_input_tokens: int = 100,
    total_output_tokens: int = 200,
    lines_added: int = 10,
    lines_removed: int = 5,
    received_at: float = 300.0,
) -> dict[str, Any]:
    return {
        "type": "statusline_logged",
        "platform": "claude",
        "timestamp": received_at,
        "process_id": process_id,
        "epoch_id": "e1",
        "pid": 1234,
        "source_system": "host",
        "cwd": "/cwd",
        "session_id": session_id,
        "model_id": "claude-opus",
        "model_name": "Opus",
        "cost_usd": 1.5,
        "session_total_cost_usd": session_total_cost_usd,
        "session_today_cost_usd": session_today_cost_usd,
        "total_input_tokens": total_input_tokens,
        "total_output_tokens": total_output_tokens,
        "context_used_pct": 25.0,
        "context_window_size": 200000,
        "lines_added": lines_added,
        "lines_removed": lines_removed,
        "received_at": received_at,
        "log_id": 1,
    }


class TestReplaceSessions:
    def test_seeds_store_from_response_list(self) -> None:
        store = ClientStore()
        store.replace_sessions([_session_response()])
        sessions = store.sessions()
        assert len(sessions) == 1
        assert sessions[0].session_id == "s1"

    def test_fires_session_added_for_new_sessions(self) -> None:
        store = ClientStore()
        added: list[str] = []
        store.on_session_added(lambda s: added.append(s.session_id))
        store.replace_sessions(
            [_session_response(session_id="a"), _session_response(session_id="b")]
        )
        assert sorted(added) == ["a", "b"]

    def test_does_not_fire_added_for_existing_session(self) -> None:
        store = ClientStore()
        store.replace_sessions([_session_response()])
        added: list[str] = []
        store.on_session_added(lambda s: added.append(s.session_id))
        store.replace_sessions([_session_response()])
        assert added == []

    def test_preserves_token_and_line_counters(self) -> None:
        """SessionResponse lacks tokens/lines; refetch must not zero them."""
        store = ClientStore()
        store.replace_sessions([_session_response()])
        store.apply_statusline_logged(_statusline_frame())
        store.replace_sessions([_session_response(total_cost_usd=99.0)])
        session = store.session("s1")
        assert session is not None
        assert session.total_input_tokens == 100
        assert session.lines_added == 10
        assert session.total_cost_usd == 99.0  # bootstrap value wins for cost

    def test_fires_on_change(self) -> None:
        store = ClientStore()
        calls = []
        store.on_change(lambda: calls.append(1))
        store.replace_sessions([_session_response()])
        assert len(calls) == 1

    def test_skips_response_without_session_id(self) -> None:
        store = ClientStore()
        store.replace_sessions([_session_response(), {"process_id": "p2"}])
        assert len(store.sessions()) == 1


class TestApplyHookLogged:
    def test_unknown_session_returns_false(self) -> None:
        store = ClientStore()
        applied = store.apply_hook_logged(_hook_frame())
        assert applied is False

    def test_updates_known_session(self) -> None:
        store = ClientStore()
        store.replace_sessions([_session_response()])
        applied = store.apply_hook_logged(_hook_frame())
        assert applied is True
        s = store.session("s1")
        assert s is not None
        assert s.last_event == "PreToolUse"
        assert s.derived_state == "working"
        assert s.last_tool == "Bash"

    def test_session_end_marks_ended(self) -> None:
        store = ClientStore()
        store.replace_sessions([_session_response()])
        ended = []
        store.on_session_ended(lambda s: ended.append(s.session_id))
        store.apply_hook_logged(_hook_frame(event_name="SessionEnd", received_at=999.0))
        s = store.session("s1")
        assert s is not None
        assert s.ended_at == 999.0
        assert ended == ["s1"]

    def test_session_end_does_not_clobber_existing_ended_at(self) -> None:
        """A second SessionEnd must not overwrite the first."""
        store = ClientStore()
        store.replace_sessions([_session_response(ended_at=500.0)])
        ended: list[str] = []
        store.on_session_ended(lambda s: ended.append(s.session_id))
        store.apply_hook_logged(_hook_frame(event_name="SessionEnd", received_at=999.0))
        s = store.session("s1")
        assert s is not None
        assert s.ended_at == 500.0
        assert ended == []

    def test_last_activity_at_monotonically_increases(self) -> None:
        store = ClientStore()
        store.replace_sessions([_session_response(last_activity_at=500.0)])
        store.apply_hook_logged(_hook_frame(received_at=200.0))
        s = store.session("s1")
        assert s is not None
        assert s.last_activity_at == 500.0


class TestApplyStatuslineLogged:
    def test_creates_pending_session_when_unknown(self) -> None:
        store = ClientStore()
        added: list[str] = []
        store.on_session_added(lambda s: added.append(s.session_id))
        store.apply_statusline_logged(_statusline_frame())
        s = store.session("s1")
        assert s is not None
        assert s.total_input_tokens == 100
        assert added == ["s1"]

    def test_replaces_cost_does_not_accumulate(self) -> None:
        store = ClientStore()
        store.apply_statusline_logged(_statusline_frame(session_total_cost_usd=5.0))
        store.apply_statusline_logged(_statusline_frame(session_total_cost_usd=7.0))
        s = store.session("s1")
        assert s is not None
        assert s.total_cost_usd == 7.0  # not 12.0

    def test_today_cost_updates_cost_by_day(self) -> None:
        store = ClientStore()
        store.apply_statusline_logged(_statusline_frame(session_today_cost_usd=3.0))
        s = store.session("s1")
        assert s is not None
        today = _today_local()
        assert s.cost_by_day[today] == 3.0

    def test_replaces_tokens_does_not_accumulate(self) -> None:
        store = ClientStore()
        store.apply_statusline_logged(_statusline_frame(total_input_tokens=100))
        store.apply_statusline_logged(_statusline_frame(total_input_tokens=150))
        s = store.session("s1")
        assert s is not None
        assert s.total_input_tokens == 150


class TestApplyPidDeath:
    def test_marks_all_sessions_under_process_ended(self) -> None:
        store = ClientStore()
        store.replace_sessions(
            [
                _session_response(session_id="a", process_id="p1"),
                _session_response(session_id="b", process_id="p1"),
                _session_response(session_id="c", process_id="p2"),
            ]
        )
        store.apply_pid_death_logged(
            {"type": "pid_death_logged", "process_id": "p1", "observed_at": 999.0}
        )
        assert store.session("a").ended_at == 999.0  # type: ignore[union-attr]
        assert store.session("b").ended_at == 999.0  # type: ignore[union-attr]
        assert store.session("c").ended_at is None  # type: ignore[union-attr]

    def test_does_not_overwrite_existing_ended_at(self) -> None:
        store = ClientStore()
        store.replace_sessions([_session_response(session_id="a", ended_at=500.0)])
        store.apply_pid_death_logged(
            {"type": "pid_death_logged", "process_id": "p1", "observed_at": 999.0}
        )
        assert store.session("a").ended_at == 500.0  # type: ignore[union-attr]

    def test_fires_on_process_ended_once(self) -> None:
        store = ClientStore()
        store.replace_sessions(
            [
                _session_response(session_id="a", process_id="p1"),
                _session_response(session_id="b", process_id="p1"),
            ]
        )
        process_ids: list[str] = []
        store.on_process_ended(lambda pid: process_ids.append(pid))
        store.apply_pid_death_logged(
            {"type": "pid_death_logged", "process_id": "p1", "observed_at": 999.0}
        )
        assert process_ids == ["p1"]


class TestApiLimits:
    def test_apply_limits_logged_replaces_snapshot(self) -> None:
        store = ClientStore()
        changes: list[Any] = []
        store.on_limits_changed(lambda lim: changes.append(lim))
        store.apply_api_limits_logged(
            {
                "type": "api_limits_logged",
                "five_hour_utilization": 25.0,
                "five_hour_resets_at": 1.0e9,
                "seven_day_utilization": 80.0,
                "seven_day_resets_at": 2.0e9,
                "received_at": 5.0e8,
            }
        )
        limits = store.limits()
        assert limits is not None
        assert limits.five_hour_utilization == 25.0
        assert len(changes) == 1

    def test_replace_limits_with_none_clears(self) -> None:
        store = ClientStore()
        store.apply_api_limits_logged(
            {
                "type": "api_limits_logged",
                "five_hour_utilization": 25.0,
                "received_at": 1.0,
            }
        )
        store.replace_limits(None)
        assert store.limits() is None


class TestConnectionState:
    def test_initial_state_is_disconnected(self) -> None:
        store = ClientStore()
        assert store.connection_state() == ConnectionState.DISCONNECTED

    def test_set_state_fires_callback_only_on_change(self) -> None:
        store = ClientStore()
        states: list[ConnectionState] = []
        store.on_connection_state(lambda s: states.append(s))
        store.set_connection_state(ConnectionState.CONNECTING)
        store.set_connection_state(ConnectionState.CONNECTING)  # idempotent
        store.set_connection_state(ConnectionState.CONNECTED)
        assert states == [ConnectionState.CONNECTING, ConnectionState.CONNECTED]


class TestStatuslineLogSeed:
    def test_applies_only_first_row_per_session(self) -> None:
        store = ClientStore()
        store.replace_sessions([_session_response(session_id="s1")])
        store.apply_statusline_log_seed(
            [
                _statusline_frame(total_input_tokens=200, received_at=300.0),
                _statusline_frame(total_input_tokens=100, received_at=200.0),
            ]
        )
        s = store.session("s1")
        assert s is not None
        assert s.total_input_tokens == 200

    def test_skips_unknown_sessions(self) -> None:
        store = ClientStore()
        store.apply_statusline_log_seed([_statusline_frame()])
        # No session was created — the seed only fills existing entries.
        assert store.sessions() == ()
