# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Tests for /ws/v2 endpoint and v2 broadcast functions.

Slice A4. Verifies the websocket layer wires up the v2 dual-write path
without crossing into the v1 /ws stream.
"""

import json
from pathlib import Path
from unittest.mock import AsyncMock

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from agentpulse.api.v2.websocket import ConnectionManager, router as v2_ws_router
from agentpulse.db import close_db, init_db
from agentpulse.platforms.claude.hooks import router as hooks_router


@pytest.fixture
async def db(tmp_path: Path):
    conn = await init_db(db_path=tmp_path / "test.db")
    yield conn
    await close_db()


@pytest.fixture
def app(db) -> FastAPI:
    app = FastAPI()
    app.include_router(v2_ws_router)
    app.include_router(hooks_router)
    return app


@pytest.fixture
def client(app) -> TestClient:
    return TestClient(app)


class TestV2ConnectionManager:
    async def test_broadcast_sends_to_all(self) -> None:
        mgr = ConnectionManager()
        ws1 = AsyncMock()
        ws2 = AsyncMock()
        mgr._connections = [ws1, ws2]

        await mgr.broadcast({"type": "hook_logged"})

        ws1.send_text.assert_called_once()
        ws2.send_text.assert_called_once()
        payload = json.loads(ws1.send_text.call_args[0][0])
        assert payload["type"] == "hook_logged"

    async def test_broadcast_drops_dead_connection(self) -> None:
        mgr = ConnectionManager()
        ws_alive = AsyncMock()
        ws_dead = AsyncMock()
        ws_dead.send_text.side_effect = RuntimeError("disconnected")
        mgr._connections = [ws_alive, ws_dead]

        await mgr.broadcast({"type": "hook_logged"})

        assert mgr.connection_count == 1
        assert ws_alive in mgr._connections


class TestV2WebSocketEndpoint:
    def test_connects(self, client) -> None:
        with client.websocket_connect("/ws/v2"):
            pass  # Just confirm the handshake completes


class TestHookLoggedBroadcast:
    def test_hook_post_emits_hook_logged(self, client) -> None:
        with client.websocket_connect("/ws/v2") as ws:
            client.post(
                "/hooks/claude",
                json={
                    "session_id": "s1",
                    "hook_event_name": "PreToolUse",
                    "tool_name": "Bash",
                    "pid": 4242,
                    "source_system": "host.example",
                    "cwd": "/proj",
                    "permission_mode": "acceptEdits",
                },
            )
            frame = ws.receive_json()
            assert frame["type"] == "hook_logged"
            assert frame["platform"] == "claude"
            assert frame["session_id"] == "s1"
            assert frame["pid"] == 4242
            assert frame["source_system"] == "host.example"
            assert frame["cwd"] == "/proj"
            assert frame["event_name"] == "PreToolUse"
            assert frame["tool_name"] == "Bash"
            assert frame["permission_mode"] == "acceptEdits"
            assert frame["agent_id"] is None
            # Derived ids present
            assert (
                isinstance(frame["process_id"], str) and len(frame["process_id"]) == 16
            )
            assert isinstance(frame["epoch_id"], str) and len(frame["epoch_id"]) == 16
            # log_id present (autoincrement, first row → 1)
            assert frame["log_id"] == 1
            # raw_payload not on the wire
            assert "raw_payload" not in frame

    def test_pidless_hook_does_not_broadcast(self, client) -> None:
        """No pid → v2 inserter skips → no broadcast."""
        with client.websocket_connect("/ws/v2") as ws:
            client.post(
                "/hooks/claude",
                json={
                    "session_id": "s-no-pid",
                    "hook_event_name": "PreToolUse",
                    "tool_name": "Bash",
                },
            )
            # Send a follow-up hook with a pid so we have something to receive
            # — if the first one had broadcast, we'd see two frames
            client.post(
                "/hooks/claude",
                json={
                    "session_id": "s-with-pid",
                    "hook_event_name": "Stop",
                    "pid": 9999,
                    "source_system": "host",
                    "cwd": "/proj",
                },
            )
            frame = ws.receive_json()
            assert frame["session_id"] == "s-with-pid"
            assert frame["log_id"] == 1  # still the first v2 row


class TestStatuslineLoggedBroadcast:
    def test_statusline_post_emits_statusline_logged(self, client) -> None:
        payload = {
            "session_id": "s1",
            "pid": 4242,
            "source_system": "host.example",
            "cwd": "/proj",
            "version": "2.1.117",
            "model": {
                "id": "claude-opus-4-7[1m]",
                "display_name": "Opus 4.7 (1M context)",
            },
            "workspace": {"project_dir": "/proj"},
            "cost": {
                "total_cost_usd": 1.25,
                "total_duration_ms": 60000,
                "total_api_duration_ms": 12000,
                "total_lines_added": 10,
                "total_lines_removed": 2,
            },
            "context_window": {
                "total_input_tokens": 1000,
                "total_output_tokens": 500,
                "context_window_size": 1000000,
                "used_percentage": 25.0,
                "current_usage": {
                    "cache_read_input_tokens": 800,
                    "cache_creation_input_tokens": 300,
                },
            },
            "exceeds_200k_tokens": False,
        }
        with client.websocket_connect("/ws/v2") as ws:
            client.post("/statusline/claude", json=payload)
            frame = ws.receive_json()
            assert frame["type"] == "statusline_logged"
            assert frame["platform"] == "claude"
            assert frame["session_id"] == "s1"
            assert frame["pid"] == 4242
            assert frame["model_id"] == "claude-opus-4-7[1m]"
            assert frame["model_name"] == "Opus 4.7 (1M context)"
            assert frame["claude_version"] == "2.1.117"
            assert frame["cost_usd"] == 1.25
            assert frame["session_total_cost_usd"] == pytest.approx(1.25)
            assert frame["session_today_cost_usd"] == pytest.approx(1.25)
            assert frame["duration_seconds"] == 60.0
            assert frame["api_duration_seconds"] == 12.0
            assert frame["cache_read_tokens"] == 800
            assert (
                isinstance(frame["process_id"], str) and len(frame["process_id"]) == 16
            )
            assert isinstance(frame["epoch_id"], str) and len(frame["epoch_id"]) == 16
            assert frame["log_id"] == 1
            assert "raw_payload" not in frame

    def test_session_total_cost_usd_cumulative_across_processes(self, client) -> None:
        """The broadcast carries the derived session-wide total. cost_usd
        is session-cumulative — pid=20 inherits the $2 from pid=10 and
        adds new work, reporting the full session total.
        """
        first = {
            "session_id": "s1",
            "pid": 10,
            "source_system": "host",
            "cwd": "/proj",
            "cost": {"total_cost_usd": 2.0},
        }
        # pid=20 resumes: inherits $2, adds $1.5 → cumulative $3.5
        second = {
            "session_id": "s1",
            "pid": 20,
            "source_system": "host",
            "cwd": "/proj",
            "cost": {"total_cost_usd": 3.5},
        }
        with client.websocket_connect("/ws/v2") as ws:
            client.post("/statusline/claude", json=first)
            frame1 = ws.receive_json()
            assert frame1["cost_usd"] == 2.0
            assert frame1["session_total_cost_usd"] == pytest.approx(2.0)

            client.post("/statusline/claude", json=second)
            frame2 = ws.receive_json()
            assert frame2["cost_usd"] == 3.5
            assert frame2["session_total_cost_usd"] == pytest.approx(3.5)

    def test_session_today_cost_usd_tracks_today_bucket(self, client) -> None:
        """`session_today_cost_usd` is the today delta of the session's
        cumulative cost. pid=20 inherits $2, adds $1.5 → today = $3.5.
        """
        first = {
            "session_id": "s1",
            "pid": 10,
            "source_system": "host",
            "cwd": "/proj",
            "cost": {"total_cost_usd": 2.0},
        }
        # pid=20 resumes: cumulative $3.5
        second = {
            "session_id": "s1",
            "pid": 20,
            "source_system": "host",
            "cwd": "/proj",
            "cost": {"total_cost_usd": 3.5},
        }
        with client.websocket_connect("/ws/v2") as ws:
            client.post("/statusline/claude", json=first)
            frame1 = ws.receive_json()
            assert frame1["session_today_cost_usd"] == pytest.approx(2.0)

            client.post("/statusline/claude", json=second)
            frame2 = ws.receive_json()
            assert frame2["session_today_cost_usd"] == pytest.approx(3.5)

    def test_pidless_statusline_does_not_broadcast(self, client) -> None:
        no_pid = {
            "session_id": "s1",
            "model": {"display_name": "Opus"},
        }
        with client.websocket_connect("/ws/v2") as ws:
            client.post("/statusline/claude", json=no_pid)
            # Send a real one so we have something to receive
            with_pid = {
                "session_id": "s2",
                "pid": 5555,
                "source_system": "host",
                "cwd": "/proj",
                "model": {"display_name": "Opus"},
            }
            client.post("/statusline/claude", json=with_pid)
            frame = ws.receive_json()
            assert frame["session_id"] == "s2"
            assert frame["log_id"] == 1
