# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for session-level cost aggregation across multiple processes.

Claude Code's cost_usd is session-cumulative — it carries forward across
``--resume`` (new PID inherits the running total). The session view
exposes total + daily spend derived from global MAX and day deltas.
"""

from pathlib import Path

import pytest

from agentpulse.api.v2 import queries
from agentpulse.db import close_db, init_db
from agentpulse.platforms.claude import schema


@pytest.fixture
async def db(tmp_path: Path):
    conn = await init_db(db_path=tmp_path / "test.db")
    yield conn
    await close_db()


async def _seed_hook(
    db,
    *,
    session_id: str,
    pid: int,
    received_at: float,
    cwd: str = "/proj",
    source_system: str = "host",
) -> None:
    payload = {
        "session_id": session_id,
        "hook_event_name": "PreToolUse",
        "pid": pid,
        "source_system": source_system,
        "cwd": cwd,
    }
    await schema.insert_log_hook(
        db, payload=payload, received_at=received_at, received_by="test"
    )
    await db.commit()


async def _seed_statusline(
    db,
    *,
    session_id: str,
    pid: int,
    received_at: float,
    cost_usd: float,
    cwd: str = "/proj",
    source_system: str = "host",
) -> None:
    payload = {
        "session_id": session_id,
        "pid": pid,
        "source_system": source_system,
        "cwd": cwd,
        "cost": {"total_cost_usd": cost_usd},
    }
    await schema.insert_log_statusline(
        db, payload=payload, received_at=received_at, received_by="test"
    )
    await db.commit()


async def _seed_death(
    db,
    *,
    pid: int,
    observed_at: float,
    cwd: str = "/proj",
    source_system: str = "host",
) -> None:
    await schema.insert_log_pid_death(
        db,
        pid=pid,
        source_system=source_system,
        cwd=cwd,
        observed_at=observed_at,
        observed_by="pid-watcher",
    )
    await db.commit()


# 2026-04-21 22:27:43 UTC == 1777152463 — picking timestamps that fall on
# distinct local dates to keep the day buckets predictable across timezones.
DAY1_START = 1777152463.0  # day "D1" in server-local time
DAY2_START = DAY1_START + 86400.0  # day after


class TestSessionTotalCost:
    async def test_single_process_session(self, db) -> None:
        await _seed_hook(db, session_id="s1", pid=10, received_at=DAY1_START)
        await _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY1_START + 60, cost_usd=2.5
        )
        sess = await queries.get_session_by_id(db, session_id="s1")
        assert sess is not None
        assert sess["total_cost_usd"] == 2.5

    async def test_multi_process_session_cumulative_cost(self, db) -> None:
        # Three SDK invocations on the same session. cost_usd is
        # session-cumulative: each new process carries forward the prior
        # total. The session total is the global MAX.
        for pid, cost in [(10, 5.0), (20, 12.5), (30, 13.75)]:
            await _seed_hook(db, session_id="s1", pid=pid, received_at=DAY1_START + pid)
            await _seed_statusline(
                db,
                session_id="s1",
                pid=pid,
                received_at=DAY1_START + pid + 1,
                cost_usd=cost,
            )
        sess = await queries.get_session_by_id(db, session_id="s1")
        assert sess["total_cost_usd"] == 13.75

    async def test_per_process_max_used_not_sum(self, db) -> None:
        """Cost is monotonic within a process — only the LAST (max) reading
        counts per process. Multiple statuslines from one process don't
        double-count."""
        await _seed_hook(db, session_id="s1", pid=10, received_at=DAY1_START)
        # Three readings from the same process — only the max matters
        for ts_offset, cost in [(60, 1.0), (120, 3.0), (180, 5.0)]:
            await _seed_statusline(
                db,
                session_id="s1",
                pid=10,
                received_at=DAY1_START + ts_offset,
                cost_usd=cost,
            )
        sess = await queries.get_session_by_id(db, session_id="s1")
        assert sess["total_cost_usd"] == 5.0  # max(cost), not sum

    async def test_no_cost_yields_zero(self, db) -> None:
        await _seed_hook(db, session_id="s1", pid=10, received_at=DAY1_START)
        # No statuslines at all
        sess = await queries.get_session_by_id(db, session_id="s1")
        assert sess["total_cost_usd"] == 0.0
        assert sess["cost_by_day"] == {}


class TestSessionCostByDay:
    async def test_single_process_one_day(self, db) -> None:
        await _seed_hook(db, session_id="s1", pid=10, received_at=DAY1_START)
        await _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY1_START + 60, cost_usd=4.0
        )
        sess = await queries.get_session_by_id(db, session_id="s1")
        # Single day → that day has the full cost
        assert sum(sess["cost_by_day"].values()) == pytest.approx(4.0)
        assert len(sess["cost_by_day"]) == 1

    async def test_single_process_two_days(self, db) -> None:
        # Day 1: cost reaches 3.0. Day 2: same process continues, reaches 5.0.
        # Daily deltas: D1=3.0, D2=2.0. Sum=5.0 = the process's MAX.
        await _seed_hook(db, session_id="s1", pid=10, received_at=DAY1_START)
        await _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY1_START + 60, cost_usd=3.0
        )
        await _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY2_START + 60, cost_usd=5.0
        )
        sess = await queries.get_session_by_id(db, session_id="s1")
        cost_by_day = sess["cost_by_day"]
        assert len(cost_by_day) == 2
        days = sorted(cost_by_day.keys())
        assert cost_by_day[days[0]] == pytest.approx(3.0)
        assert cost_by_day[days[1]] == pytest.approx(2.0)

    async def test_multi_process_same_day_cumulative(self, db) -> None:
        # Two processes on the same day. cost_usd is session-cumulative:
        # pid=20 inherits $2 from pid=10, adds $3 of new work → $5.
        await _seed_hook(db, session_id="s1", pid=10, received_at=DAY1_START)
        await _seed_hook(db, session_id="s1", pid=20, received_at=DAY1_START + 5)
        await _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY1_START + 60, cost_usd=2.0
        )
        await _seed_statusline(
            db, session_id="s1", pid=20, received_at=DAY1_START + 120, cost_usd=5.0
        )
        sess = await queries.get_session_by_id(db, session_id="s1")
        assert len(sess["cost_by_day"]) == 1
        (day_total,) = sess["cost_by_day"].values()
        assert day_total == pytest.approx(5.0)

    async def test_multi_process_multi_day(self, db) -> None:
        # Process A: day1 costs $2. Process B resumes on day2, inherits $2,
        # adds $3 of new work → cumulative $5. Day1=$2, Day2=$3. Total=$5.
        await _seed_hook(db, session_id="s1", pid=10, received_at=DAY1_START)
        await _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY1_START + 60, cost_usd=2.0
        )
        await _seed_hook(db, session_id="s1", pid=20, received_at=DAY2_START)
        await _seed_statusline(
            db, session_id="s1", pid=20, received_at=DAY2_START + 60, cost_usd=5.0
        )
        sess = await queries.get_session_by_id(db, session_id="s1")
        days = sorted(sess["cost_by_day"].keys())
        assert len(days) == 2
        assert sess["cost_by_day"][days[0]] == pytest.approx(2.0)
        assert sess["cost_by_day"][days[1]] == pytest.approx(3.0)
        assert sess["total_cost_usd"] == pytest.approx(5.0)

    async def test_sequential_processes_cumulative(self, db) -> None:
        """Second process inherits session cost from the first.
        P10 reaches $4, P20 inherits and adds $1.5 → cumulative $5.5.
        """
        await _seed_hook(db, session_id="s1", pid=10, received_at=DAY1_START)
        await _seed_hook(db, session_id="s1", pid=20, received_at=DAY1_START + 30)
        await _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY1_START + 100, cost_usd=4.0
        )
        await _seed_statusline(
            db, session_id="s1", pid=20, received_at=DAY1_START + 110, cost_usd=5.5
        )
        sess = await queries.get_session_by_id(db, session_id="s1")
        (day_total,) = sess["cost_by_day"].values()
        assert day_total == pytest.approx(5.5)
        assert sess["total_cost_usd"] == pytest.approx(5.5)


class TestPidReuseAggregation:
    """When a pid is reused within the same session (rare — OS reassigns
    the same pid to a new Claude Code process after the prior one died,
    and the user resumes that session into the new process), cost_usd is
    session-cumulative. The second instance's statuslines carry forward
    the total from the first.
    """

    async def test_total_cost_with_reused_pid(self, db) -> None:
        # Instance 1: pid=10 reaches $7, dies on day 1
        await _seed_hook(db, session_id="s1", pid=10, received_at=DAY1_START)
        await _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY1_START + 60, cost_usd=7.0
        )
        await _seed_death(db, pid=10, observed_at=DAY1_START + 100)
        # Instance 2: same pid reused, session cost grows from $7 to $11
        await _seed_hook(db, session_id="s1", pid=10, received_at=DAY2_START)
        await _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY2_START + 60, cost_usd=11.0
        )

        sess = await queries.get_session_by_id(db, session_id="s1")
        assert sess["total_cost_usd"] == pytest.approx(11.0)

    async def test_cost_by_day_with_reused_pid(self, db) -> None:
        # Same scenario — daily deltas: D1=$7, D2=$11-$7=$4
        await _seed_hook(db, session_id="s1", pid=10, received_at=DAY1_START)
        await _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY1_START + 60, cost_usd=7.0
        )
        await _seed_death(db, pid=10, observed_at=DAY1_START + 100)
        await _seed_hook(db, session_id="s1", pid=10, received_at=DAY2_START)
        await _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY2_START + 60, cost_usd=11.0
        )

        sess = await queries.get_session_by_id(db, session_id="s1")
        days = sorted(sess["cost_by_day"].keys())
        assert len(days) == 2
        assert sess["cost_by_day"][days[0]] == pytest.approx(7.0)
        assert sess["cost_by_day"][days[1]] == pytest.approx(4.0)


class TestResumedSessionCost:
    """Reproduces the double-counting bug: a session resumed days later
    should attribute only the delta to today, not the full cumulative.
    """

    async def test_resumed_session_total_cost(self, db) -> None:
        # Day 1: pid=100 works up to $17.24
        await _seed_hook(db, session_id="s1", pid=100, received_at=DAY1_START)
        await _seed_statusline(
            db, session_id="s1", pid=100, received_at=DAY1_START + 60, cost_usd=17.24
        )
        # Day 2: pid=200 resumes, inherits $17.24, says "hi" → $20.12
        await _seed_hook(db, session_id="s1", pid=200, received_at=DAY2_START)
        await _seed_statusline(
            db,
            session_id="s1",
            pid=200,
            received_at=DAY2_START + 10,
            cost_usd=18.83,
        )
        await _seed_statusline(
            db,
            session_id="s1",
            pid=200,
            received_at=DAY2_START + 60,
            cost_usd=20.12,
        )

        sess = await queries.get_session_by_id(db, session_id="s1")
        # Total is the global MAX, not SUM of per-instance MAXes
        assert sess["total_cost_usd"] == pytest.approx(20.12)
        days = sorted(sess["cost_by_day"].keys())
        assert len(days) == 2
        assert sess["cost_by_day"][days[0]] == pytest.approx(17.24)
        assert sess["cost_by_day"][days[1]] == pytest.approx(2.88)


class TestSessionEndpointExposesCost:
    """The values flow through SessionResponse to the /api/v2/sessions endpoint."""

    async def test_response_dict_carries_total_and_breakdown(self, db) -> None:
        await _seed_hook(db, session_id="s1", pid=10, received_at=DAY1_START)
        await _seed_statusline(
            db, session_id="s1", pid=10, received_at=DAY1_START + 60, cost_usd=7.0
        )
        sess = await queries.get_session_by_id(db, session_id="s1")
        assert "total_cost_usd" in sess
        assert "cost_by_day" in sess
        assert sess["total_cost_usd"] == 7.0
