# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Tests for /api/v2 endpoints — processes, sessions, log streams."""

from pathlib import Path

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from agentpulse.api.v2 import router as v2_router
from agentpulse.db import close_db, init_db
from agentpulse.platforms.claude import schema
from tests.conftest import run_async


@pytest.fixture
async def db(tmp_path: Path):
    conn = await init_db(db_path=tmp_path / "test.db")
    yield conn
    await close_db()


@pytest.fixture
def client(db) -> TestClient:
    app = FastAPI()
    app.include_router(v2_router)
    return TestClient(app)


def _seed_hook(
    db,
    *,
    session_id: str,
    pid: int,
    received_at: float,
    event_name: str = "PreToolUse",
    tool_name: str | None = "Bash",
    agent_id: str | None = None,
    source_system: str = "host",
    cwd: str = "/proj",
    entrypoint: str = "vscode",
) -> None:
    payload = {
        "session_id": session_id,
        "hook_event_name": event_name,
        "tool_name": tool_name or "",
        "agent_id": agent_id or "",
        "pid": pid,
        "source_system": source_system,
        "cwd": cwd,
        "permission_mode": "acceptEdits",
        "claude_version": "2.1.117",
    }
    run_async(
        schema.insert_log_hook(
            db,
            payload=payload,
            received_at=received_at,
            received_by="test",
            entrypoint=entrypoint,
        )
    )
    run_async(db.commit())


def _seed_statusline(
    db,
    *,
    session_id: str,
    pid: int,
    received_at: float,
    cost_usd: float = 1.0,
    source_system: str = "host",
    cwd: str = "/proj",
) -> None:
    payload = {
        "session_id": session_id,
        "pid": pid,
        "source_system": source_system,
        "cwd": cwd,
        "version": "2.1.117",
        "workspace": {"project_dir": cwd},
        "model": {"id": "claude-opus-4-7[1m]", "display_name": "Opus 4.7 (1M context)"},
        "cost": {
            "total_cost_usd": cost_usd,
            "total_duration_ms": 60000,
            "total_api_duration_ms": 12000,
            "total_lines_added": 10,
            "total_lines_removed": 2,
        },
        "context_window": {
            "total_input_tokens": 1000,
            "total_output_tokens": 500,
            "context_window_size": 1000000,
            "used_percentage": 25.0,
            "current_usage": {
                "cache_read_input_tokens": 800,
                "cache_creation_input_tokens": 300,
            },
        },
        "exceeds_200k_tokens": False,
    }
    run_async(
        schema.insert_log_statusline(
            db,
            payload=payload,
            received_at=received_at,
            received_by="test",
        )
    )
    run_async(db.commit())


class TestListProcesses:
    def test_empty(self, client) -> None:
        resp = client.get("/api/v2/processes")
        assert resp.status_code == 200
        assert resp.json() == []

    def test_lists_processes(self, client, db) -> None:
        _seed_hook(db, session_id="s1", pid=10, received_at=100.0)
        _seed_statusline(db, session_id="s1", pid=10, cost_usd=2.5, received_at=110.0)
        _seed_hook(db, session_id="s2", pid=20, received_at=200.0)

        resp = client.get("/api/v2/processes")
        assert resp.status_code == 200
        body = resp.json()
        assert len(body) == 2
        # Sorted DESC by last_activity_at — pid=20 first
        assert body[0]["pid"] == 20
        assert body[1]["pid"] == 10
        # No sessions[] on list response
        assert body[0].get("sessions") is None

    def test_filter_source_system(self, client, db) -> None:
        _seed_hook(db, session_id="s1", pid=10, source_system="a", received_at=100.0)
        _seed_hook(db, session_id="s2", pid=20, source_system="b", received_at=110.0)

        resp = client.get("/api/v2/processes?source_system=b")
        body = resp.json()
        assert len(body) == 1
        assert body[0]["source_system"] == "b"

    def test_filter_cwd(self, client, db) -> None:
        _seed_hook(db, session_id="s1", pid=10, cwd="/a", received_at=100.0)
        _seed_hook(db, session_id="s2", pid=20, cwd="/b", received_at=110.0)

        resp = client.get("/api/v2/processes?cwd=/b")
        body = resp.json()
        assert len(body) == 1
        assert body[0]["cwd"] == "/b"

    def test_filter_since(self, client, db) -> None:
        _seed_hook(db, session_id="s1", pid=10, received_at=100.0)
        _seed_hook(db, session_id="s2", pid=20, received_at=200.0)

        resp = client.get("/api/v2/processes?since=150")
        body = resp.json()
        assert len(body) == 1
        assert body[0]["pid"] == 20


class TestProcessDetail:
    def test_returns_with_sessions_nested(self, client, db) -> None:
        _seed_hook(db, session_id="sa", pid=10, received_at=100.0)
        _seed_hook(db, session_id="sb", pid=10, received_at=200.0)

        resp = client.get("/api/v2/processes")
        process_id = resp.json()[0]["process_id"]

        detail = client.get(f"/api/v2/processes/{process_id}")
        assert detail.status_code == 200
        body = detail.json()
        assert body["process_id"] == process_id
        assert len(body["sessions"]) == 2

    def test_unknown_process_id_404(self, client) -> None:
        resp = client.get("/api/v2/processes/0000000000000000")
        assert resp.status_code == 404


class TestListSessions:
    def test_empty(self, client) -> None:
        resp = client.get("/api/v2/sessions")
        assert resp.status_code == 200
        assert resp.json() == []

    def test_lists_sessions(self, client, db) -> None:
        _seed_hook(db, session_id="sa", pid=10, received_at=100.0)
        _seed_hook(db, session_id="sb", pid=20, received_at=200.0)

        resp = client.get("/api/v2/sessions")
        body = resp.json()
        assert len(body) == 2
        assert body[0]["session_id"] == "sb"  # latest first

    def test_active_filter_excludes_ended(self, client, db) -> None:
        _seed_hook(db, session_id="sa", pid=10, received_at=100.0)
        _seed_hook(
            db, session_id="sb", pid=20, event_name="SessionEnd", received_at=200.0
        )

        resp = client.get("/api/v2/sessions?active=true")
        body = resp.json()
        assert len(body) == 1
        assert body[0]["session_id"] == "sa"

    def test_filter_by_process_id(self, client, db) -> None:
        _seed_hook(db, session_id="sa", pid=10, received_at=100.0)
        _seed_hook(db, session_id="sb", pid=20, received_at=110.0)

        procs = client.get("/api/v2/processes").json()
        target_pid = procs[0]["process_id"]

        resp = client.get(f"/api/v2/sessions?process_id={target_pid}")
        body = resp.json()
        assert len(body) == 1


class TestSessionDetail:
    def test_returns_with_epochs_and_agents(self, client, db) -> None:
        _seed_hook(
            db,
            session_id="sa",
            pid=10,
            event_name="SubagentStart",
            agent_id="agent-1",
            received_at=100.0,
        )
        _seed_hook(db, session_id="sa", pid=10, received_at=200.0)

        resp = client.get("/api/v2/sessions/sa")
        assert resp.status_code == 200
        body = resp.json()
        assert body["session_id"] == "sa"
        assert len(body["epochs"]) == 1
        assert len(body["agents"]) == 1
        assert body["agents"][0]["agent_id"] == "agent-1"

    def test_unknown_404(self, client) -> None:
        resp = client.get("/api/v2/sessions/nope")
        assert resp.status_code == 404


class TestLogHooksEndpoint:
    def test_returns_rows_with_derived_ids(self, client, db) -> None:
        _seed_hook(db, session_id="s1", pid=10, received_at=100.0)
        _seed_hook(db, session_id="s1", pid=10, received_at=200.0)

        resp = client.get("/api/v2/log/hooks")
        assert resp.status_code == 200
        body = resp.json()
        assert len(body) == 2
        # Both rows in the same process → same process_id
        assert body[0]["process_id"] == body[1]["process_id"]
        assert body[0]["epoch_id"] == body[1]["epoch_id"]
        # raw_payload included by default
        assert body[0]["raw_payload"] is not None

    def test_filter_session_id(self, client, db) -> None:
        _seed_hook(db, session_id="s1", pid=10, received_at=100.0)
        _seed_hook(db, session_id="s2", pid=20, received_at=110.0)
        resp = client.get("/api/v2/log/hooks?session_id=s2")
        body = resp.json()
        assert len(body) == 1
        assert body[0]["session_id"] == "s2"

    def test_pagination(self, client, db) -> None:
        for t in (100.0, 110.0, 120.0):
            _seed_hook(db, session_id="s1", pid=10, received_at=t)
        resp = client.get("/api/v2/log/hooks?limit=1&offset=1")
        body = resp.json()
        assert len(body) == 1
        assert body[0]["received_at"] == 110.0

    def test_invalid_limit_returns_422(self, client) -> None:
        resp = client.get("/api/v2/log/hooks?limit=2000")
        assert resp.status_code == 422


class TestLogStatuslinesEndpoint:
    def test_returns_rows_with_derived_ids(self, client, db) -> None:
        _seed_statusline(db, session_id="s1", pid=10, cost_usd=1.0, received_at=100.0)
        _seed_statusline(db, session_id="s1", pid=10, cost_usd=2.0, received_at=200.0)

        resp = client.get("/api/v2/log/statuslines")
        body = resp.json()
        assert len(body) == 2
        assert body[0]["process_id"] == body[1]["process_id"]
        assert body[0]["model_id"] == "claude-opus-4-7[1m]"

    def test_filter_session_id(self, client, db) -> None:
        _seed_statusline(db, session_id="s1", pid=10, received_at=100.0)
        _seed_statusline(db, session_id="s2", pid=20, received_at=110.0)
        resp = client.get("/api/v2/log/statuslines?session_id=s1")
        body = resp.json()
        assert len(body) == 1


class TestLogPidDeathsEndpoint:
    def _seed_death(
        self, db, *, pid: int, source_system: str, cwd: str, observed_at: float
    ) -> None:
        run_async(
            schema.insert_log_pid_death(
                db,
                pid=pid,
                source_system=source_system,
                cwd=cwd,
                observed_at=observed_at,
                observed_by="pid-watcher",
            )
        )
        run_async(db.commit())

    def test_returns_rows_with_derived_process_id(self, client, db) -> None:
        # Need a hook for the IdEnricher's earliest-received_at lookup
        _seed_hook(db, session_id="s1", pid=10, received_at=100.0)
        self._seed_death(
            db, pid=10, source_system="host", cwd="/proj", observed_at=500.0
        )
        resp = client.get("/api/v2/log/pid-deaths")
        assert resp.status_code == 200
        body = resp.json()
        assert len(body) == 1
        row = body[0]
        assert row["pid"] == 10
        assert row["source_system"] == "host"
        assert row["cwd"] == "/proj"
        assert row["observed_at"] == 500.0
        assert row["observed_by"] == "pid-watcher"
        assert isinstance(row["process_id"], str) and len(row["process_id"]) == 16

    def test_filter_by_pid(self, client, db) -> None:
        _seed_hook(db, session_id="s1", pid=10, received_at=100.0)
        _seed_hook(db, session_id="s2", pid=20, received_at=110.0)
        self._seed_death(
            db, pid=10, source_system="host", cwd="/proj", observed_at=500.0
        )
        self._seed_death(
            db, pid=20, source_system="host", cwd="/proj", observed_at=600.0
        )
        resp = client.get("/api/v2/log/pid-deaths?pid=20")
        body = resp.json()
        assert len(body) == 1
        assert body[0]["pid"] == 20

    def test_observed_at_range_filter(self, client, db) -> None:
        _seed_hook(db, session_id="s1", pid=10, received_at=100.0)
        for ts in (100.0, 200.0, 300.0):
            self._seed_death(
                db, pid=10, source_system="host", cwd="/proj", observed_at=ts
            )
        resp = client.get("/api/v2/log/pid-deaths?since=150&until=250")
        body = resp.json()
        assert len(body) == 1
        assert body[0]["observed_at"] == 200.0
