#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Relay Claude Code hook events to the AgentPulse service.

Used as a Claude Code command hook. Reads JSON from stdin,
POSTs it to AgentPulse's HTTP endpoint.
Non-blocking — if the service is down, exits silently.

Requires --config pointing to the same config.json the service uses.

Uses psutil (if available) to find the Claude Code PID via process
ancestry. Falls back to os.getppid() if psutil is not installed.
"""

import json
import logging
import logging.handlers
import os
import platform
import sys
import urllib.request
from pathlib import Path

_LOG_DIR = Path.home() / ".claude" / "agentpulse" / "logs"
_LOG_FILE = _LOG_DIR / "hook-payloads.jsonl"

logger = logging.getLogger(__name__)


def _load_config(config_path: Path) -> dict:
    """Load config from JSON file."""
    try:
        data = json.loads(config_path.read_text(encoding="utf-8"))
        if isinstance(data, dict):
            return data
    except (json.JSONDecodeError, OSError) as exc:
        print(f"hook_relay: failed to read config {config_path}: {exc}", file=sys.stderr)
    return {}


def _get_url(config: dict) -> str:
    """Build the AgentPulse POST URL from config."""
    host = config.get("host", "127.0.0.1")
    port = config.get("port", 17385)
    return f"http://{host}:{port}/hooks/claude"


def _configure_logging(*, debug: bool) -> None:
    """Set up logging. In debug mode, also log raw payloads to a JSONL file."""
    logging.basicConfig(
        level=logging.WARNING, format="%(message)s", stream=sys.stderr
    )
    if debug:
        logger.setLevel(logging.DEBUG)
        try:
            _LOG_DIR.mkdir(parents=True, exist_ok=True)
            handler = logging.handlers.RotatingFileHandler(
                _LOG_FILE,
                maxBytes=2 * 1024 * 1024,
                backupCount=1,
                encoding="utf-8",
            )
            handler.setLevel(logging.DEBUG)
            handler.setFormatter(logging.Formatter("%(message)s"))
            logger.addHandler(handler)
        except OSError:
            pass


def _now_iso() -> str:
    from datetime import datetime, timezone

    return datetime.now(timezone.utc).isoformat()


def _parse_config_path() -> Path | None:
    """Parse --config from sys.argv."""
    for i, arg in enumerate(sys.argv[1:], 1):
        if arg == "--config" and i + 1 < len(sys.argv):
            return Path(sys.argv[i + 1])
    return None


def main() -> None:
    config_path = _parse_config_path()

    if config_path is None:
        print("hook_relay: --config is required", file=sys.stderr)
        sys.exit(1)

    config = _load_config(config_path)
    url = _get_url(config)
    log_level = str(config.get("log_level", "INFO")).upper()
    debug = log_level == "DEBUG"

    # --marker flag: inject a labeled boundary line and exit
    if len(sys.argv) >= 2 and sys.argv[1] == "--marker":
        _configure_logging(debug=True)
        marker_text = " ".join(sys.argv[2:]) if len(sys.argv) >= 3 else ""
        logger.debug(json.dumps({"_marker": marker_text, "_ts": _now_iso()}))
        return

    _configure_logging(debug=debug)

    try:
        data = sys.stdin.read()
        if not data:
            return

        # Inject source_system into the payload so agentpulse knows
        # which machine this event came from.
        try:
            payload = json.loads(data)
            payload["source_system"] = platform.node()

            # Walk the process ancestry to find the Claude Code PID.
            try:
                import psutil

                claude_pid = 0
                for proc in psutil.Process(os.getpid()).parents():
                    try:
                        if "claude" in proc.name().lower():
                            claude_pid = proc.pid
                            break
                    except (psutil.NoSuchProcess, psutil.AccessDenied):
                        break
                payload["pid"] = claude_pid or os.getppid()
            except ImportError:
                payload["pid"] = os.getppid()

            data = json.dumps(payload)
        except (json.JSONDecodeError, TypeError):
            pass

        # Log raw payload with timestamp (debug only)
        if debug:
            try:
                log_payload = json.loads(data)
                log_payload["_ts"] = _now_iso()
                logger.debug(json.dumps(log_payload))
            except (json.JSONDecodeError, TypeError):
                logger.debug(
                    json.dumps({"_raw": data, "_ts": _now_iso()})
                )

        req = urllib.request.Request(
            url,
            data=data.encode(),
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        urllib.request.urlopen(req, timeout=2)
    except Exception:
        if debug:
            logger.debug("relay failed", exc_info=True)


if __name__ == "__main__":
    main()
