#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Install the AgentPulse hook relay script and default config.

Copies hook_relay.py to ~/.claude/agentpulse/scripts/ and
config.json to ~/.claude/agentpulse/ (if not already present).

Zero dependencies — stdlib only.
"""

import shutil
from pathlib import Path

_DEST_BASE = Path.home() / ".claude" / "agentpulse"


def main() -> None:
    project_root = Path(__file__).parent.parent

    # Install relay script
    scripts_dir = _DEST_BASE / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    relay_src = project_root / "scripts" / "hook_relay.py"
    relay_dest = scripts_dir / "hook_relay.py"
    shutil.copy2(relay_src, relay_dest)
    print(f"Installed hook_relay.py to {relay_dest}")

    # Install config (only if not present — don't overwrite user edits)
    config_dest = _DEST_BASE / "config.json"
    if not config_dest.exists():
        config_src = project_root / "config.example.json"
        shutil.copy2(config_src, config_dest)
        print(f"Installed default config to {config_dest}")
    else:
        print(f"Config already exists at {config_dest} (not overwritten)")

    print()
    print("Next: merge hooks-settings.json into ~/.claude/settings.json")
    print("  The hooks configuration tells Claude Code to relay events")
    print("  to AgentPulse. Edit config.json to change host/port.")


if __name__ == "__main__":
    main()
