#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Install AgentPulse hooks: copy relay script + merge hook config into Claude settings.

Deep merge strategy (matching ~/source/my-claude-stuff/scripts/reconcile.py):
- Dicts: recursively merged, source wins on conflicts
- Lists: union with deduplication (JSON serialization as key)
- Scalars: source overwrites
- Dest-only keys: preserved

Zero dependencies — stdlib only.
"""

import json
import logging
import shutil
import sys
from pathlib import Path

logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
HOOKS_SETTINGS = PROJECT_ROOT / "hooks-settings.json"
RELAY_SCRIPT = PROJECT_ROOT / "scripts" / "hook_relay.py"
CONFIG_EXAMPLE = PROJECT_ROOT / "config.example.json"
CLAUDE_SETTINGS = Path.home() / ".claude" / "settings.json"
INSTALL_BASE = Path.home() / ".claude" / "agentpulse"
INSTALL_SCRIPTS = INSTALL_BASE / "scripts"

_RELAY_MARKER = ".claude/agentpulse/scripts/hook_relay.py"


def _hook_entry_key(item: object) -> str | None:
    """Extract a stable identity key from a hook rule entry.

    Returns the relay marker so that flag changes replace the existing
    entry instead of duplicating it.
    """
    if not isinstance(item, dict):
        return None
    hooks = item.get("hooks")
    if not isinstance(hooks, list):
        return None
    for hook in hooks:
        if isinstance(hook, dict):
            cmd = hook.get("command", "")
            if _RELAY_MARKER in cmd:
                return _RELAY_MARKER
    return None


def _deep_merge(src: dict, dest: dict) -> dict:
    """Merge src into dest recursively. Returns dest (mutated)."""
    for key, src_val in src.items():
        if key not in dest:
            dest[key] = src_val
        elif isinstance(src_val, dict) and isinstance(dest[key], dict):
            _deep_merge(src_val, dest[key])
        elif isinstance(src_val, list) and isinstance(dest[key], list):
            keyed_indices: dict[str, int] = {}
            for i, item in enumerate(dest[key]):
                hk = _hook_entry_key(item)
                if hk is not None:
                    keyed_indices[hk] = i

            existing = {
                json.dumps(item, sort_keys=True) for item in dest[key]
            }
            for item in src_val:
                hk = _hook_entry_key(item)
                if hk is not None and hk in keyed_indices:
                    dest[key][keyed_indices[hk]] = item
                else:
                    serialized = json.dumps(item, sort_keys=True)
                    if serialized not in existing:
                        dest[key].append(item)
                        existing.add(serialized)
        else:
            dest[key] = src_val
    return dest


def install_hooks(
    *,
    hooks_path: Path | None = None,
    settings_path: Path | None = None,
    dry_run: bool = False,
) -> bool:
    """Copy relay script, install default config, and merge hooks."""
    hooks_file = hooks_path or HOOKS_SETTINGS
    settings_file = settings_path or CLAUDE_SETTINGS

    if not hooks_file.exists():
        logger.error("hooks settings file not found path=%s", hooks_file)
        return False

    if not dry_run:
        # Copy relay script
        INSTALL_SCRIPTS.mkdir(parents=True, exist_ok=True)
        dest_relay = INSTALL_SCRIPTS / "hook_relay.py"
        shutil.copy2(RELAY_SCRIPT, dest_relay)
        logger.info("relay script installed to %s", dest_relay)

        # Copy default config (only if not present)
        config_dest = INSTALL_BASE / "config.json"
        if not config_dest.exists():
            shutil.copy2(CONFIG_EXAMPLE, config_dest)
            logger.info("default config installed to %s", config_dest)
        else:
            logger.info("config already exists at %s (not overwritten)", config_dest)

    # Merge hook config into Claude settings
    src = json.loads(hooks_file.read_text(encoding="utf-8"))

    if settings_file.exists():
        dest = json.loads(settings_file.read_text(encoding="utf-8"))
    else:
        dest = {}

    merged = _deep_merge(src, dest)

    if dry_run:
        print(json.dumps(merged, indent=2))
        return True

    settings_file.parent.mkdir(parents=True, exist_ok=True)
    settings_file.write_text(
        json.dumps(merged, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    logger.info("hooks merged into %s", settings_file)
    return True


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    dry_run = "--dryrun" in sys.argv or "--dry-run" in sys.argv
    success = install_hooks(dry_run=dry_run)
    sys.exit(0 if success else 1)
