# Generated By: Claude Code (Claude Opus 4.6)
LOG_FILE := ~/.claude/$(PACKAGE_NAME)/$(PACKAGE_NAME).log

.PHONY: run
run: $(PYTHON) ## Start AgentPulse (use DEBUG=1 for debug logging)
	@echo "Logging to $(LOG_FILE)"
	$(if $(DEBUG),DEBUG=1) $(PYTHON) -m $(PACKAGE_NAME)
