# Generated By: Claude Code (Claude Opus 4.6)
CONFIG_FILE ?= ~/.claude/$(PACKAGE_NAME)/config.json

.PHONY: run
run: $(PYTHON) ## Start AgentPulse (set debug in config.json)
	$(PYTHON) -m $(PACKAGE_NAME) --config $(CONFIG_FILE)
