# Generated By: Claude Code (Claude Opus 4.7)
.PHONY: run-tray install-autostart-tray uninstall-autostart-tray

run-tray: $(PYTHON) ## Start tray icon in the foreground
	$(PYTHON) -m $(PACKAGE_NAME).tray --config $(CONFIG_FILE)

install-autostart-tray: $(PYTHON) ## Enable tray auto-start on login
	$(PYTHON) scripts/install_tray_autostart.py install

uninstall-autostart-tray: $(PYTHON) ## Disable tray auto-start
	$(PYTHON) scripts/install_tray_autostart.py uninstall
