# Generated By: Claude Code (Claude Opus 4.7)
"""Let tray tests mock subprocess directly (override root autouse block)."""

from typing import Iterator

import pytest


@pytest.fixture(autouse=True)
def _block_subprocess() -> Iterator[None]:
    yield
