# Generated By: Claude Code (Claude Opus 4.7)
"""Tests for the tray WebSocket client."""

from unittest.mock import AsyncMock, MagicMock, patch

from agentpulse.tray.state import TrayState
from agentpulse.tray.ws_client import (
    _backoff,
    apply_bootstrap,
    seed_from_summary,
)


def test_apply_bootstrap_sets_active_count() -> None:
    state = TrayState()
    apply_bootstrap(state, summary={"active_sessions": 7})
    assert state.active_sessions == 7


def test_apply_bootstrap_handles_missing_key() -> None:
    state = TrayState(active_sessions=3)
    apply_bootstrap(state, summary={})
    assert state.active_sessions == 0


def test_backoff_sequence() -> None:
    delays = [_backoff(i) for i in range(0, 7)]
    assert delays == [1, 2, 4, 8, 16, 30, 30]


async def test_seed_from_summary_sets_state() -> None:
    fake_response = MagicMock()
    fake_response.status_code = 200
    fake_response.json.return_value = {"active_sessions": 4}

    fake_client = MagicMock()
    fake_client.__aenter__ = AsyncMock(return_value=fake_client)
    fake_client.__aexit__ = AsyncMock(return_value=False)
    fake_client.get = AsyncMock(return_value=fake_response)

    state = TrayState()
    with patch("agentpulse.tray.ws_client._make_http_client", return_value=fake_client):
        ok = await seed_from_summary(state, base_url="http://127.0.0.1:17385")

    assert ok is True
    assert state.active_sessions == 4


async def test_seed_from_summary_non_200_marks_error() -> None:
    fake_response = MagicMock()
    fake_response.status_code = 500

    fake_client = MagicMock()
    fake_client.__aenter__ = AsyncMock(return_value=fake_client)
    fake_client.__aexit__ = AsyncMock(return_value=False)
    fake_client.get = AsyncMock(return_value=fake_response)

    state = TrayState()
    with patch("agentpulse.tray.ws_client._make_http_client", return_value=fake_client):
        ok = await seed_from_summary(state, base_url="http://127.0.0.1:17385")

    assert ok is False
    assert state.last_error == "summary http 500"


async def test_seed_from_summary_exception_marks_error() -> None:
    fake_client = MagicMock()
    fake_client.__aenter__ = AsyncMock(return_value=fake_client)
    fake_client.__aexit__ = AsyncMock(return_value=False)
    fake_client.get = AsyncMock(side_effect=Exception("connect refused"))

    state = TrayState()
    with patch("agentpulse.tray.ws_client._make_http_client", return_value=fake_client):
        ok = await seed_from_summary(state, base_url="http://127.0.0.1:17385")

    assert ok is False
    assert state.last_error == "connect refused"
