# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Slice A2: dual-write integration tests for /hooks/claude and /statusline/claude.

Each live ingestion endpoint writes the v1 row (existing behavior) AND the v2
log row from the same wire payload. These tests pin the parity between the
two so we can rely on it during the v1 retirement (slice E).
"""

import json
from pathlib import Path
from unittest.mock import patch

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from agentpulse.db import close_db, init_db
from agentpulse.platforms.claude.hooks import router as hooks_router
from tests.conftest import run_async

_SAMPLE_HOOK = {
    "session_id": "s-dual-1",
    "hook_event_name": "PreToolUse",
    "tool_name": "Bash",
    "agent_id": "",
    "agent_type": "",
    "cwd": "/proj",
    "source_system": "host.example",
    "pid": 4242,
}


_SAMPLE_STATUSLINE = {
    "session_id": "s-dual-1",
    "pid": 4242,
    "source_system": "host.example",
    "cwd": "/proj",
    "transcript_path": "/tmp/s.jsonl",
    "model": {
        "id": "claude-opus-4-7[1m]",
        "display_name": "Opus 4.7 (1M context)",
    },
    "workspace": {
        "current_dir": "/proj",
        "project_dir": "/proj",
        "added_dirs": ["/proj"],
    },
    "version": "2.1.117",
    "cost": {
        "total_cost_usd": 1.25,
        "total_duration_ms": 60000,
        "total_api_duration_ms": 12000,
        "total_lines_added": 10,
        "total_lines_removed": 2,
    },
    "context_window": {
        "total_input_tokens": 1000,
        "total_output_tokens": 500,
        "context_window_size": 1000000,
        "current_usage": {
            "input_tokens": 5,
            "output_tokens": 200,
            "cache_creation_input_tokens": 300,
            "cache_read_input_tokens": 800,
        },
        "used_percentage": 25.0,
        "remaining_percentage": 75.0,
    },
    "exceeds_200k_tokens": False,
}


@pytest.fixture
async def db(tmp_path: Path):
    conn = await init_db(db_path=tmp_path / "test.db")
    yield conn
    await close_db()


@pytest.fixture
def client(db) -> TestClient:
    app = FastAPI()
    app.include_router(hooks_router)
    return TestClient(app)


class TestHookDualWrite:
    def test_hook_writes_v1_and_v2(self, client, db) -> None:
        with patch(
            "agentpulse.platforms.claude.hooks.detect_entrypoint",
            return_value="vscode",
        ):
            resp = client.post("/hooks/claude", json=_SAMPLE_HOOK)
        assert resp.status_code == 200

        # v1 row landed
        v1 = run_async(
            db.execute(
                "SELECT count(*) AS n FROM claude_events WHERE session_id = ?",
                ("s-dual-1",),
            )
        )
        assert dict(run_async(v1.fetchone()))["n"] == 1

        # v2 row landed with the same identity + extracted fields
        v2 = run_async(
            db.execute(
                "SELECT * FROM claude_log_hooks WHERE session_id = ?",
                ("s-dual-1",),
            )
        )
        rows = run_async(v2.fetchall())
        assert len(rows) == 1
        row = dict(rows[0])
        assert row["pid"] == 4242
        assert row["source_system"] == "host.example"
        assert row["cwd"] == "/proj"
        assert row["event_name"] == "PreToolUse"
        assert row["tool_name"] == "Bash"
        assert row["agent_id"] is None  # empty string → null
        assert row["entrypoint"] == "vscode"
        assert row["received_by"] == "hook-endpoint"

    def test_hook_v2_raw_payload_is_wire_bytes(self, client, db) -> None:
        """raw_payload must preserve the original wire bytes, not a re-serialized dump.

        Pydantic's model_dump fills defaults ("" for absent agent_id, etc.); the
        original body might omit them. This test sends a payload that omits
        optional fields and asserts the v2 raw_payload doesn't grow them.
        """
        # Trim payload to required-only — omit optional defaults
        minimal = {
            "session_id": "s-min",
            "hook_event_name": "Stop",
            "pid": 7,
        }
        client.post("/hooks/claude", json=minimal)

        cursor = run_async(
            db.execute(
                "SELECT raw_payload FROM claude_log_hooks WHERE session_id = ?",
                ("s-min",),
            )
        )
        row = dict(run_async(cursor.fetchone()))
        stored = json.loads(row["raw_payload"])
        # The wire payload had three keys; stored raw should not include
        # the Pydantic-default empties (tool_name, agent_id, etc.)
        assert set(stored.keys()) == {"session_id", "hook_event_name", "pid"}

    def test_hook_skips_v2_when_no_pid(self, client, db) -> None:
        """No pid → v1 still writes, v2 silently skips."""
        no_pid = {
            "session_id": "s-no-pid",
            "hook_event_name": "PreToolUse",
            "tool_name": "Bash",
        }
        # Also stub detect_entrypoint so it doesn't error on pid=0
        with patch(
            "agentpulse.platforms.claude.hooks.detect_entrypoint",
            return_value="cli",
        ):
            resp = client.post("/hooks/claude", json=no_pid)
        assert resp.status_code == 200

        # v1 wrote
        v1 = run_async(
            db.execute(
                "SELECT count(*) AS n FROM claude_events WHERE session_id = ?",
                ("s-no-pid",),
            )
        )
        assert dict(run_async(v1.fetchone()))["n"] == 1

        # v2 skipped (no pid in payload → insert_log_hook returns False)
        v2 = run_async(
            db.execute(
                "SELECT count(*) AS n FROM claude_log_hooks WHERE session_id = ?",
                ("s-no-pid",),
            )
        )
        assert dict(run_async(v2.fetchone()))["n"] == 0

    def test_multiple_hooks_append_to_v2(self, client, db) -> None:
        for event in ("PreToolUse", "PostToolUse", "Stop"):
            payload = {**_SAMPLE_HOOK, "hook_event_name": event}
            client.post("/hooks/claude", json=payload)

        cursor = run_async(
            db.execute(
                "SELECT event_name FROM claude_log_hooks "
                "WHERE session_id = ? ORDER BY id",
                ("s-dual-1",),
            )
        )
        rows = run_async(cursor.fetchall())
        assert [dict(r)["event_name"] for r in rows] == [
            "PreToolUse",
            "PostToolUse",
            "Stop",
        ]


class TestStatuslineDualWrite:
    def test_statusline_writes_v1_and_v2(self, client, db) -> None:
        resp = client.post("/statusline/claude", json=_SAMPLE_STATUSLINE)
        assert resp.status_code == 200

        v1 = run_async(
            db.execute(
                "SELECT count(*) AS n FROM claude_statusline WHERE session_id = ?",
                ("s-dual-1",),
            )
        )
        assert dict(run_async(v1.fetchone()))["n"] == 1

        v2 = run_async(
            db.execute(
                "SELECT * FROM claude_log_statuslines WHERE session_id = ?",
                ("s-dual-1",),
            )
        )
        rows = run_async(v2.fetchall())
        assert len(rows) == 1
        row = dict(rows[0])
        assert row["pid"] == 4242
        assert row["source_system"] == "host.example"
        assert row["cwd"] == "/proj"
        assert row["project_dir"] == "/proj"
        assert row["model_id"] == "claude-opus-4-7[1m]"
        assert row["model_name"] == "Opus 4.7 (1M context)"
        assert row["claude_version"] == "2.1.117"
        assert row["cost_usd"] == 1.25
        assert row["duration_seconds"] == 60.0  # 60000ms / 1000
        assert row["api_duration_seconds"] == 12.0
        assert row["context_used_pct"] == 25.0
        assert row["cache_read_tokens"] == 800
        assert row["cache_creation_tokens"] == 300
        assert row["received_by"] == "statusline-endpoint"

    def test_statusline_v2_raw_payload_is_wire_bytes(self, client, db) -> None:
        """raw_payload preserves the exact body the relay sent."""
        client.post("/statusline/claude", json=_SAMPLE_STATUSLINE)

        cursor = run_async(
            db.execute(
                "SELECT raw_payload FROM claude_log_statuslines "
                "WHERE session_id = ?",
                ("s-dual-1",),
            )
        )
        row = dict(run_async(cursor.fetchone()))
        stored = json.loads(row["raw_payload"])
        # All wire keys are preserved; no defaults injected
        assert stored == _SAMPLE_STATUSLINE

    def test_statusline_skips_v2_when_no_pid(self, client, db) -> None:
        """No pid in statusline payload → v1 writes, v2 skips."""
        no_pid = {k: v for k, v in _SAMPLE_STATUSLINE.items() if k != "pid"}
        client.post("/statusline/claude", json=no_pid)

        v1 = run_async(
            db.execute(
                "SELECT count(*) AS n FROM claude_statusline WHERE session_id = ?",
                ("s-dual-1",),
            )
        )
        assert dict(run_async(v1.fetchone()))["n"] == 1

        v2 = run_async(
            db.execute(
                "SELECT count(*) AS n FROM claude_log_statuslines "
                "WHERE session_id = ?",
                ("s-dual-1",),
            )
        )
        assert dict(run_async(v2.fetchone()))["n"] == 0

    def test_statusline_ignored_no_session_id_does_not_write_v2(
        self, client, db
    ) -> None:
        """When v1 ignores the payload (no session_id), v2 must not write either."""
        no_sid = {k: v for k, v in _SAMPLE_STATUSLINE.items() if k != "session_id"}
        resp = client.post("/statusline/claude", json=no_sid)
        assert resp.json()["status"] == "ignored"

        v2 = run_async(db.execute("SELECT count(*) AS n FROM claude_log_statuslines"))
        assert dict(run_async(v2.fetchone()))["n"] == 0

    def test_multiple_statuslines_append_to_v2(self, client, db) -> None:
        for cost in (1.0, 2.0, 3.0):
            payload = {
                **_SAMPLE_STATUSLINE,
                "cost": {**_SAMPLE_STATUSLINE["cost"], "total_cost_usd": cost},
            }
            client.post("/statusline/claude", json=payload)

        cursor = run_async(
            db.execute(
                "SELECT cost_usd FROM claude_log_statuslines "
                "WHERE session_id = ? ORDER BY id",
                ("s-dual-1",),
            )
        )
        rows = run_async(cursor.fetchall())
        assert [dict(r)["cost_usd"] for r in rows] == [1.0, 2.0, 3.0]
