# Generated By: Claude Code (Claude Opus 4.7)
"""Tests for v2 append-only log tables and inserters."""

from pathlib import Path

import pytest

from agentpulse.db import close_db, init_db
from agentpulse.platforms.claude import schema


@pytest.fixture
async def db(tmp_path: Path):
    """Provide an initialized test database."""
    db_path = tmp_path / "test.db"
    conn = await init_db(db_path=db_path)
    yield conn
    await close_db()


class TestLogTablesExist:
    async def test_claude_log_hooks_created(self, db) -> None:
        cursor = await db.execute(
            "SELECT name FROM sqlite_master "
            "WHERE type='table' AND name='claude_log_hooks'"
        )
        row = await cursor.fetchone()
        assert row is not None

    async def test_claude_log_statuslines_created(self, db) -> None:
        cursor = await db.execute(
            "SELECT name FROM sqlite_master "
            "WHERE type='table' AND name='claude_log_statuslines'"
        )
        row = await cursor.fetchone()
        assert row is not None

    async def test_log_hooks_columns(self, db) -> None:
        cursor = await db.execute("PRAGMA table_info(claude_log_hooks)")
        cols = {row["name"] for row in await cursor.fetchall()}
        expected = {
            "id",
            "pid",
            "session_id",
            "source_system",
            "cwd",
            "agent_id",
            "event_name",
            "tool_name",
            "agent_type",
            "permission_mode",
            "entrypoint",
            "claude_version",
            "received_at",
            "received_by",
            "raw_payload",
        }
        assert expected.issubset(cols)

    async def test_log_statuslines_columns(self, db) -> None:
        cursor = await db.execute("PRAGMA table_info(claude_log_statuslines)")
        cols = {row["name"] for row in await cursor.fetchall()}
        expected = {
            "id",
            "pid",
            "session_id",
            "source_system",
            "cwd",
            "project_dir",
            "model_id",
            "model_name",
            "claude_version",
            "cost_usd",
            "total_input_tokens",
            "total_output_tokens",
            "context_used_pct",
            "context_window_size",
            "cache_read_tokens",
            "cache_creation_tokens",
            "duration_seconds",
            "api_duration_seconds",
            "lines_added",
            "lines_removed",
            "exceeds_200k_tokens",
            "received_at",
            "received_by",
            "raw_payload",
        }
        assert expected.issubset(cols)


class TestLogTableIndexes:
    async def _index_names_for(self, db, table: str) -> set[str]:
        cursor = await db.execute(
            "SELECT name FROM sqlite_master "
            "WHERE type='index' AND tbl_name = ? AND sql IS NOT NULL",
            (table,),
        )
        return {row["name"] for row in await cursor.fetchall()}

    async def test_claude_log_hooks_indexes(self, db) -> None:
        names = await self._index_names_for(db, "claude_log_hooks")
        assert "idx_claude_log_hooks_session" in names
        assert "idx_claude_log_hooks_process" in names
        assert "idx_claude_log_hooks_received" in names
        assert "idx_claude_log_hooks_agent" in names

    async def test_claude_log_statuslines_indexes(self, db) -> None:
        names = await self._index_names_for(db, "claude_log_statuslines")
        assert "idx_claude_log_statuslines_session" in names
        assert "idx_claude_log_statuslines_process" in names
        assert "idx_claude_log_statuslines_received" in names

    async def test_agent_index_is_partial(self, db) -> None:
        """The agent_id index should be partial (WHERE agent_id IS NOT NULL)."""
        cursor = await db.execute(
            "SELECT sql FROM sqlite_master "
            "WHERE type='index' AND name='idx_claude_log_hooks_agent'"
        )
        row = await cursor.fetchone()
        assert row is not None
        assert "WHERE" in row["sql"].upper()
        assert "AGENT_ID IS NOT NULL" in row["sql"].upper()


class TestInsertLogHook:
    """Direct unit tests for the canonical hook inserter."""

    async def test_inserts_basic_hook(self, db) -> None:
        payload = {
            "session_id": "s1",
            "hook_event_name": "PreToolUse",
            "tool_name": "Bash",
            "pid": 1234,
            "source_system": "host.example",
            "cwd": "/proj",
            "permission_mode": "acceptEdits",
            "claude_version": "2.1.117",
        }
        log_id = await schema.insert_log_hook(
            db,
            payload=payload,
            received_at=100.0,
            received_by="hook-endpoint",
        )
        assert isinstance(log_id, int) and log_id > 0

        cursor = await db.execute("SELECT * FROM claude_log_hooks")
        row = await cursor.fetchone()
        assert row is not None
        assert row["pid"] == 1234
        assert row["session_id"] == "s1"
        assert row["event_name"] == "PreToolUse"
        assert row["tool_name"] == "Bash"
        assert row["source_system"] == "host.example"
        assert row["cwd"] == "/proj"
        assert row["permission_mode"] == "acceptEdits"
        assert row["claude_version"] == "2.1.117"
        assert row["received_by"] == "hook-endpoint"

    async def test_returns_none_without_pid(self, db) -> None:
        payload = {"session_id": "s1", "hook_event_name": "Stop"}
        log_id = await schema.insert_log_hook(
            db,
            payload=payload,
            received_at=100.0,
            received_by="hook-endpoint",
        )
        assert log_id is None

        cursor = await db.execute("SELECT count(*) AS n FROM claude_log_hooks")
        row = await cursor.fetchone()
        assert row["n"] == 0

    async def test_entrypoint_param_stored(self, db) -> None:
        """entrypoint is the only v2 field not in the payload — caller supplies."""
        payload = {
            "session_id": "s1",
            "hook_event_name": "PreToolUse",
            "pid": 1234,
        }
        await schema.insert_log_hook(
            db,
            payload=payload,
            received_at=100.0,
            received_by="hook-endpoint",
            entrypoint="vscode",
        )
        cursor = await db.execute("SELECT entrypoint FROM claude_log_hooks")
        row = await cursor.fetchone()
        assert row["entrypoint"] == "vscode"

    async def test_empty_string_agent_id_stored_as_null(self, db) -> None:
        """Wire payloads use '' for missing agent_id; v2 stores NULL."""
        payload = {
            "session_id": "s1",
            "hook_event_name": "PreToolUse",
            "agent_id": "",
            "pid": 1234,
        }
        await schema.insert_log_hook(
            db,
            payload=payload,
            received_at=100.0,
            received_by="hook-endpoint",
        )
        cursor = await db.execute("SELECT agent_id FROM claude_log_hooks")
        row = await cursor.fetchone()
        assert row["agent_id"] is None


class TestInsertLogStatusline:
    """Direct unit tests for the canonical statusline inserter."""

    async def test_inserts_full_payload(self, db) -> None:
        payload = {
            "session_id": "s1",
            "pid": 1234,
            "source_system": "host.example",
            "cwd": "/proj",
            "version": "2.1.117",
            "workspace": {"project_dir": "/proj"},
            "model": {"id": "claude-opus-4-7[1m]", "display_name": "Opus 4.7"},
            "cost": {
                "total_cost_usd": 1.5,
                "total_duration_ms": 60000,
                "total_api_duration_ms": 12000,
                "total_lines_added": 10,
                "total_lines_removed": 2,
            },
            "context_window": {
                "total_input_tokens": 1000,
                "total_output_tokens": 500,
                "used_percentage": 25.0,
                "context_window_size": 1000000,
                "current_usage": {
                    "cache_read_input_tokens": 800,
                    "cache_creation_input_tokens": 300,
                },
            },
            "exceeds_200k_tokens": False,
        }
        log_id = await schema.insert_log_statusline(
            db,
            payload=payload,
            received_at=100.0,
            received_by="statusline-endpoint",
        )
        assert isinstance(log_id, int) and log_id > 0

        cursor = await db.execute("SELECT * FROM claude_log_statuslines")
        row = await cursor.fetchone()
        assert row is not None
        assert row["pid"] == 1234
        assert row["source_system"] == "host.example"
        assert row["model_id"] == "claude-opus-4-7[1m]"
        assert row["model_name"] == "Opus 4.7"
        assert row["claude_version"] == "2.1.117"
        assert row["project_dir"] == "/proj"
        assert row["cost_usd"] == 1.5
        assert row["duration_seconds"] == 60.0
        assert row["api_duration_seconds"] == 12.0
        assert row["context_used_pct"] == 25.0
        assert row["cache_read_tokens"] == 800
        assert row["cache_creation_tokens"] == 300
        assert row["lines_added"] == 10
        assert row["received_by"] == "statusline-endpoint"

    async def test_returns_none_without_pid(self, db) -> None:
        payload = {"session_id": "s1"}
        log_id = await schema.insert_log_statusline(
            db,
            payload=payload,
            received_at=100.0,
            received_by="statusline-endpoint",
        )
        assert log_id is None

    async def test_raw_payload_preserved_when_passed(self, db) -> None:
        """Callers may pass original raw_payload bytes for provenance."""
        payload = {"session_id": "s1", "pid": 1234}
        original = '{"session_id": "s1", "pid": 1234, "extra": "preserved"}'
        await schema.insert_log_statusline(
            db,
            payload=payload,
            received_at=100.0,
            received_by="statusline-endpoint",
            raw_payload=original,
        )
        cursor = await db.execute("SELECT raw_payload FROM claude_log_statuslines")
        row = await cursor.fetchone()
        assert row["raw_payload"] == original

    async def test_cwd_falls_back_to_workspace_project_dir(self, db) -> None:
        """SDK-style payload: only `workspace.project_dir`, no top-level `cwd`.

        Statusline cwd must inherit workspace.project_dir so the (pid,
        source_system, cwd) tuple matches hooks for the same process.
        """
        payload = {
            "session_id": "s1",
            "pid": 1234,
            "source_system": "host",
            "workspace": {"project_dir": "C:/Users/me/project"},
        }
        await schema.insert_log_statusline(
            db,
            payload=payload,
            received_at=100.0,
            received_by="statusline-endpoint",
        )
        cursor = await db.execute(
            "SELECT cwd FROM claude_log_statuslines WHERE session_id = 's1'"
        )
        row = await cursor.fetchone()
        assert row["cwd"] == "C:/Users/me/project"

    async def test_cwd_top_level_wins_over_workspace(self, db) -> None:
        """When both fields exist, top-level cwd wins."""
        payload = {
            "session_id": "s1",
            "pid": 1234,
            "cwd": "/explicit/cwd",
            "workspace": {"project_dir": "/different/workspace"},
        }
        await schema.insert_log_statusline(
            db,
            payload=payload,
            received_at=100.0,
            received_by="statusline-endpoint",
        )
        cursor = await db.execute("SELECT cwd FROM claude_log_statuslines")
        row = await cursor.fetchone()
        assert row["cwd"] == "/explicit/cwd"

    async def test_cwd_empty_when_neither_field_present(self, db) -> None:
        payload = {"session_id": "s1", "pid": 1234}
        await schema.insert_log_statusline(
            db,
            payload=payload,
            received_at=100.0,
            received_by="statusline-endpoint",
        )
        cursor = await db.execute("SELECT cwd FROM claude_log_statuslines")
        row = await cursor.fetchone()
        assert row["cwd"] == ""
