# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for session discovery — PID liveness and entrypoint detection."""

from pathlib import Path
from unittest.mock import patch, MagicMock

import pytest

from agentpulse.db import close_db, init_db
from agentpulse.platforms.claude.discovery import (
    detect_entrypoint,
    run_discovery_tick,
    validate_pid,
)
from agentpulse.platforms.claude import schema


@pytest.fixture
async def db(tmp_path: Path):
    conn = await init_db(db_path=tmp_path / "test.db")
    yield conn
    await close_db()


class TestValidatePid:
    def test_alive_claude_process(self) -> None:
        with patch("agentpulse.platforms.claude.discovery.psutil") as mock_psutil:
            mock_psutil.pid_exists.return_value = True
            mock_proc = mock_psutil.Process.return_value
            mock_proc.name.return_value = "claude"
            assert validate_pid(pid=1234) is True

    def test_dead_process(self) -> None:
        with patch("agentpulse.platforms.claude.discovery.psutil") as mock_psutil:
            mock_psutil.pid_exists.return_value = False
            assert validate_pid(pid=9999) is False

    def test_non_claude_process(self) -> None:
        with patch("agentpulse.platforms.claude.discovery.psutil") as mock_psutil:
            mock_psutil.pid_exists.return_value = True
            mock_proc = mock_psutil.Process.return_value
            mock_proc.name.return_value = "bash"
            assert validate_pid(pid=1234) is False


class TestDetectEntrypoint:
    def test_vscode_parent(self) -> None:
        with patch("agentpulse.platforms.claude.discovery.psutil") as mock_psutil:
            parent = MagicMock()
            parent.name.return_value = "Code.exe"
            grandparent = MagicMock()
            grandparent.name.return_value = "explorer.exe"
            mock_psutil.Process.return_value.parents.return_value = [
                parent,
                grandparent,
            ]
            assert detect_entrypoint(pid=1234) == "vscode"

    def test_cursor_parent(self) -> None:
        with patch("agentpulse.platforms.claude.discovery.psutil") as mock_psutil:
            parent = MagicMock()
            parent.name.return_value = "Cursor.exe"
            mock_psutil.Process.return_value.parents.return_value = [parent]
            assert detect_entrypoint(pid=1234) == "cursor"

    def test_jetbrains_parent(self) -> None:
        with patch("agentpulse.platforms.claude.discovery.psutil") as mock_psutil:
            parent = MagicMock()
            parent.name.return_value = "pycharm64.exe"
            mock_psutil.Process.return_value.parents.return_value = [parent]
            assert detect_entrypoint(pid=1234) == "jetbrains"

    def test_terminal_defaults_to_cli(self) -> None:
        with patch("agentpulse.platforms.claude.discovery.psutil") as mock_psutil:
            parent = MagicMock()
            parent.name.return_value = "bash"
            grandparent = MagicMock()
            grandparent.name.return_value = "WindowsTerminal.exe"
            mock_psutil.Process.return_value.parents.return_value = [
                parent,
                grandparent,
            ]
            assert detect_entrypoint(pid=1234) == "cli"

    def test_pid_zero_returns_cli(self) -> None:
        assert detect_entrypoint(pid=0) == "cli"

    def test_negative_pid_returns_cli(self) -> None:
        assert detect_entrypoint(pid=-1) == "cli"

    def test_dead_process_returns_cli(self) -> None:
        with patch("agentpulse.platforms.claude.discovery.psutil") as mock_psutil:
            mock_psutil.NoSuchProcess = type("NoSuchProcess", (Exception,), {})
            mock_psutil.AccessDenied = type("AccessDenied", (Exception,), {})
            mock_psutil.Process.side_effect = mock_psutil.NoSuchProcess()
            assert detect_entrypoint(pid=9999) == "cli"

    def test_linux_vscode_no_exe_suffix(self) -> None:
        with patch("agentpulse.platforms.claude.discovery.psutil") as mock_psutil:
            parent = MagicMock()
            parent.name.return_value = "code"
            mock_psutil.Process.return_value.parents.return_value = [parent]
            assert detect_entrypoint(pid=1234) == "vscode"


class TestRunDiscoveryTick:
    async def test_marks_dead_session_ended(self, db) -> None:
        """Sessions with dead PIDs get marked as ended."""
        await schema.upsert_session(
            db,
            session_id="will-die",
            pid=1234,
            cwd="/tmp/proj",
            last_event="PreToolUse",
            last_event_at=1.0,
        )

        with patch(
            "agentpulse.platforms.claude.discovery.validate_pid",
            return_value=False,
        ):
            await run_discovery_tick(db)

        row = await schema.get_session(db, session_id="will-die")
        assert row["pid_alive"] == 0
        assert row["ended_at"] is not None

    async def test_alive_session_unchanged(self, db) -> None:
        """Sessions with alive PIDs stay alive."""
        await schema.upsert_session(
            db,
            session_id="alive",
            pid=1234,
            cwd="/tmp/proj",
            last_event="PreToolUse",
            last_event_at=1.0,
        )

        with patch(
            "agentpulse.platforms.claude.discovery.validate_pid",
            return_value=True,
        ):
            await run_discovery_tick(db)

        row = await schema.get_session(db, session_id="alive")
        assert row["pid_alive"] == 1
        assert row["ended_at"] is None

    async def test_hook_only_session_not_killed(self, db) -> None:
        """Sessions with pid=0 (created by hooks, no PID yet) must not
        be killed by the liveness check."""
        await schema.upsert_session(
            db,
            session_id="hook-only",
            pid=0,
            cwd="/tmp/proj",
            last_event="PreToolUse",
            last_event_at=1.0,
        )

        with patch(
            "agentpulse.platforms.claude.discovery.validate_pid",
            return_value=False,
        ) as mock_validate:
            await run_discovery_tick(db)

        mock_validate.assert_not_called()

        row = await schema.get_session(db, session_id="hook-only")
        assert row["pid_alive"] == 1
        assert row["ended_at"] is None

    async def test_ended_sessions_skipped(self, db) -> None:
        """Already-ended sessions are not rechecked."""
        await schema.upsert_session(
            db,
            session_id="ended",
            pid=1234,
            cwd="/tmp/proj",
        )
        await schema.end_session(db, session_id="ended", ended_at=99.0)
        await schema.update_session_pid_alive(db, session_id="ended", pid_alive=False)

        with patch(
            "agentpulse.platforms.claude.discovery.validate_pid",
        ) as mock_validate:
            await run_discovery_tick(db)

        mock_validate.assert_not_called()
