# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Tests for v2 append-only log tables and the v1→v2 replay migration.

Slice A1 of the v2 rollout. See docs/old/changes-with-v2.md for the
slicing plan and docs/old/data-migration.md for the replay rules.
"""

import json
from pathlib import Path

import pytest

from agentpulse.db import close_db, init_db
from agentpulse.platforms.claude import schema


@pytest.fixture
async def db(tmp_path: Path):
    """Provide an initialized test database."""
    db_path = tmp_path / "test.db"
    conn = await init_db(db_path=db_path)
    yield conn
    await close_db()


class TestLogTablesExist:
    async def test_claude_log_hooks_created(self, db) -> None:
        cursor = await db.execute(
            "SELECT name FROM sqlite_master "
            "WHERE type='table' AND name='claude_log_hooks'"
        )
        row = await cursor.fetchone()
        assert row is not None

    async def test_claude_log_statuslines_created(self, db) -> None:
        cursor = await db.execute(
            "SELECT name FROM sqlite_master "
            "WHERE type='table' AND name='claude_log_statuslines'"
        )
        row = await cursor.fetchone()
        assert row is not None

    async def test_log_hooks_columns(self, db) -> None:
        cursor = await db.execute("PRAGMA table_info(claude_log_hooks)")
        cols = {row["name"] for row in await cursor.fetchall()}
        expected = {
            "id",
            "pid",
            "session_id",
            "source_system",
            "cwd",
            "agent_id",
            "event_name",
            "tool_name",
            "agent_type",
            "permission_mode",
            "entrypoint",
            "claude_version",
            "received_at",
            "received_by",
            "raw_payload",
        }
        assert expected.issubset(cols)

    async def test_log_statuslines_columns(self, db) -> None:
        cursor = await db.execute("PRAGMA table_info(claude_log_statuslines)")
        cols = {row["name"] for row in await cursor.fetchall()}
        expected = {
            "id",
            "pid",
            "session_id",
            "source_system",
            "cwd",
            "project_dir",
            "model_id",
            "model_name",
            "claude_version",
            "cost_usd",
            "total_input_tokens",
            "total_output_tokens",
            "context_used_pct",
            "context_window_size",
            "cache_read_tokens",
            "cache_creation_tokens",
            "duration_seconds",
            "api_duration_seconds",
            "lines_added",
            "lines_removed",
            "exceeds_200k_tokens",
            "received_at",
            "received_by",
            "raw_payload",
        }
        assert expected.issubset(cols)


class TestLogTableIndexes:
    async def _index_names_for(self, db, table: str) -> set[str]:
        cursor = await db.execute(
            "SELECT name FROM sqlite_master "
            "WHERE type='index' AND tbl_name = ? AND sql IS NOT NULL",
            (table,),
        )
        return {row["name"] for row in await cursor.fetchall()}

    async def test_claude_log_hooks_indexes(self, db) -> None:
        names = await self._index_names_for(db, "claude_log_hooks")
        assert "idx_claude_log_hooks_session" in names
        assert "idx_claude_log_hooks_process" in names
        assert "idx_claude_log_hooks_received" in names
        assert "idx_claude_log_hooks_agent" in names

    async def test_claude_log_statuslines_indexes(self, db) -> None:
        names = await self._index_names_for(db, "claude_log_statuslines")
        assert "idx_claude_log_statuslines_session" in names
        assert "idx_claude_log_statuslines_process" in names
        assert "idx_claude_log_statuslines_received" in names

    async def test_agent_index_is_partial(self, db) -> None:
        """The agent_id index should be partial (WHERE agent_id IS NOT NULL)."""
        cursor = await db.execute(
            "SELECT sql FROM sqlite_master "
            "WHERE type='index' AND name='idx_claude_log_hooks_agent'"
        )
        row = await cursor.fetchone()
        assert row is not None
        assert "WHERE" in row["sql"].upper()
        assert "AGENT_ID IS NOT NULL" in row["sql"].upper()


class TestReplayHooks:
    async def _seed_v1_event(
        self,
        db,
        *,
        session_id: str,
        event_name: str,
        received_at: float,
        payload_overrides: dict | None = None,
        cwd: str = "/proj",
        agent_id: str | None = None,
        tool_name: str | None = None,
    ) -> None:
        # Mirror real v1 ingestion: the relay payload carries every field;
        # claude_events columns are derived from the same payload at ingest.
        payload = {
            "session_id": session_id,
            "hook_event_name": event_name,
            "tool_name": tool_name or "",
            "pid": 1234,
            "source_system": "host.example",
            "cwd": cwd,
            "agent_id": agent_id or "",
            "permission_mode": "acceptEdits",
        }
        if payload_overrides:
            payload.update(payload_overrides)
        await db.execute(
            "INSERT INTO claude_events (session_id, agent_id, event_name, "
            "tool_name, cwd, received_at, raw_payload) "
            "VALUES (?, ?, ?, ?, ?, ?, ?)",
            (
                session_id,
                agent_id,
                event_name,
                tool_name,
                cwd,
                received_at,
                json.dumps(payload),
            ),
        )
        await db.commit()

    async def test_replays_v1_event_into_log(self, db) -> None:
        await self._seed_v1_event(
            db,
            session_id="s1",
            event_name="PreToolUse",
            received_at=100.0,
            tool_name="Bash",
        )
        # Ensure replay is needed: v2 table is empty
        result = await schema.replay_v1_to_v2_logs(db)
        assert result["hooks"] == 1

        cursor = await db.execute(
            "SELECT * FROM claude_log_hooks WHERE session_id = 's1'"
        )
        row = await cursor.fetchone()
        assert row is not None
        assert row["pid"] == 1234
        assert row["source_system"] == "host.example"
        assert row["cwd"] == "/proj"
        assert row["event_name"] == "PreToolUse"
        assert row["tool_name"] == "Bash"
        assert row["permission_mode"] == "acceptEdits"
        assert row["received_at"] == 100.0
        assert row["received_by"] == "hook-endpoint-v1-replay"

    async def test_drops_pidless_v1_events(self, db) -> None:
        # Seed an event whose raw_payload has no pid (pre-injection era)
        payload = {
            "session_id": "s1",
            "hook_event_name": "PreToolUse",
            "source_system": "host.example",
            "cwd": "/proj",
        }
        await db.execute(
            "INSERT INTO claude_events (session_id, event_name, cwd, "
            "received_at, raw_payload) VALUES (?, ?, ?, ?, ?)",
            ("s1", "PreToolUse", "/proj", 100.0, json.dumps(payload)),
        )
        await db.commit()

        result = await schema.replay_v1_to_v2_logs(db)
        assert result["hooks"] == 0

        cursor = await db.execute("SELECT count(*) AS n FROM claude_log_hooks")
        row = await cursor.fetchone()
        assert row["n"] == 0

    async def test_pulls_entrypoint_from_session_row(self, db) -> None:
        await schema.upsert_session(
            db,
            session_id="s1",
            pid=1234,
            cwd="/proj",
            entrypoint="vscode",
            started_at=1000,
        )
        await self._seed_v1_event(
            db,
            session_id="s1",
            event_name="UserPromptSubmit",
            received_at=100.0,
        )

        await schema.replay_v1_to_v2_logs(db)

        cursor = await db.execute(
            "SELECT entrypoint FROM claude_log_hooks WHERE session_id = 's1'"
        )
        row = await cursor.fetchone()
        assert row["entrypoint"] == "vscode"


class TestReplayStatuslines:
    async def _seed_v1_statusline(
        self,
        db,
        *,
        session_id: str,
        received_at: float,
        cost_usd: float = 1.5,
        duration_ms: int = 120000,
        with_pid: bool = True,
    ) -> None:
        # Mirror real v1 ingestion: payload carries the full nested cost +
        # context_window structure; v1 columns are extracted from it.
        payload = {
            "session_id": session_id,
            "cwd": "/proj",
            "source_system": "host.example",
            "model": {"id": "claude-opus-4-7[1m]", "display_name": "Opus 4.7"},
            "version": "2.1.117",
            "workspace": {"project_dir": "/proj"},
            "cost": {
                "total_cost_usd": cost_usd,
                "total_duration_ms": duration_ms,
                "total_api_duration_ms": 30000,
                "total_lines_added": 0,
                "total_lines_removed": 0,
            },
            "context_window": {
                "total_input_tokens": 0,
                "total_output_tokens": 0,
            },
            "exceeds_200k_tokens": False,
        }
        if with_pid:
            payload["pid"] = 1234

        await db.execute(
            "INSERT INTO claude_statusline (session_id, received_at, cost_usd, "
            "duration_ms, api_duration_ms, model_name, raw_payload) "
            "VALUES (?, ?, ?, ?, ?, ?, ?)",
            (
                session_id,
                received_at,
                cost_usd,
                duration_ms,
                30000,
                "Opus 4.7",
                json.dumps(payload),
            ),
        )
        await db.commit()

    async def test_replays_v1_statusline(self, db) -> None:
        await self._seed_v1_statusline(
            db, session_id="s1", received_at=100.0, cost_usd=2.5
        )

        result = await schema.replay_v1_to_v2_logs(db)
        assert result["statuslines"] == 1

        cursor = await db.execute(
            "SELECT * FROM claude_log_statuslines WHERE session_id = 's1'"
        )
        row = await cursor.fetchone()
        assert row is not None
        assert row["pid"] == 1234
        assert row["source_system"] == "host.example"
        assert row["model_id"] == "claude-opus-4-7[1m]"
        assert row["model_name"] == "Opus 4.7"
        assert row["claude_version"] == "2.1.117"
        assert row["project_dir"] == "/proj"
        assert row["cost_usd"] == 2.5
        assert row["duration_seconds"] == 120.0  # 120000 / 1000
        assert row["api_duration_seconds"] == 30.0
        assert row["received_by"] == "statusline-endpoint-v1-replay"

    async def test_drops_pidless_statuslines(self, db) -> None:
        await self._seed_v1_statusline(
            db, session_id="s1", received_at=100.0, with_pid=False
        )
        result = await schema.replay_v1_to_v2_logs(db)
        assert result["statuslines"] == 0


class TestInsertLogHook:
    """Direct unit tests for the canonical hook inserter (slice A2 will use it)."""

    async def test_inserts_basic_hook(self, db) -> None:
        payload = {
            "session_id": "s1",
            "hook_event_name": "PreToolUse",
            "tool_name": "Bash",
            "pid": 1234,
            "source_system": "host.example",
            "cwd": "/proj",
            "permission_mode": "acceptEdits",
            "claude_version": "2.1.117",
        }
        ok = await schema.insert_log_hook(
            db,
            payload=payload,
            received_at=100.0,
            received_by="hook-endpoint",
        )
        assert ok is True

        cursor = await db.execute("SELECT * FROM claude_log_hooks")
        row = await cursor.fetchone()
        assert row is not None
        assert row["pid"] == 1234
        assert row["session_id"] == "s1"
        assert row["event_name"] == "PreToolUse"
        assert row["tool_name"] == "Bash"
        assert row["source_system"] == "host.example"
        assert row["cwd"] == "/proj"
        assert row["permission_mode"] == "acceptEdits"
        assert row["claude_version"] == "2.1.117"
        assert row["received_by"] == "hook-endpoint"

    async def test_returns_false_without_pid(self, db) -> None:
        payload = {"session_id": "s1", "hook_event_name": "Stop"}
        ok = await schema.insert_log_hook(
            db,
            payload=payload,
            received_at=100.0,
            received_by="hook-endpoint",
        )
        assert ok is False

        cursor = await db.execute("SELECT count(*) AS n FROM claude_log_hooks")
        row = await cursor.fetchone()
        assert row["n"] == 0

    async def test_entrypoint_param_stored(self, db) -> None:
        """entrypoint is the only v2 field not in the payload — caller supplies."""
        payload = {
            "session_id": "s1",
            "hook_event_name": "PreToolUse",
            "pid": 1234,
        }
        await schema.insert_log_hook(
            db,
            payload=payload,
            received_at=100.0,
            received_by="hook-endpoint",
            entrypoint="vscode",
        )
        cursor = await db.execute("SELECT entrypoint FROM claude_log_hooks")
        row = await cursor.fetchone()
        assert row["entrypoint"] == "vscode"

    async def test_empty_string_agent_id_stored_as_null(self, db) -> None:
        """Wire payloads use '' for missing agent_id; v2 stores NULL."""
        payload = {
            "session_id": "s1",
            "hook_event_name": "PreToolUse",
            "agent_id": "",
            "pid": 1234,
        }
        await schema.insert_log_hook(
            db,
            payload=payload,
            received_at=100.0,
            received_by="hook-endpoint",
        )
        cursor = await db.execute("SELECT agent_id FROM claude_log_hooks")
        row = await cursor.fetchone()
        assert row["agent_id"] is None


class TestInsertLogStatusline:
    """Direct unit tests for the canonical statusline inserter."""

    async def test_inserts_full_payload(self, db) -> None:
        payload = {
            "session_id": "s1",
            "pid": 1234,
            "source_system": "host.example",
            "cwd": "/proj",
            "version": "2.1.117",
            "workspace": {"project_dir": "/proj"},
            "model": {"id": "claude-opus-4-7[1m]", "display_name": "Opus 4.7"},
            "cost": {
                "total_cost_usd": 1.5,
                "total_duration_ms": 60000,
                "total_api_duration_ms": 12000,
                "total_lines_added": 10,
                "total_lines_removed": 2,
            },
            "context_window": {
                "total_input_tokens": 1000,
                "total_output_tokens": 500,
                "used_percentage": 25.0,
                "context_window_size": 1000000,
                "current_usage": {
                    "cache_read_input_tokens": 800,
                    "cache_creation_input_tokens": 300,
                },
            },
            "exceeds_200k_tokens": False,
        }
        ok = await schema.insert_log_statusline(
            db,
            payload=payload,
            received_at=100.0,
            received_by="statusline-endpoint",
        )
        assert ok is True

        cursor = await db.execute("SELECT * FROM claude_log_statuslines")
        row = await cursor.fetchone()
        assert row is not None
        assert row["pid"] == 1234
        assert row["source_system"] == "host.example"
        assert row["model_id"] == "claude-opus-4-7[1m]"
        assert row["model_name"] == "Opus 4.7"
        assert row["claude_version"] == "2.1.117"
        assert row["project_dir"] == "/proj"
        assert row["cost_usd"] == 1.5
        assert row["duration_seconds"] == 60.0
        assert row["api_duration_seconds"] == 12.0
        assert row["context_used_pct"] == 25.0
        assert row["cache_read_tokens"] == 800
        assert row["cache_creation_tokens"] == 300
        assert row["lines_added"] == 10
        assert row["received_by"] == "statusline-endpoint"

    async def test_returns_false_without_pid(self, db) -> None:
        payload = {"session_id": "s1"}
        ok = await schema.insert_log_statusline(
            db,
            payload=payload,
            received_at=100.0,
            received_by="statusline-endpoint",
        )
        assert ok is False

    async def test_raw_payload_preserved_when_passed(self, db) -> None:
        """The migration path passes original raw_payload bytes for provenance."""
        payload = {"session_id": "s1", "pid": 1234}
        original = '{"session_id": "s1", "pid": 1234, "extra": "preserved"}'
        await schema.insert_log_statusline(
            db,
            payload=payload,
            received_at=100.0,
            received_by="statusline-endpoint",
            raw_payload=original,
        )
        cursor = await db.execute("SELECT raw_payload FROM claude_log_statuslines")
        row = await cursor.fetchone()
        assert row["raw_payload"] == original


class TestReplayIdempotency:
    async def test_skips_when_log_hooks_populated(self, db) -> None:
        # Pre-populate v2 table directly
        await db.execute(
            "INSERT INTO claude_log_hooks (pid, session_id, event_name, "
            "received_at) VALUES (?, ?, ?, ?)",
            (1234, "s1", "PreToolUse", 100.0),
        )
        await db.commit()

        # Add a v1 row that *would* replay if not skipped
        payload = {
            "session_id": "s2",
            "hook_event_name": "Stop",
            "pid": 5678,
            "source_system": "host.example",
            "cwd": "/proj",
        }
        await db.execute(
            "INSERT INTO claude_events (session_id, event_name, cwd, "
            "received_at, raw_payload) VALUES (?, ?, ?, ?, ?)",
            ("s2", "Stop", "/proj", 200.0, json.dumps(payload)),
        )
        await db.commit()

        result = await schema.replay_v1_to_v2_logs(db)
        assert result == {"hooks": 0, "statuslines": 0}

        cursor = await db.execute("SELECT count(*) AS n FROM claude_log_hooks")
        row = await cursor.fetchone()
        assert row["n"] == 1  # only the pre-populated row

    async def test_runs_when_both_tables_empty(self, db) -> None:
        # Both tables are empty (just initialized); trivial case
        result = await schema.replay_v1_to_v2_logs(db)
        assert result == {"hooks": 0, "statuslines": 0}  # no v1 rows to replay
