# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for usage limits fetching and DB persistence."""

import json
import time
from pathlib import Path
from unittest.mock import patch

import pytest

from agentpulse.db import close_db, init_db
from agentpulse.platforms.claude import limits, schema


@pytest.fixture
async def db(tmp_path: Path):
    conn = await init_db(db_path=tmp_path / "test.db")
    yield conn
    await close_db()


@pytest.fixture(autouse=True)
def _reset_limits_state() -> None:
    limits.reset_state()


_SAMPLE_API_RESPONSE = {
    "five_hour": {
        "utilization": 25.0,
        "resets_at": "2026-04-12T23:00:00+00:00",
    },
    "seven_day": {
        "utilization": 8.0,
        "resets_at": "2026-04-19T13:00:00+00:00",
    },
    "extra_usage": {
        "is_enabled": False,
        "monthly_limit": None,
        "used_credits": None,
        "utilization": None,
    },
}


class TestGetLimits:
    async def test_returns_none_when_no_token_and_no_history(self, db) -> None:
        with patch.object(limits, "_read_token", return_value=None):
            result = await limits.get_limits(db)
        assert result is None

    async def test_fetches_and_stores_in_db(self, db) -> None:
        with (
            patch.object(limits, "_read_token", return_value="token"),
            patch.object(limits, "_fetch_from_api", return_value=_SAMPLE_API_RESPONSE),
        ):
            result = await limits.get_limits(db)

        assert result is not None
        assert result["available"] is True
        assert result["five_hour"]["utilization"] == 25.0
        assert result["age_seconds"] < 1.0
        assert result["stale"] is False
        assert "refresh_after" in result
        assert result["refresh_after"] > result["fetched_at"]

        # Verify it's in the DB
        row = await schema.get_latest_limits(db)
        assert row is not None
        stored = json.loads(row["raw_response"])
        assert stored["five_hour"]["utilization"] == 25.0

    async def test_returns_cached_within_ttl(self, db) -> None:
        with (
            patch.object(limits, "_read_token", return_value="token"),
            patch.object(limits, "_fetch_from_api", return_value=_SAMPLE_API_RESPONSE),
        ):
            await limits.get_limits(db)

        # Second call should not hit the API
        with patch.object(
            limits,
            "_fetch_from_api",
            side_effect=RuntimeError("should not call"),
        ):
            result = await limits.get_limits(db)

        assert result is not None
        assert result["stale"] is False

    async def test_returns_stale_on_failure(self, db) -> None:
        # Seed with a row
        await schema.insert_limits(
            db,
            fetched_at=time.time() - 300,
            raw_response=json.dumps(_SAMPLE_API_RESPONSE),
        )
        limits._last_attempt_at = 0

        with (
            patch.object(limits, "_read_token", return_value="token"),
            patch.object(limits, "_fetch_from_api", return_value=None),
        ):
            result = await limits.get_limits(db)

        assert result is not None
        assert result["stale"] is True
        assert result["age_seconds"] > 200

    async def test_inserts_new_rows_for_history(self, db) -> None:
        with (
            patch.object(limits, "_read_token", return_value="token"),
            patch.object(limits, "_fetch_from_api", return_value=_SAMPLE_API_RESPONSE),
        ):
            await limits.get_limits(db)

        # Force TTL expiry and fetch again with different data
        latest = await schema.get_latest_limits(db)
        assert latest is not None
        await db.execute(
            "UPDATE claude_limits SET fetched_at = ? WHERE id = ?",
            (time.time() - 300, latest["id"]),
        )
        await db.commit()
        limits._last_attempt_at = 0
        limits._cached_limits = None

        updated = {
            **_SAMPLE_API_RESPONSE,
            "five_hour": {"utilization": 50.0, "resets_at": "x"},
        }
        with (
            patch.object(limits, "_read_token", return_value="token"),
            patch.object(limits, "_fetch_from_api", return_value=updated),
        ):
            await limits.get_limits(db)

        history = await schema.get_limits_history(db)
        assert len(history) == 2

    async def test_extra_usage_conversion(self, db) -> None:
        api_response = {
            "extra_usage": {
                "is_enabled": True,
                "monthly_limit": 5000,
                "used_credits": 1234,
                "utilization": 24.68,
            },
        }
        with (
            patch.object(limits, "_read_token", return_value="token"),
            patch.object(limits, "_fetch_from_api", return_value=api_response),
        ):
            result = await limits.get_limits(db)

        assert result["extra_usage"]["monthly_limit_usd"] == 50.0
        assert result["extra_usage"]["used_credits_usd"] == 12.34
