# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Query helpers backing /api/v2 endpoints.

Layered into sub-modules by sub-domain:

- ``log`` — raw log reads (filtered + paginated SELECTs).
- ``enrich`` — IdEnricher: per-request cache for derived process/epoch ids
  on raw log rows.
- ``sessions`` — session / epoch / agent derivation.
- ``processes`` — process derivation (layered on top of sessions).

Public API is re-exported here so callers do
``from agentpulse.api.v2 import queries`` and use ``queries.X`` as before.
"""

from agentpulse.api.v2.queries.enrich import IdEnricher
from agentpulse.api.v2.queries.log import (
    get_log_hooks,
    get_log_pid_deaths,
    get_log_statuslines,
)
from agentpulse.api.v2.queries.processes import get_process_by_id, get_processes
from agentpulse.api.v2.queries.sessions import get_session_by_id, get_sessions

__all__ = [
    "IdEnricher",
    "get_log_hooks",
    "get_log_pid_deaths",
    "get_log_statuslines",
    "get_process_by_id",
    "get_processes",
    "get_session_by_id",
    "get_sessions",
]
