# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Instance windowing — handles PID reuse correctly.

A (pid, source_system, cwd) tuple may correspond to multiple distinct
process instances over time (PID reuse). Each instance is a contiguous
span of activity bounded by claude_log_pid_deaths rows for the tuple.

Used by:
- processes.py — `_instance_windows` for per-instance enumeration
- enrich.py — `_instance_started_at_for` for per-row process_id derivation
- pid_watcher.py — same lookup at broadcast time

Sentinels: time-range bounds use plain large/negative numbers when
"unbounded" — SQLite parameter binding doesn't naturally express infinity,
so the helpers translate None to -1.0 / 9e18 internally. Real timestamps
are post-2025 epoch seconds, comfortably between those bounds.
"""

import aiosqlite

_NO_LOWER = -1.0
_NO_UPPER = 9e18


async def _max_death_observed_at_before(
    db: aiosqlite.Connection,
    *,
    pid: int,
    source_system: str,
    cwd: str,
    t: float,
) -> float | None:
    """Latest claude_log_pid_deaths.observed_at strictly < t for this tuple."""
    cursor = await db.execute(
        """
        SELECT MAX(observed_at) AS m FROM claude_log_pid_deaths
        WHERE pid = ? AND source_system = ? AND cwd = ? AND observed_at < ?
        """,
        (pid, source_system, cwd, t),
    )
    row = await cursor.fetchone()
    if row is None or row["m"] is None:
        return None
    return float(row["m"])


async def _earliest_activity_in_range(
    db: aiosqlite.Connection,
    *,
    pid: int,
    source_system: str,
    cwd: str,
    after: float | None,
    until: float | None,
) -> float | None:
    """MIN(received_at) across both log tables where received_at is in (after, until].

    after=None → no lower bound. until=None → no upper bound. Returns None
    when there's no activity in the range.
    """
    after_val = after if after is not None else _NO_LOWER
    until_val = until if until is not None else _NO_UPPER
    cursor = await db.execute(
        """
        SELECT MIN(t) AS m FROM (
            SELECT received_at AS t FROM claude_log_hooks
            WHERE pid = ? AND source_system = ? AND cwd = ?
                  AND received_at > ? AND received_at <= ?
            UNION ALL
            SELECT received_at AS t FROM claude_log_statuslines
            WHERE pid = ? AND source_system = ? AND cwd = ?
                  AND received_at > ? AND received_at <= ?
        )
        """,
        (
            pid,
            source_system,
            cwd,
            after_val,
            until_val,
            pid,
            source_system,
            cwd,
            after_val,
            until_val,
        ),
    )
    row = await cursor.fetchone()
    if row is None or row["m"] is None:
        return None
    return float(row["m"])


async def _instance_started_at_for(
    db: aiosqlite.Connection,
    *,
    pid: int,
    source_system: str,
    cwd: str,
    received_at: float,
) -> float | None:
    """Earliest activity in the instance that contains a row at received_at.

    Step 1: latest death observed_at < received_at (None if no prior death).
    Step 2: earliest activity > that death (or earliest of all if None).

    Returns None for the edge case of a tuple with only death rows and no
    activity (shouldn't happen in practice — deaths are always observed
    against a process that had activity).
    """
    prior_death = await _max_death_observed_at_before(
        db, pid=pid, source_system=source_system, cwd=cwd, t=received_at
    )
    return await _earliest_activity_in_range(
        db,
        pid=pid,
        source_system=source_system,
        cwd=cwd,
        after=prior_death,
        until=None,
    )


async def _instance_windows(
    db: aiosqlite.Connection,
    *,
    pid: int,
    source_system: str,
    cwd: str,
) -> list[dict]:
    """Enumerate all instance windows for the tuple.

    Each returned dict has:
    - prior_death_observed_at: float | None  — exclusive lower bound
    - started_at: float                       — earliest activity in window
    - ended_at: float | None                  — closing death (None = alive)

    Windows with no activity in their range are skipped — they represent
    death-without-activity which would be malformed data.
    """
    deaths_cursor = await db.execute(
        """
        SELECT observed_at FROM claude_log_pid_deaths
        WHERE pid = ? AND source_system = ? AND cwd = ?
        ORDER BY observed_at
        """,
        (pid, source_system, cwd),
    )
    death_times = [r["observed_at"] for r in await deaths_cursor.fetchall()]

    windows: list[dict] = []
    prior_death: float | None = None
    boundaries: list[float | None] = list(death_times) + [None]
    for boundary in boundaries:
        started = await _earliest_activity_in_range(
            db,
            pid=pid,
            source_system=source_system,
            cwd=cwd,
            after=prior_death,
            until=boundary,
        )
        if started is not None:
            windows.append(
                {
                    "prior_death_observed_at": prior_death,
                    "started_at": started,
                    "ended_at": boundary,
                }
            )
        prior_death = boundary
    return windows
