# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Per-request id enrichment for raw log rows.

`IdEnricher.process_id` is per-row: each row's process_id depends on the
*instance* the row belongs to, which depends on its received_at relative
to surrounding claude_log_pid_deaths. Cache key is the resolved instance
start, so multiple rows in the same instance share a single cache entry.

Epoch derivation uses (session_id, pid) which doesn't suffer from PID
reuse — session_ids don't reuse — so `epoch_id` keeps its tuple-MIN
shape.
"""

import aiosqlite

from agentpulse.api.v2.ids import derive_epoch_id, derive_process_id
from agentpulse.api.v2.queries._instance import _instance_started_at_for


async def _earliest_for_epoch_tuple(
    db: aiosqlite.Connection,
    *,
    session_id: str,
    pid: int,
    source_system: str,
    cwd: str,
) -> float:
    cursor = await db.execute(
        """
        SELECT MIN(t) AS m FROM (
            SELECT received_at AS t FROM claude_log_hooks
            WHERE session_id = ? AND pid = ? AND source_system = ? AND cwd = ?
            UNION ALL
            SELECT received_at AS t FROM claude_log_statuslines
            WHERE session_id = ? AND pid = ? AND source_system = ? AND cwd = ?
        )
        """,
        (
            session_id,
            pid,
            source_system,
            cwd,
            session_id,
            pid,
            source_system,
            cwd,
        ),
    )
    row = await cursor.fetchone()
    return float(row["m"]) if row and row["m"] is not None else 0.0


class IdEnricher:
    """Per-request cache for process_id / epoch_id of raw log rows."""

    def __init__(self, db: aiosqlite.Connection) -> None:
        self._db = db
        self._proc: dict[tuple, str] = {}
        self._epoch: dict[tuple, str] = {}

    async def process_id(
        self,
        *,
        pid: int,
        source_system: str,
        cwd: str,
        received_at: float,
    ) -> str:
        """Resolve the row's instance, hash its instance-local start.

        Two DB queries on cache miss (find prior death, find earliest
        activity since). Cache key is the resolved instance start so
        multiple rows in the same instance reuse the cached hash.
        """
        instance_start = await _instance_started_at_for(
            self._db,
            pid=pid,
            source_system=source_system,
            cwd=cwd,
            received_at=received_at,
        )
        # Defensive fallback: if there's no activity at all (shouldn't happen
        # for a row we just fetched), use the row's own received_at.
        if instance_start is None:
            instance_start = received_at
        key = (pid, source_system, cwd, instance_start)
        if key not in self._proc:
            self._proc[key] = derive_process_id(
                source_system=source_system,
                pid=pid,
                cwd=cwd,
                earliest_received_at=instance_start,
            )
        return self._proc[key]

    async def epoch_id(
        self, *, session_id: str, pid: int, source_system: str, cwd: str
    ) -> str:
        key = (session_id, pid, source_system, cwd)
        if key not in self._epoch:
            earliest = await _earliest_for_epoch_tuple(
                self._db,
                session_id=session_id,
                pid=pid,
                source_system=source_system,
                cwd=cwd,
            )
            self._epoch[key] = derive_epoch_id(
                session_id=session_id,
                pid=pid,
                source_system=source_system,
                cwd=cwd,
                earliest_received_at=earliest,
            )
        return self._epoch[key]
