# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Per-request id enrichment for raw log rows.

The /log/hooks and /log/statuslines endpoints return per-row dicts with
process_id / epoch_id appended. Computing those needs a "what's the
earliest row for this identity" lookup, which we cache per request.
"""

import aiosqlite

from agentpulse.api.v2.ids import derive_epoch_id, derive_process_id


async def _earliest_for_process_tuple(
    db: aiosqlite.Connection, *, pid: int, source_system: str, cwd: str
) -> float:
    cursor = await db.execute(
        """
        SELECT MIN(t) AS m FROM (
            SELECT received_at AS t FROM claude_log_hooks
            WHERE pid = ? AND source_system = ? AND cwd = ?
            UNION ALL
            SELECT received_at AS t FROM claude_log_statuslines
            WHERE pid = ? AND source_system = ? AND cwd = ?
        )
        """,
        (pid, source_system, cwd, pid, source_system, cwd),
    )
    row = await cursor.fetchone()
    return float(row["m"]) if row and row["m"] is not None else 0.0


async def _earliest_for_epoch_tuple(
    db: aiosqlite.Connection,
    *,
    session_id: str,
    pid: int,
    source_system: str,
    cwd: str,
) -> float:
    cursor = await db.execute(
        """
        SELECT MIN(t) AS m FROM (
            SELECT received_at AS t FROM claude_log_hooks
            WHERE session_id = ? AND pid = ? AND source_system = ? AND cwd = ?
            UNION ALL
            SELECT received_at AS t FROM claude_log_statuslines
            WHERE session_id = ? AND pid = ? AND source_system = ? AND cwd = ?
        )
        """,
        (
            session_id,
            pid,
            source_system,
            cwd,
            session_id,
            pid,
            source_system,
            cwd,
        ),
    )
    row = await cursor.fetchone()
    return float(row["m"]) if row and row["m"] is not None else 0.0


class IdEnricher:
    """Per-request cache for process_id / epoch_id of raw log rows."""

    def __init__(self, db: aiosqlite.Connection) -> None:
        self._db = db
        self._proc: dict[tuple, str] = {}
        self._epoch: dict[tuple, str] = {}

    async def process_id(self, *, pid: int, source_system: str, cwd: str) -> str:
        key = (pid, source_system, cwd)
        if key not in self._proc:
            earliest = await _earliest_for_process_tuple(
                self._db, pid=pid, source_system=source_system, cwd=cwd
            )
            self._proc[key] = derive_process_id(
                source_system=source_system,
                pid=pid,
                cwd=cwd,
                earliest_received_at=earliest,
            )
        return self._proc[key]

    async def epoch_id(
        self, *, session_id: str, pid: int, source_system: str, cwd: str
    ) -> str:
        key = (session_id, pid, source_system, cwd)
        if key not in self._epoch:
            earliest = await _earliest_for_epoch_tuple(
                self._db,
                session_id=session_id,
                pid=pid,
                source_system=source_system,
                cwd=cwd,
            )
            self._epoch[key] = derive_epoch_id(
                session_id=session_id,
                pid=pid,
                source_system=source_system,
                cwd=cwd,
                earliest_received_at=earliest,
            )
        return self._epoch[key]
