# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Raw log reads — filtered + paginated SELECTs against a single log table.

Returns list[dict] mirroring the table column shape directly. No derived ids
here; consumers that want process_id / epoch_id wire through ``enrich``.
"""

import aiosqlite


def _build_where(filters: list[tuple[str, object]]) -> tuple[str, list[object]]:
    """Build a WHERE clause from (column = ?, value) pairs, skipping None values."""
    clauses: list[str] = []
    params: list[object] = []
    for clause, value in filters:
        if value is None:
            continue
        clauses.append(clause)
        params.append(value)
    where = ("WHERE " + " AND ".join(clauses)) if clauses else ""
    return where, params


async def get_log_hooks(
    db: aiosqlite.Connection,
    *,
    since: float | None = None,
    until: float | None = None,
    session_id: str | None = None,
    pid: int | None = None,
    source_system: str | None = None,
    cwd: str | None = None,
    agent_id: str | None = None,
    event_name: str | None = None,
    tool_name: str | None = None,
    limit: int = 100,
    offset: int = 0,
) -> list[dict]:
    """Filtered + paginated read of claude_log_hooks. Ordered by id ASC."""
    where, params = _build_where(
        [
            ("received_at >= ?", since),
            ("received_at <= ?", until),
            ("session_id = ?", session_id),
            ("pid = ?", pid),
            ("source_system = ?", source_system),
            ("cwd = ?", cwd),
            ("agent_id = ?", agent_id),
            ("event_name = ?", event_name),
            ("tool_name = ?", tool_name),
        ]
    )
    sql = f"SELECT * FROM claude_log_hooks {where} ORDER BY id LIMIT ? OFFSET ?"
    cursor = await db.execute(sql, [*params, limit, offset])
    rows = await cursor.fetchall()
    return [dict(r) for r in rows]


async def get_log_statuslines(
    db: aiosqlite.Connection,
    *,
    since: float | None = None,
    until: float | None = None,
    session_id: str | None = None,
    pid: int | None = None,
    source_system: str | None = None,
    cwd: str | None = None,
    limit: int = 100,
    offset: int = 0,
) -> list[dict]:
    """Filtered + paginated read of claude_log_statuslines. Ordered by id ASC."""
    where, params = _build_where(
        [
            ("received_at >= ?", since),
            ("received_at <= ?", until),
            ("session_id = ?", session_id),
            ("pid = ?", pid),
            ("source_system = ?", source_system),
            ("cwd = ?", cwd),
        ]
    )
    sql = f"SELECT * FROM claude_log_statuslines {where} ORDER BY id LIMIT ? OFFSET ?"
    cursor = await db.execute(sql, [*params, limit, offset])
    rows = await cursor.fetchall()
    return [dict(r) for r in rows]


async def get_log_pid_deaths(
    db: aiosqlite.Connection,
    *,
    since: float | None = None,
    until: float | None = None,
    pid: int | None = None,
    source_system: str | None = None,
    cwd: str | None = None,
    limit: int = 100,
    offset: int = 0,
) -> list[dict]:
    """Filtered + paginated read of claude_log_pid_deaths. Ordered by id ASC.

    Time bounds apply to observed_at (the watcher-observation timestamp),
    not received_at — pid-deaths are observation-sourced, not wire-sourced.
    """
    where, params = _build_where(
        [
            ("observed_at >= ?", since),
            ("observed_at <= ?", until),
            ("pid = ?", pid),
            ("source_system = ?", source_system),
            ("cwd = ?", cwd),
        ]
    )
    sql = f"SELECT * FROM claude_log_pid_deaths {where} ORDER BY id LIMIT ? OFFSET ?"
    cursor = await db.execute(sql, [*params, limit, offset])
    rows = await cursor.fetchall()
    return [dict(r) for r in rows]


async def get_log_api_limits(
    db: aiosqlite.Connection,
    *,
    since: float | None = None,
    until: float | None = None,
    limit: int = 100,
    offset: int = 0,
) -> list[dict]:
    """Filtered + paginated read of claude_log_api_limits. Ordered by id ASC.

    Account-scoped — no pid/source_system/cwd filters. since/until bound
    received_at.
    """
    where, params = _build_where(
        [
            ("received_at >= ?", since),
            ("received_at <= ?", until),
        ]
    )
    sql = f"SELECT * FROM claude_log_api_limits {where} ORDER BY id LIMIT ? OFFSET ?"
    cursor = await db.execute(sql, [*params, limit, offset])
    rows = await cursor.fetchall()
    return [dict(r) for r in rows]
