# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Session, epoch, and agent derivation.

Session is the natural unit; epochs are (session_id, pid) spans within a
session, agents are subagents within a session. Helpers used by both this
module and ``processes`` live in ``_helpers``.
"""

import aiosqlite

from agentpulse.api.v2.ids import derive_epoch_id, derive_process_id
from agentpulse.api.v2.queries._helpers import (
    active_agent_states,
    agents_for_session,
    latest_hook_for_session,
)
from agentpulse.api.v2.queries._instance import _instance_windows
from agentpulse.api.v2.state import compute_effective_state, derive_state

_NO_LOWER = -1.0
_NO_UPPER = 9e18


async def _latest_statusline_for_session(
    db: aiosqlite.Connection, *, session_id: str
) -> dict | None:
    cursor = await db.execute(
        """
        SELECT * FROM claude_log_statuslines
        WHERE session_id = ?
        ORDER BY received_at DESC, id DESC LIMIT 1
        """,
        (session_id,),
    )
    row = await cursor.fetchone()
    return dict(row) if row else None


# ---- session + epoch derivation ---------------------------------------------


async def _session_ids_all(db: aiosqlite.Connection) -> list[str]:
    cursor = await db.execute("""
        SELECT session_id FROM claude_log_hooks
        UNION
        SELECT session_id FROM claude_log_statuslines
        """)
    rows = await cursor.fetchall()
    return [r["session_id"] for r in rows]


async def _session_window(
    db: aiosqlite.Connection, *, session_id: str
) -> tuple[float, float] | None:
    cursor = await db.execute(
        """
        SELECT MIN(t) AS started_at, MAX(t) AS last_activity_at FROM (
            SELECT received_at AS t FROM claude_log_hooks WHERE session_id = ?
            UNION ALL
            SELECT received_at AS t FROM claude_log_statuslines WHERE session_id = ?
        )
        """,
        (session_id, session_id),
    )
    row = await cursor.fetchone()
    if row is None or row["started_at"] is None:
        return None
    return float(row["started_at"]), float(row["last_activity_at"])


async def _epochs_for_session(
    db: aiosqlite.Connection, *, session_id: str
) -> list[dict]:
    """One epoch per distinct (session_id, pid). UNIONs hooks + statuslines
    so a session that has only statuslines (statusline-discovered) still
    yields its open epoch.

    started_at = MIN(received_at) across both tables in the (session_id, pid)
    span — same input IdEnricher.epoch_id uses, so epoch_id is consistent
    whether produced from session detail or from a raw log row.

    ended_at = the matching claude_log_pid_deaths.observed_at when one
    exists for the (pid, source_system, cwd) tuple; otherwise None for an
    alive epoch.
    """
    cursor = await db.execute(
        """
        SELECT pid, source_system, cwd,
               MIN(received_at) AS started_at,
               MAX(received_at) AS last_activity_at,
               SUM(is_hook) AS event_count
        FROM (
            SELECT pid, source_system, cwd, received_at, 1 AS is_hook
            FROM claude_log_hooks WHERE session_id = ?
            UNION ALL
            SELECT pid, source_system, cwd, received_at, 0 AS is_hook
            FROM claude_log_statuslines WHERE session_id = ?
        )
        GROUP BY pid, source_system, cwd
        ORDER BY started_at
        """,
        (session_id, session_id),
    )
    rows = [dict(r) for r in await cursor.fetchall()]
    if not rows:
        return []

    epochs: list[dict] = []
    for r in rows:
        # Entrypoint travels with each hook event in v2 — pull from the
        # first hook in this epoch. Statusline-only epochs have no
        # entrypoint until a hook arrives.
        cursor = await db.execute(
            """
            SELECT entrypoint FROM claude_log_hooks
            WHERE session_id = ? AND pid = ?
            ORDER BY received_at, id LIMIT 1
            """,
            (session_id, r["pid"]),
        )
        ep_row = await cursor.fetchone()
        entrypoint = ep_row["entrypoint"] if ep_row else None

        # ended_at: take the latest pid_death for the (pid, source, cwd)
        # tuple whose observed_at is at-or-after this epoch's last activity
        # (i.e. the death that closed this instance). Earlier deaths belong
        # to other reuse instances on the same tuple.
        cursor = await db.execute(
            """
            SELECT MIN(observed_at) AS m FROM claude_log_pid_deaths
            WHERE pid = ? AND source_system = ? AND cwd = ?
                  AND observed_at >= ?
            """,
            (r["pid"], r["source_system"], r["cwd"], r["last_activity_at"]),
        )
        d_row = await cursor.fetchone()
        ended_at = float(d_row["m"]) if d_row and d_row["m"] is not None else None

        epoch_id = derive_epoch_id(
            session_id=session_id,
            pid=r["pid"],
            source_system=r["source_system"],
            cwd=r["cwd"],
            earliest_received_at=r["started_at"],
        )
        process_id = derive_process_id(
            source_system=r["source_system"],
            pid=r["pid"],
            cwd=r["cwd"],
            earliest_received_at=r["started_at"],
        )
        epochs.append(
            {
                "epoch_id": epoch_id,
                "session_id": session_id,
                "process_id": process_id,
                "pid": r["pid"],
                "source_system": r["source_system"],
                "cwd": r["cwd"],
                "entrypoint": entrypoint,
                "started_at": r["started_at"],
                "ended_at": ended_at,
                "event_count": int(r["event_count"]) if r["event_count"] else 0,
            }
        )
    return epochs


async def _derive_session(db: aiosqlite.Connection, *, session_id: str) -> dict | None:
    win = await _session_window(db, session_id=session_id)
    if win is None:
        return None
    started_at, last_activity_at = win

    latest_hook = await latest_hook_for_session(db, session_id=session_id)
    latest_sl = await _latest_statusline_for_session(db, session_id=session_id)

    # Current epoch identity = the (pid, source_system, cwd) of the latest
    # event source. Hook beats statusline because hooks define epoch
    # boundaries; fall back to the statusline if no hooks yet.
    current = latest_hook or latest_sl
    if current is None:
        return None
    pid = current["pid"]
    source_system = current["source_system"]
    cwd = current["cwd"]

    # Earliest received_at for this (session_id, pid) — defines the epoch's id
    # and, for processes the session belongs to, the process_id.
    cursor = await db.execute(
        """
        SELECT MIN(t) AS earliest FROM (
            SELECT received_at AS t FROM claude_log_hooks
            WHERE session_id = ? AND pid = ?
            UNION ALL
            SELECT received_at AS t FROM claude_log_statuslines
            WHERE session_id = ? AND pid = ?
        )
        """,
        (session_id, pid, session_id, pid),
    )
    row = await cursor.fetchone()
    earliest = (
        float(row["earliest"]) if row and row["earliest"] is not None else started_at
    )

    process_id = derive_process_id(
        source_system=source_system,
        pid=pid,
        cwd=cwd,
        earliest_received_at=earliest,
    )

    # ended_at: from a SessionEnd hook for this session (any pid)
    cursor = await db.execute(
        """
        SELECT received_at FROM claude_log_hooks
        WHERE session_id = ? AND event_name = 'SessionEnd'
        ORDER BY received_at DESC LIMIT 1
        """,
        (session_id,),
    )
    end_row = await cursor.fetchone()
    ended_at = float(end_row["received_at"]) if end_row else None

    last_event = (latest_hook or {}).get("event_name")
    last_tool = (latest_hook or {}).get("tool_name")
    last_event_at = (latest_hook or {}).get("received_at")

    session_state: str | None = None
    if latest_hook is not None:
        session_state = derive_state(
            latest_hook["event_name"], tool_name=latest_hook["tool_name"] or ""
        )
    agents = await agents_for_session(db, session_id=session_id)
    derived_state = compute_effective_state(session_state, active_agent_states(agents))

    cursor = await db.execute(
        "SELECT COUNT(DISTINCT pid) AS n FROM claude_log_hooks WHERE session_id = ?",
        (session_id,),
    )
    row = await cursor.fetchone()
    epoch_count = int(row["n"]) if row else 0

    total_cost_usd = await _session_total_cost(db, session_id=session_id)
    cost_by_day = await _session_cost_by_day(db, session_id=session_id)

    return {
        "session_id": session_id,
        "platform": "claude",
        "process_id": process_id,
        "pid": pid,
        "source_system": source_system,
        "cwd": cwd,
        "started_at": started_at,
        "last_activity_at": last_activity_at,
        "ended_at": ended_at,
        "last_event": last_event,
        "last_tool": last_tool,
        "last_event_at": last_event_at,
        "context_used_pct": (latest_sl or {}).get("context_used_pct"),
        "context_window_size": (latest_sl or {}).get("context_window_size"),
        "model_id": (latest_sl or {}).get("model_id"),
        "model_name": (latest_sl or {}).get("model_name"),
        "agent_count": len(agents),
        "derived_state": derived_state,
        "epoch_count": epoch_count,
        "total_cost_usd": total_cost_usd,
        "cost_by_day": cost_by_day,
        "epochs": None,
        "agents": None,
    }


async def _session_process_instances(
    db: aiosqlite.Connection, *, session_id: str
) -> list[dict]:
    """Enumerate process instances that contributed to this session.

    For each (pid, source_system, cwd) tuple the session touches, expand
    into instance windows bounded by claude_log_pid_deaths rows. PID reuse
    within the same session — same tuple appearing twice in history with a
    death in between — yields two instances; cost_usd is a fresh counter
    per process so each must aggregate separately.
    """
    cursor = await db.execute(
        """
        SELECT DISTINCT pid, source_system, cwd FROM claude_log_statuslines
        WHERE session_id = ? AND cost_usd IS NOT NULL
        """,
        (session_id,),
    )
    tuples = await cursor.fetchall()

    instances: list[dict] = []
    for t in tuples:
        windows = await _instance_windows(
            db,
            pid=t["pid"],
            source_system=t["source_system"],
            cwd=t["cwd"],
        )
        for w in windows:
            instances.append(
                {
                    "pid": t["pid"],
                    "source_system": t["source_system"],
                    "cwd": t["cwd"],
                    "prior_death_observed_at": w["prior_death_observed_at"],
                    "ended_at": w["ended_at"],
                }
            )
    return instances


async def _session_total_cost(db: aiosqlite.Connection, *, session_id: str) -> float:
    """Sum of MAX(cost_usd) per process instance in the session.

    Instance-windowed grouping handles PID reuse: a tuple that died and was
    reused yields two instances, each contributing its own MAX. Without
    windowing, one MAX would capture only the higher of the two counters
    and silently undercount the session total.
    """
    instances = await _session_process_instances(db, session_id=session_id)
    total = 0.0
    for inst in instances:
        after = (
            inst["prior_death_observed_at"]
            if inst["prior_death_observed_at"] is not None
            else _NO_LOWER
        )
        until = inst["ended_at"] if inst["ended_at"] is not None else _NO_UPPER
        cursor = await db.execute(
            """
            SELECT MAX(cost_usd) AS m FROM claude_log_statuslines
            WHERE session_id = ?
                  AND pid = ? AND source_system = ? AND cwd = ?
                  AND received_at > ? AND received_at <= ?
            """,
            (
                session_id,
                inst["pid"],
                inst["source_system"],
                inst["cwd"],
                after,
                until,
            ),
        )
        row = await cursor.fetchone()
        if row is not None and row["m"] is not None:
            total += float(row["m"])
    return round(total, 6)


async def _session_cost_by_day(
    db: aiosqlite.Connection, *, session_id: str
) -> dict[str, float]:
    """Per-day cost increments across all process instances in this session.

    Within a single instance, daily delta = MAX(cost_usd today) - MAX(cost_usd
    through yesterday). Session daily total = sum of per-instance deltas.
    Server local time bucketing matches queries/processes._cost_by_day.
    Instance-windowed grouping preserves correctness across PID reuse: each
    (pid, source_system, cwd) span bounded by deaths is its own counter.
    """
    instances = await _session_process_instances(db, session_id=session_id)
    by_day: dict[str, float] = {}

    for inst in instances:
        after = (
            inst["prior_death_observed_at"]
            if inst["prior_death_observed_at"] is not None
            else _NO_LOWER
        )
        until = inst["ended_at"] if inst["ended_at"] is not None else _NO_UPPER
        cursor = await db.execute(
            """
            SELECT date(received_at, 'unixepoch', 'localtime') AS day,
                   MAX(cost_usd) AS day_max
            FROM claude_log_statuslines
            WHERE session_id = ?
                  AND pid = ? AND source_system = ? AND cwd = ?
                  AND received_at > ? AND received_at <= ?
                  AND cost_usd IS NOT NULL
            GROUP BY day
            ORDER BY day
            """,
            (
                session_id,
                inst["pid"],
                inst["source_system"],
                inst["cwd"],
                after,
                until,
            ),
        )
        prev_max = 0.0
        for r in await cursor.fetchall():
            day_max = float(r["day_max"]) if r["day_max"] is not None else prev_max
            delta = day_max - prev_max
            by_day[r["day"]] = by_day.get(r["day"], 0.0) + delta
            prev_max = day_max

    return {d: round(v, 6) for d, v in by_day.items()}


async def get_sessions(
    db: aiosqlite.Connection,
    *,
    active_only: bool = False,
    process_id: str | None = None,
    since: float | None = None,
) -> list[dict]:
    """List sessions derived from log tables. Ordered by last_activity_at DESC."""
    sids = await _session_ids_all(db)
    sessions: list[dict] = []
    for sid in sids:
        sess = await _derive_session(db, session_id=sid)
        if sess is None:
            continue
        if active_only and sess["ended_at"] is not None:
            continue
        if process_id is not None and sess["process_id"] != process_id:
            continue
        if since is not None and sess["last_activity_at"] < since:
            continue
        sessions.append(sess)
    sessions.sort(key=lambda s: s["last_activity_at"], reverse=True)
    return sessions


async def get_session_by_id(
    db: aiosqlite.Connection, *, session_id: str
) -> dict | None:
    """Single session by id, with epochs[] and agents[] populated."""
    sess = await _derive_session(db, session_id=session_id)
    if sess is None:
        return None
    sess["epochs"] = await _epochs_for_session(db, session_id=session_id)
    sess["agents"] = await agents_for_session(db, session_id=session_id)
    return sess


async def get_session_epochs(
    db: aiosqlite.Connection, *, session_id: str
) -> list[dict] | None:
    """Standalone epoch list for a session.

    Returns None when the session is unknown (no hook or statusline rows).
    Returns the same list shape as session detail's nested epochs[].
    """
    win = await _session_window(db, session_id=session_id)
    if win is None:
        return None
    return await _epochs_for_session(db, session_id=session_id)
