# Generated By: Claude Code (Claude Opus 4.6)
"""Session discovery — scan ~/.claude/sessions/*.json for Claude Code sessions."""

import asyncio
import json
import logging
import platform
import time
from pathlib import Path

import aiosqlite
import psutil

from agentpulse import config
from agentpulse.platforms.claude import schema
from agentpulse.websocket import manager

logger = logging.getLogger(__name__)


def discover_sessions(
    *,
    sessions_dir: Path | None = None,
) -> list[dict]:
    """Read all session files and return parsed session dicts.

    Each dict has keys: pid, session_id, cwd, started_at, entrypoint.
    """
    directory = sessions_dir or config.SESSIONS_DIR

    if not directory.is_dir():
        logger.debug("sessions directory does not exist path=%s", directory)
        return []

    sessions: list[dict] = []
    for session_file in directory.glob("*.json"):
        try:
            data = json.loads(session_file.read_text(encoding="utf-8"))
            if not isinstance(data, dict):
                continue
            pid = data.get("pid", 0)
            session_id = data.get("sessionId", "")
            if pid and session_id:
                sessions.append(
                    {
                        "pid": pid,
                        "session_id": session_id,
                        "cwd": data.get("cwd", ""),
                        "started_at": data.get("startedAt", 0),
                        "entrypoint": data.get("entrypoint", "cli"),
                    }
                )
        except (json.JSONDecodeError, OSError) as exc:
            logger.warning(
                "failed to read session file=%s error=%s",
                session_file,
                exc,
            )

    return sessions


def validate_pid(*, pid: int) -> bool:
    """Check if a process is alive and is a Claude process."""
    try:
        if not psutil.pid_exists(pid):
            return False
        proc = psutil.Process(pid)
        name = proc.name().lower()
        return "claude" in name
    except (psutil.NoSuchProcess, psutil.AccessDenied):
        return False


def detect_branch(*, cwd: str) -> str:
    """Return the active git branch for a directory.

    Reads .git/HEAD directly — no subprocess needed.
    Returns empty string if not a git repo or HEAD is detached.
    """
    try:
        head_path = Path(cwd) / ".git" / "HEAD"
        head_content = head_path.read_text(encoding="utf-8").strip()
        if not head_content.startswith("ref: refs/heads/"):
            return ""
        return head_content[len("ref: refs/heads/") :]
    except OSError:
        return ""


async def run_discovery_tick(
    db: "aiosqlite.Connection",
    *,
    sessions_dir: Path | None = None,
) -> list[dict]:
    """Run a full discovery cycle.

    Returns list of newly discovered sessions (for WebSocket broadcast).
    """
    discovered = await asyncio.to_thread(discover_sessions, sessions_dir=sessions_dir)
    logger.debug("discovery tick found %d session files", len(discovered))

    new_sessions: list[dict] = []
    seen_ids: set[str] = set()

    for session in discovered:
        sid = session["session_id"]
        seen_ids.add(sid)

        pid_alive = await asyncio.to_thread(validate_pid, pid=session["pid"])
        branch = await asyncio.to_thread(detect_branch, cwd=session["cwd"])

        existing = await schema.get_session(db, session_id=sid)

        await schema.update_session_discovery(
            db,
            session_id=sid,
            pid=session["pid"],
            cwd=session["cwd"],
            entrypoint=session["entrypoint"],
            started_at=session["started_at"],
            pid_alive=pid_alive,
            branch=branch,
            source_system=platform.node(),
        )

        if existing is None:
            logger.info(
                "new session discovered session=%s pid=%d cwd=%s",
                sid,
                session["pid"],
                session["cwd"],
            )
            new_sessions.append(session)
            await manager.broadcast(
                {
                    "type": "session_discovered",
                    "platform": "claude",
                    "session_id": sid,
                    "event_name": None,
                    "tool_name": None,
                    "agent_id": None,
                    "cwd": session["cwd"],
                    "timestamp": time.time(),
                }
            )

    # Check for sessions that are in DB as alive but not in discovery
    alive_sessions = await schema.get_sessions_needing_pid_check(db)
    for row in alive_sessions:
        sid = row["session_id"]
        if sid in seen_ids:
            continue

        pid_alive = await asyncio.to_thread(validate_pid, pid=row["pid"])
        if not pid_alive:
            logger.info(
                "session pid died session=%s pid=%d",
                sid,
                row["pid"],
            )
            await schema.update_session_pid_alive(db, session_id=sid, pid_alive=False)
            ended_at = time.time()
            await schema.end_session(db, session_id=sid, ended_at=ended_at)
            await manager.broadcast(
                {
                    "type": "session_ended",
                    "platform": "claude",
                    "session_id": sid,
                    "event_name": None,
                    "tool_name": None,
                    "agent_id": None,
                    "cwd": row.get("cwd"),
                    "timestamp": ended_at,
                }
            )

    return new_sessions
