# Generated By: Claude Code (Claude Opus 4.6)
"""Session discovery — PID liveness checks and process inspection."""

import asyncio
import logging
import time

import aiosqlite
import psutil

from agentpulse.platforms.claude import schema
from agentpulse.websocket import manager

logger = logging.getLogger(__name__)

# Known IDE process names → entrypoint values.
_IDE_NAMES: dict[str, str] = {
    "code": "vscode",
    "cursor": "cursor",
    "idea": "jetbrains",
    "idea64": "jetbrains",
    "pycharm": "jetbrains",
    "pycharm64": "jetbrains",
    "webstorm": "jetbrains",
    "webstorm64": "jetbrains",
    "goland": "jetbrains",
    "goland64": "jetbrains",
    "rider": "jetbrains",
    "rider64": "jetbrains",
}


def validate_pid(*, pid: int) -> bool:
    """Check if a process is alive and is a Claude process."""
    try:
        if not psutil.pid_exists(pid):
            return False
        proc = psutil.Process(pid)
        name = proc.name().lower()
        return "claude" in name
    except (psutil.NoSuchProcess, psutil.AccessDenied):
        return False


def detect_entrypoint(*, pid: int) -> str:
    """Determine how Claude Code was launched by examining ancestor processes.

    Walks up the process tree looking for known IDE parent processes.
    Returns 'cli' if no IDE ancestor is found.
    """
    if pid <= 0:
        return "cli"
    try:
        proc = psutil.Process(pid)
        for ancestor in proc.parents():
            name = ancestor.name().lower()
            # Strip .exe suffix for Windows
            if name.endswith(".exe"):
                name = name[:-4]
            entrypoint = _IDE_NAMES.get(name)
            if entrypoint:
                return entrypoint
    except (psutil.NoSuchProcess, psutil.AccessDenied):
        pass
    return "cli"


async def run_discovery_tick(
    db: "aiosqlite.Connection",
) -> None:
    """Run a PID liveness check cycle.

    Sessions are created by hooks — this loop only checks whether
    known-alive sessions have died (PID no longer running).
    """
    alive_sessions = await schema.get_sessions_needing_pid_check(db)
    logger.debug("liveness tick checking %d sessions", len(alive_sessions))

    for row in alive_sessions:
        sid = row["session_id"]
        pid = row["pid"]

        # Hook-only sessions with pid=0 can't be PID-checked.
        # They end via explicit SessionEnd events only.
        if pid == 0:
            continue

        pid_alive = await asyncio.to_thread(validate_pid, pid=pid)
        if not pid_alive:
            logger.info(
                "session pid died session=%s pid=%d",
                sid,
                pid,
            )
            await schema.update_session_pid_alive(db, session_id=sid, pid_alive=False)
            ended_at = time.time()
            await schema.end_session(db, session_id=sid, ended_at=ended_at)
            await manager.broadcast(
                {
                    "type": "session_ended",
                    "platform": "claude",
                    "session_id": sid,
                    "event_name": None,
                    "tool_name": None,
                    "agent_id": None,
                    "cwd": row.get("cwd"),
                    "timestamp": ended_at,
                }
            )
