# Generated By: Claude Code (Claude Opus 4.7)
"""Claude Code launch-context inference via process-tree inspection."""

import psutil

# Known IDE process names → entrypoint values.
_IDE_NAMES: dict[str, str] = {
    "code": "vscode",
    "cursor": "cursor",
    "idea": "jetbrains",
    "idea64": "jetbrains",
    "pycharm": "jetbrains",
    "pycharm64": "jetbrains",
    "webstorm": "jetbrains",
    "webstorm64": "jetbrains",
    "goland": "jetbrains",
    "goland64": "jetbrains",
    "rider": "jetbrains",
    "rider64": "jetbrains",
}


def detect_entrypoint(*, pid: int) -> str:
    """Determine how Claude Code was launched by examining ancestor processes.

    Walks up the process tree looking for known IDE parent processes.
    Returns 'cli' if no IDE ancestor is found.
    """
    if pid <= 0:
        return "cli"
    try:
        proc = psutil.Process(pid)
        for ancestor in proc.parents():
            name = ancestor.name().lower()
            if name.endswith(".exe"):
                name = name[:-4]
            entrypoint = _IDE_NAMES.get(name)
            if entrypoint:
                return entrypoint
    except (psutil.NoSuchProcess, psutil.AccessDenied):
        pass
    return "cli"
