# Generated By: Claude Code (Claude Opus 4.6)
"""Claude Code hook relay endpoint — receives POST /hooks/claude."""

import asyncio
import json
import logging
import time

import aiosqlite
from fastapi import APIRouter, Request, Response

from agentpulse.api.v2.events import (
    broadcast_hook_logged,
    broadcast_statusline_logged,
)
from agentpulse.api.v2.queries import IdEnricher
from agentpulse.db import get_db
from agentpulse.events import (
    broadcast_hook_event,
    broadcast_session_discovered,
    broadcast_statusline_update,
)
from agentpulse.platforms.claude.discovery import detect_entrypoint
from agentpulse.platforms.claude.models import ClaudeHookPayload
from agentpulse.platforms.claude import schema
from agentpulse.timeutil import local_midnight_epoch

logger = logging.getLogger(__name__)

router = APIRouter()


async def _handle_agent_event(
    db: aiosqlite.Connection,
    payload: ClaudeHookPayload,
    *,
    event: str,
    received_at: float,
) -> None:
    """Register or end an agent based on the hook event."""
    if not payload.agent_id:
        return
    if event == "SubagentStop":
        logger.info(
            "agent ended session=%s agent=%s",
            payload.session_id,
            payload.agent_id,
        )
        await schema.end_agent(db, agent_id=payload.agent_id, ended_at=received_at)
    else:
        logger.debug(
            "agent event session=%s agent=%s type=%s event=%s",
            payload.session_id,
            payload.agent_id,
            payload.agent_type,
            event,
        )
        await schema.upsert_agent(
            db,
            agent_id=payload.agent_id,
            session_id=payload.session_id,
            agent_type=payload.agent_type,
            last_event=event,
            last_tool=payload.tool_name or None,
            last_event_at=received_at,
        )


@router.post("/hooks/claude")
async def receive_hook(payload: ClaudeHookPayload, request: Request) -> dict:
    """Process an incoming Claude Code hook event."""
    db = await get_db()
    received_at = time.time()
    event = payload.hook_event_name
    # v1 stores Pydantic-normalized JSON (existing behavior); v2 stores the
    # original wire bytes so optional-field defaults aren't injected.
    raw = json.dumps(payload.model_dump())
    raw_wire = (await request.body()).decode("utf-8")

    logger.debug(
        "hook received session=%s event=%s tool=%s agent=%s",
        payload.session_id,
        event,
        payload.tool_name,
        payload.agent_id or "-",
    )

    existing = await schema.get_session(db, session_id=payload.session_id)
    is_new = existing is None
    is_resumed = (
        existing is not None
        and event != "SessionEnd"
        and (
            existing.get("ended_at") is not None or not existing.get("pid_alive", True)
        )
    )

    entrypoint = await asyncio.to_thread(detect_entrypoint, pid=payload.pid)

    try:
        await schema.upsert_session(
            db,
            session_id=payload.session_id,
            pid=payload.pid,
            cwd=payload.cwd,
            entrypoint=entrypoint,
            started_at=int(received_at * 1000),
            last_event=event,
            last_tool=payload.tool_name or None,
            last_event_at=received_at,
            source_system=payload.source_system,
        )

        await _handle_agent_event(db, payload, event=event, received_at=received_at)

        if event == "SessionEnd":
            logger.info("session ended session=%s", payload.session_id)
            await schema.end_session(
                db, session_id=payload.session_id, ended_at=received_at
            )

        await schema.insert_event(
            db,
            session_id=payload.session_id,
            agent_id=payload.agent_id or None,
            event_name=event,
            tool_name=payload.tool_name or None,
            cwd=payload.cwd,
            received_at=received_at,
            raw_payload=raw,
        )

        # v2 dual-write — derive payload from the wire body so optional-field
        # defaults from Pydantic don't leak into raw_payload.
        try:
            wire_payload = json.loads(raw_wire) if raw_wire else {}
        except json.JSONDecodeError:
            wire_payload = {}
        v2_log_id = await schema.insert_log_hook(
            db,
            payload=wire_payload,
            received_at=received_at,
            received_by="hook-endpoint",
            entrypoint=entrypoint,
            raw_payload=raw_wire,
        )
        await db.commit()
    except aiosqlite.Error:
        logger.exception(
            "database error processing hook session=%s event=%s",
            payload.session_id,
            event,
        )
        return {"status": "error", "reason": "database error"}

    if is_new or is_resumed:
        if is_new:
            logger.info(
                "new session from hook session=%s pid=%d cwd=%s",
                payload.session_id,
                payload.pid,
                payload.cwd,
            )
        else:
            logger.info(
                "session resumed from hook session=%s pid=%d cwd=%s",
                payload.session_id,
                payload.pid,
                payload.cwd,
            )
        await broadcast_session_discovered(
            session_id=payload.session_id,
            cwd=payload.cwd or None,
            timestamp=received_at,
        )

    await broadcast_hook_event(
        session_id=payload.session_id,
        event_name=event,
        tool_name=payload.tool_name or None,
        agent_id=payload.agent_id or None,
        cwd=payload.cwd or None,
        timestamp=received_at,
    )

    if v2_log_id is not None:
        enricher = IdEnricher(db)
        process_id = await enricher.process_id(
            pid=payload.pid,
            source_system=payload.source_system,
            cwd=payload.cwd,
            received_at=received_at,
        )
        epoch_id = await enricher.epoch_id(
            session_id=payload.session_id,
            pid=payload.pid,
            source_system=payload.source_system,
            cwd=payload.cwd,
        )
        await broadcast_hook_logged(
            log_id=v2_log_id,
            process_id=process_id,
            epoch_id=epoch_id,
            pid=payload.pid,
            source_system=payload.source_system,
            cwd=payload.cwd,
            session_id=payload.session_id,
            agent_id=payload.agent_id or None,
            event_name=event,
            tool_name=payload.tool_name or None,
            agent_type=payload.agent_type or None,
            permission_mode=wire_payload.get("permission_mode") or None,
            entrypoint=entrypoint,
            claude_version=wire_payload.get("claude_version") or None,
            received_at=received_at,
            received_by="hook-endpoint",
        )

    return {"status": "ok"}


@router.post("/statusline/claude")
async def receive_statusline(body: dict, request: Request) -> dict:
    """Receive statusline data from Claude Code.

    Stores the full payload with extracted numerics and enriches
    the session with cost/context/model/token data.
    """
    db = await get_db()
    received_at = time.time()
    raw = json.dumps(body)
    raw_wire = (await request.body()).decode("utf-8")

    session_id = body.get("session_id", "")
    if not session_id:
        return {"status": "ignored", "reason": "no session_id"}

    workspace = body.get("workspace") or {}
    cwd = workspace.get("project_dir") or body.get("cwd") or ""
    pid = body.get("pid", 0)
    source_system = body.get("source_system", "")

    existing = await schema.get_session(db, session_id=session_id)
    is_new = existing is None
    is_resumed = (
        existing is not None
        and existing.get("last_event") != "SessionEnd"
        and (
            existing.get("ended_at") is not None or not existing.get("pid_alive", True)
        )
    )

    if is_new or is_resumed:
        entrypoint = "cli"
        if pid:
            entrypoint = await asyncio.to_thread(detect_entrypoint, pid=pid)
        await schema.upsert_session(
            db,
            session_id=session_id,
            pid=pid,
            cwd=cwd,
            entrypoint=entrypoint,
            started_at=int(received_at * 1000),
            source_system=source_system,
        )
        if is_new:
            logger.info(
                "new session from statusline session=%s cwd=%s",
                session_id,
                cwd,
            )
        else:
            logger.info(
                "session resumed from statusline session=%s cwd=%s",
                session_id,
                cwd,
            )
        await broadcast_session_discovered(
            session_id=session_id,
            cwd=cwd or None,
            timestamp=received_at,
        )

    cost = body.get("cost") or {}
    ctx = body.get("context_window") or {}
    current_usage = ctx.get("current_usage") or {}
    model = body.get("model") or {}

    cost_usd = cost.get("total_cost_usd")
    total_input_tokens = ctx.get("total_input_tokens")
    total_output_tokens = ctx.get("total_output_tokens")
    context_used_pct = ctx.get("used_percentage")
    context_window_size = ctx.get("context_window_size")
    cache_read_tokens = current_usage.get("cache_read_input_tokens")
    cache_creation_tokens = current_usage.get("cache_creation_input_tokens")
    duration_ms = cost.get("total_duration_ms")
    api_duration_ms = cost.get("total_api_duration_ms")
    lines_added = cost.get("total_lines_added")
    lines_removed = cost.get("total_lines_removed")
    model_name = model.get("display_name")

    try:
        await schema.insert_statusline(
            db,
            session_id=session_id,
            received_at=received_at,
            cost_usd=cost_usd,
            total_input_tokens=total_input_tokens,
            total_output_tokens=total_output_tokens,
            context_used_pct=context_used_pct,
            context_window_size=context_window_size,
            cache_read_tokens=cache_read_tokens,
            cache_creation_tokens=cache_creation_tokens,
            duration_ms=duration_ms,
            api_duration_ms=api_duration_ms,
            lines_added=lines_added,
            lines_removed=lines_removed,
            model_name=model_name,
            raw_payload=raw,
        )

        await schema.update_session_statusline(
            db,
            session_id=session_id,
            cost_usd=cost_usd,
            context_used_pct=context_used_pct,
            model_name=model_name,
            total_input_tokens=total_input_tokens,
            total_output_tokens=total_output_tokens,
            lines_added=lines_added,
            lines_removed=lines_removed,
        )

        # v2 dual-write
        v2_log_id = await schema.insert_log_statusline(
            db,
            payload=body,
            received_at=received_at,
            received_by="statusline-endpoint",
            raw_payload=raw_wire,
        )
        await db.commit()
    except aiosqlite.Error:
        logger.exception(
            "database error processing statusline session=%s",
            session_id,
        )
        return {"status": "error", "reason": "database error"}

    logger.debug(
        "statusline received session=%s cost=%.2f ctx=%s%% model=%s",
        session_id,
        cost_usd or 0,
        context_used_pct or "?",
        model_name or "?",
    )

    prior_cost_usd = await schema.get_prior_cost(
        db, session_id=session_id, before_ts=local_midnight_epoch()
    )

    await broadcast_statusline_update(
        session_id=session_id,
        cost_usd=cost_usd,
        prior_cost_usd=prior_cost_usd,
        context_used_pct=context_used_pct,
        model_name=model_name,
        total_input_tokens=total_input_tokens,
        total_output_tokens=total_output_tokens,
        lines_added=lines_added,
        lines_removed=lines_removed,
        timestamp=received_at,
    )

    if v2_log_id is not None:
        enricher = IdEnricher(db)
        process_id = await enricher.process_id(
            pid=pid,
            source_system=source_system,
            cwd=cwd,
            received_at=received_at,
        )
        epoch_id = await enricher.epoch_id(
            session_id=session_id,
            pid=pid,
            source_system=source_system,
            cwd=cwd,
        )
        await broadcast_statusline_logged(
            log_id=v2_log_id,
            process_id=process_id,
            epoch_id=epoch_id,
            pid=pid,
            source_system=source_system,
            cwd=cwd,
            session_id=session_id,
            project_dir=workspace.get("project_dir") or None,
            model_id=model.get("id") or None,
            model_name=model_name,
            claude_version=body.get("version") or None,
            cost_usd=cost_usd,
            total_input_tokens=total_input_tokens,
            total_output_tokens=total_output_tokens,
            context_used_pct=context_used_pct,
            context_window_size=context_window_size,
            cache_read_tokens=cache_read_tokens,
            cache_creation_tokens=cache_creation_tokens,
            duration_seconds=(duration_ms / 1000.0) if duration_ms else None,
            api_duration_seconds=(
                (api_duration_ms / 1000.0) if api_duration_ms else None
            ),
            lines_added=lines_added,
            lines_removed=lines_removed,
            exceeds_200k_tokens=bool(body.get("exceeds_200k_tokens")),
            received_at=received_at,
            received_by="statusline-endpoint",
        )

    return {"status": "ok"}


@router.post("/costs/claude")
async def receive_costs() -> Response:
    """Stub for future cost data ingestion."""
    return Response(status_code=501, content="Not implemented")
