# Generated By: Claude Code (Claude Opus 4.6)
"""Claude Code hook relay endpoint — receives POST /hooks/claude."""

import json
import logging
import time

import aiosqlite
from fastapi import APIRouter, Response

from agentpulse.db import get_db
from agentpulse.platforms.claude.models import ClaudeHookPayload
from agentpulse.platforms.claude import schema
from agentpulse.websocket import manager

logger = logging.getLogger(__name__)

router = APIRouter()

_WS_TYPE_MAP: dict[str, str] = {
    "SessionEnd": "session_ended",
    "SubagentStart": "agent_started",
    "SubagentStop": "agent_stopped",
}


async def _handle_agent_event(
    db: aiosqlite.Connection,
    payload: ClaudeHookPayload,
    *,
    event: str,
    received_at: float,
) -> None:
    """Register or end an agent based on the hook event."""
    if not payload.agent_id:
        return
    if event == "SubagentStop":
        logger.info(
            "agent ended session=%s agent=%s",
            payload.session_id,
            payload.agent_id,
        )
        await schema.end_agent(db, agent_id=payload.agent_id, ended_at=received_at)
    else:
        logger.debug(
            "agent event session=%s agent=%s type=%s event=%s",
            payload.session_id,
            payload.agent_id,
            payload.agent_type,
            event,
        )
        await schema.upsert_agent(
            db,
            agent_id=payload.agent_id,
            session_id=payload.session_id,
            agent_type=payload.agent_type,
            last_event=event,
            last_tool=payload.tool_name or None,
            last_event_at=received_at,
        )


async def _broadcast_event(
    payload: ClaudeHookPayload,
    *,
    event: str,
    received_at: float,
) -> None:
    """Broadcast a hook event to all WebSocket clients."""
    ws_type = _WS_TYPE_MAP.get(event, "hook_event")
    await manager.broadcast(
        {
            "type": ws_type,
            "platform": "claude",
            "session_id": payload.session_id,
            "event_name": event,
            "tool_name": payload.tool_name or None,
            "agent_id": payload.agent_id or None,
            "cwd": payload.cwd or None,
            "timestamp": received_at,
        }
    )


@router.post("/hooks/claude")
async def receive_hook(payload: ClaudeHookPayload) -> dict:
    """Process an incoming Claude Code hook event."""
    db = await get_db()
    received_at = time.time()
    event = payload.hook_event_name
    raw = json.dumps(payload.model_dump())

    logger.debug(
        "hook received session=%s event=%s tool=%s agent=%s",
        payload.session_id,
        event,
        payload.tool_name,
        payload.agent_id or "-",
    )

    await schema.upsert_session(
        db,
        session_id=payload.session_id,
        cwd=payload.cwd,
        last_event=event,
        last_tool=payload.tool_name or None,
        last_event_at=received_at,
        source_system=payload.source_system,
    )

    await _handle_agent_event(db, payload, event=event, received_at=received_at)

    if event == "SessionEnd":
        logger.info("session ended session=%s", payload.session_id)
        await schema.end_session(
            db, session_id=payload.session_id, ended_at=received_at
        )

    await schema.insert_event(
        db,
        session_id=payload.session_id,
        agent_id=payload.agent_id or None,
        event_name=event,
        tool_name=payload.tool_name or None,
        cwd=payload.cwd,
        received_at=received_at,
        raw_payload=raw,
    )

    await _broadcast_event(payload, event=event, received_at=received_at)

    return {"status": "ok"}


@router.post("/costs/claude")
async def receive_costs() -> Response:
    """Stub for future cost data ingestion."""
    return Response(status_code=501, content="Not implemented")
