# Generated By: Claude Code (Claude Opus 4.6)
"""Claude Code hook relay endpoint — receives POST /hooks/claude."""

import asyncio
import json
import logging
import time

import aiosqlite
from fastapi import APIRouter, Response

from agentpulse.db import get_db
from agentpulse.platforms.claude.discovery import detect_entrypoint
from agentpulse.platforms.claude.models import ClaudeHookPayload
from agentpulse.platforms.claude import schema
from agentpulse.websocket import manager

logger = logging.getLogger(__name__)

router = APIRouter()

_WS_TYPE_MAP: dict[str, str] = {
    "SessionEnd": "session_ended",
    "SubagentStart": "agent_started",
    "SubagentStop": "agent_stopped",
}


async def _handle_agent_event(
    db: aiosqlite.Connection,
    payload: ClaudeHookPayload,
    *,
    event: str,
    received_at: float,
) -> None:
    """Register or end an agent based on the hook event."""
    if not payload.agent_id:
        return
    if event == "SubagentStop":
        logger.info(
            "agent ended session=%s agent=%s",
            payload.session_id,
            payload.agent_id,
        )
        await schema.end_agent(db, agent_id=payload.agent_id, ended_at=received_at)
    else:
        logger.debug(
            "agent event session=%s agent=%s type=%s event=%s",
            payload.session_id,
            payload.agent_id,
            payload.agent_type,
            event,
        )
        await schema.upsert_agent(
            db,
            agent_id=payload.agent_id,
            session_id=payload.session_id,
            agent_type=payload.agent_type,
            last_event=event,
            last_tool=payload.tool_name or None,
            last_event_at=received_at,
        )


async def _broadcast_event(
    payload: ClaudeHookPayload,
    *,
    event: str,
    received_at: float,
) -> None:
    """Broadcast a hook event to all WebSocket clients."""
    ws_type = _WS_TYPE_MAP.get(event, "hook_event")
    await manager.broadcast(
        {
            "type": ws_type,
            "platform": "claude",
            "session_id": payload.session_id,
            "event_name": event,
            "tool_name": payload.tool_name or None,
            "agent_id": payload.agent_id or None,
            "cwd": payload.cwd or None,
            "timestamp": received_at,
        }
    )


@router.post("/hooks/claude")
async def receive_hook(payload: ClaudeHookPayload) -> dict:
    """Process an incoming Claude Code hook event."""
    db = await get_db()
    received_at = time.time()
    event = payload.hook_event_name
    raw = json.dumps(payload.model_dump())

    logger.debug(
        "hook received session=%s event=%s tool=%s agent=%s",
        payload.session_id,
        event,
        payload.tool_name,
        payload.agent_id or "-",
    )

    existing = await schema.get_session(db, session_id=payload.session_id)

    entrypoint = await asyncio.to_thread(detect_entrypoint, pid=payload.pid)

    await schema.upsert_session(
        db,
        session_id=payload.session_id,
        pid=payload.pid,
        cwd=payload.cwd,
        entrypoint=entrypoint,
        started_at=int(received_at * 1000),
        last_event=event,
        last_tool=payload.tool_name or None,
        last_event_at=received_at,
        source_system=payload.source_system,
    )

    if existing is None:
        logger.info(
            "new session from hook session=%s pid=%d cwd=%s",
            payload.session_id,
            payload.pid,
            payload.cwd,
        )
        await manager.broadcast(
            {
                "type": "session_discovered",
                "platform": "claude",
                "session_id": payload.session_id,
                "event_name": None,
                "tool_name": None,
                "agent_id": None,
                "cwd": payload.cwd or None,
                "timestamp": received_at,
            }
        )

    await _handle_agent_event(db, payload, event=event, received_at=received_at)

    if event == "SessionEnd":
        logger.info("session ended session=%s", payload.session_id)
        await schema.end_session(
            db, session_id=payload.session_id, ended_at=received_at
        )

    await schema.insert_event(
        db,
        session_id=payload.session_id,
        agent_id=payload.agent_id or None,
        event_name=event,
        tool_name=payload.tool_name or None,
        cwd=payload.cwd,
        received_at=received_at,
        raw_payload=raw,
    )

    await _broadcast_event(payload, event=event, received_at=received_at)

    return {"status": "ok"}


@router.post("/statusline/claude")
async def receive_statusline(body: dict) -> dict:
    """Receive statusline data from Claude Code.

    Stores the full payload with extracted numerics and enriches
    the session with cost/context/model/token data.
    """
    db = await get_db()
    received_at = time.time()
    raw = json.dumps(body)

    session_id = body.get("session_id", "")
    if not session_id:
        return {"status": "ignored", "reason": "no session_id"}

    workspace = body.get("workspace") or {}
    cwd = workspace.get("project_dir") or body.get("cwd") or ""
    pid = body.get("pid", 0)
    source_system = body.get("source_system", "")

    existing = await schema.get_session(db, session_id=session_id)
    if existing is None:
        entrypoint = "cli"
        if pid:
            entrypoint = await asyncio.to_thread(detect_entrypoint, pid=pid)
        await schema.upsert_session(
            db,
            session_id=session_id,
            pid=pid,
            cwd=cwd,
            entrypoint=entrypoint,
            started_at=int(received_at * 1000),
            source_system=source_system,
        )
        logger.info(
            "new session from statusline session=%s cwd=%s",
            session_id,
            cwd,
        )
        await manager.broadcast(
            {
                "type": "session_discovered",
                "platform": "claude",
                "session_id": session_id,
                "event_name": None,
                "tool_name": None,
                "agent_id": None,
                "cwd": cwd or None,
                "timestamp": received_at,
            }
        )

    cost = body.get("cost") or {}
    ctx = body.get("context_window") or {}
    current_usage = ctx.get("current_usage") or {}
    model = body.get("model") or {}

    cost_usd = cost.get("total_cost_usd")
    total_input_tokens = ctx.get("total_input_tokens")
    total_output_tokens = ctx.get("total_output_tokens")
    context_used_pct = ctx.get("used_percentage")
    context_window_size = ctx.get("context_window_size")
    cache_read_tokens = current_usage.get("cache_read_input_tokens")
    cache_creation_tokens = current_usage.get("cache_creation_input_tokens")
    duration_ms = cost.get("total_duration_ms")
    api_duration_ms = cost.get("total_api_duration_ms")
    lines_added = cost.get("total_lines_added")
    lines_removed = cost.get("total_lines_removed")
    model_name = model.get("display_name")

    await schema.insert_statusline(
        db,
        session_id=session_id,
        received_at=received_at,
        cost_usd=cost_usd,
        total_input_tokens=total_input_tokens,
        total_output_tokens=total_output_tokens,
        context_used_pct=context_used_pct,
        context_window_size=context_window_size,
        cache_read_tokens=cache_read_tokens,
        cache_creation_tokens=cache_creation_tokens,
        duration_ms=duration_ms,
        api_duration_ms=api_duration_ms,
        lines_added=lines_added,
        lines_removed=lines_removed,
        model_name=model_name,
        raw_payload=raw,
    )

    await schema.update_session_statusline(
        db,
        session_id=session_id,
        cost_usd=cost_usd,
        context_used_pct=context_used_pct,
        model_name=model_name,
        total_input_tokens=total_input_tokens,
        total_output_tokens=total_output_tokens,
        lines_added=lines_added,
        lines_removed=lines_removed,
    )

    logger.debug(
        "statusline received session=%s cost=%.2f ctx=%s%% model=%s",
        session_id,
        cost_usd or 0,
        context_used_pct or "?",
        model_name or "?",
    )

    await manager.broadcast(
        {
            "type": "statusline_update",
            "platform": "claude",
            "session_id": session_id,
            "cost_usd": cost_usd,
            "context_used_pct": context_used_pct,
            "model_name": model_name,
            "total_input_tokens": total_input_tokens,
            "total_output_tokens": total_output_tokens,
            "lines_added": lines_added,
            "lines_removed": lines_removed,
            "timestamp": received_at,
        }
    )

    return {"status": "ok"}


@router.post("/costs/claude")
async def receive_costs() -> Response:
    """Stub for future cost data ingestion."""
    return Response(status_code=501, content="Not implemented")
