# Generated By: Claude Code (Claude Opus 4.7)
"""Fetch Claude Code usage limits from the Anthropic OAuth API.

Each successful fetch inserts one row into claude_log_api_limits
and broadcasts api_limits_logged on /ws/v2. Completely inert when
disabled via config (fetch_limits=false).
"""

import json
import logging
import time
import urllib.request

import aiosqlite

from agentpulse import config
from agentpulse.api.v2.events import broadcast_api_limits_logged
from agentpulse.platforms.claude import schema

logger = logging.getLogger(__name__)

_API_URL = "https://api.anthropic.com/api/oauth/usage"
_CREDENTIALS_PATH = config.CLAUDE_HOME / ".credentials.json"
_TTL_SECONDS = 120
_MAX_BACKOFF_SECONDS = 3600

_last_attempt_at: float = 0.0
_consecutive_failures: int = 0


def _read_token() -> str | None:
    """Read the OAuth access token from Claude credentials."""
    try:
        data = json.loads(_CREDENTIALS_PATH.read_text(encoding="utf-8"))
        token: str | None = data.get("claudeAiOauth", {}).get("accessToken")
        return token
    except (json.JSONDecodeError, OSError, KeyError):
        return None


def _fetch_from_api(*, token: str) -> dict | None:
    """Fetch usage data from the Anthropic OAuth API."""
    try:
        req = urllib.request.Request(
            _API_URL,
            headers={
                "Authorization": f"Bearer {token}",
                "anthropic-beta": "oauth-2025-04-20",
            },
        )
        resp = urllib.request.urlopen(req, timeout=10)
        data = json.loads(resp.read())
        if isinstance(data, dict):
            return data
    except Exception as exc:
        logger.warning("limits API fetch failed: %s", exc)
    return None


def _backoff_seconds() -> float:
    """Calculate backoff duration based on consecutive failures."""
    if _consecutive_failures == 0:
        return 0.0
    return float(
        min(
            (2**_consecutive_failures) * _TTL_SECONDS,
            _MAX_BACKOFF_SECONDS,
        )
    )


async def _latest_received_at(db: aiosqlite.Connection) -> float:
    """Return the most recent claude_log_api_limits.received_at, or 0.0."""
    cursor = await db.execute(
        "SELECT MAX(received_at) AS ts FROM claude_log_api_limits"
    )
    row = await cursor.fetchone()
    if row is None or row["ts"] is None:
        return 0.0
    return float(row["ts"])


async def get_limits(db: aiosqlite.Connection) -> bool:
    """Refresh OAuth limits if a fetch is due.

    Returns True when a new row was inserted, False otherwise (TTL not
    elapsed, in backoff, no token, or upstream call failed). Safe to
    call from a background loop on a fixed cadence; the function
    self-throttles via TTL + exponential backoff.
    """
    global _last_attempt_at, _consecutive_failures

    now = time.time()
    latest_at = await _latest_received_at(db)
    if latest_at > 0.0 and (now - latest_at) < _TTL_SECONDS:
        return False

    if _consecutive_failures > 0:
        cooldown = _backoff_seconds()
        if (now - _last_attempt_at) < cooldown:
            logger.debug(
                "limits fetch in backoff failures=%d cooldown=%.0fs",
                _consecutive_failures,
                cooldown,
            )
            return False

    token = _read_token()
    if token is None:
        logger.debug("no OAuth token found, limits disabled")
        return False

    _last_attempt_at = now
    raw = _fetch_from_api(token=token)

    if raw is None:
        _consecutive_failures += 1
        logger.warning(
            "limits fetch failed attempts=%d backoff=%.0fs",
            _consecutive_failures,
            _backoff_seconds(),
        )
        return False

    fetched_at = time.time()
    raw_json = json.dumps(raw)
    log_id, fields = await schema.insert_log_api_limits(
        db,
        received_at=fetched_at,
        received_by="limits-fetcher",
        raw_response=raw_json,
    )
    await db.commit()
    _consecutive_failures = 0
    logger.info("limits fetched and stored")

    await broadcast_api_limits_logged(
        log_id=log_id,
        received_at=fetched_at,
        received_by="limits-fetcher",
        **fields,
    )
    return True


def reset_state() -> None:
    """Reset backoff state (for testing)."""
    global _last_attempt_at, _consecutive_failures
    _last_attempt_at = 0.0
    _consecutive_failures = 0
