# Generated By: Claude Code (Claude Opus 4.7)
"""Tests for scripts/install_tray_autostart.py."""

import importlib
import os
from pathlib import Path
from unittest.mock import patch

import pytest


def _reload_mod():  # type: ignore[no-untyped-def]
    mod = importlib.import_module("install_tray_autostart")
    return importlib.reload(mod)


def test_linux_install_writes_desktop_file(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr("sys.platform", "linux")
    fake_home = tmp_path / "home"
    fake_home.mkdir()
    monkeypatch.setattr("pathlib.Path.home", lambda: fake_home)

    mod = _reload_mod()
    exit_code = mod.install(argv=[])

    desktop = fake_home / ".config" / "autostart" / "agentpulse-tray.desktop"
    assert exit_code == 0
    assert desktop.exists()
    content = desktop.read_text()
    assert "agentpulse-tray" in content


def test_linux_uninstall_removes_desktop_file(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr("sys.platform", "linux")
    fake_home = tmp_path / "home"
    fake_home.mkdir()
    monkeypatch.setattr("pathlib.Path.home", lambda: fake_home)
    desktop = fake_home / ".config" / "autostart" / "agentpulse-tray.desktop"
    desktop.parent.mkdir(parents=True)
    desktop.write_text("stub")

    mod = _reload_mod()
    exit_code = mod.uninstall(argv=[])

    assert exit_code == 0
    assert not desktop.exists()


def test_windows_install_creates_shortcut(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr("sys.platform", "win32")
    fake_home = tmp_path / "home"
    fake_appdata = fake_home / "AppData" / "Roaming"
    fake_appdata.mkdir(parents=True)
    monkeypatch.setattr("pathlib.Path.home", lambda: fake_home)
    monkeypatch.setitem(os.environ, "APPDATA", str(fake_appdata))

    mod = _reload_mod()
    monkeypatch.setattr(mod.winutil, "pythonw_path", lambda: "C:\\fake\\pythonw.exe")

    calls: list[list[str]] = []

    def _fake_run(cmd: list[str], **_: object) -> object:
        calls.append(cmd)
        startup = (
            fake_appdata
            / "Microsoft"
            / "Windows"
            / "Start Menu"
            / "Programs"
            / "Startup"
        )
        startup.mkdir(parents=True, exist_ok=True)
        (startup / "AgentPulseTray.lnk").write_text("stub")

        class R:
            returncode = 0
            stderr = ""

        return R()

    with patch("subprocess.run", side_effect=_fake_run):
        exit_code = mod.install(argv=[])

    assert exit_code == 0
    assert any("AgentPulseTray.lnk" in " ".join(c) for c in calls)
    joined = " ".join(calls[0])
    # Regression: target pythonw.exe -m agentpulse.tray, not the
    # pipx console shim.
    assert "pythonw.exe" in joined
    assert "-m agentpulse.tray" in joined
    assert "agentpulse-tray.exe" not in joined
